- README.md
Some organizations will already have the GCloud SDK installed and will want to know what the minimum required version is. In our case, this is really helpful to know what version to upgrade to so we can read the changelog in between and perform any updates for our own FTL test runner (which we'd eventually like to migrate from).
149.0.0 seems to be right as that version introduces the "firebase" namespace which flank now uses (`gcloud firebase test android run...`), and after upgrading to this version tests run and pass.
> document minimum required gcloud sdk version

- cloud_testing/readme.md
Google's new discovery service supports multiple formats. For example:
> https://cloudtrace.googleapis.com/$discovery/swagger2?version=v1
https://cloudtrace.googleapis.com/$discovery/rest?version=v1
> Document new discovery URL

- README.md
This PR add `--fail` which will make curl fail if response code is not 2xx, otherwise curl will happily write something like `404` page to the `--output` file and then `java -jar` will fail with unreadable error :)
Also, changed `-o` and `-L` to their full parameter names so people could better understand what's going on.
> Add --fail to curl recipe, use full parameter names.

- Flank/src/main/java/com/walmart/otto/Flank.java
- Flank/src/main/java/com/walmart/otto/configurator/ConfigReader.java
- README.md
Fixes #53. 
This PR allows user to set gcloud-bucket from free Firebase account and avoid paid plan if it's not required.
> Make gcloud bucket configurable, enables Flank for free Firebase plan.

- Flank/src/main/java/com/walmart/otto/configurator/ConfigReader.java
- Flank/src/main/java/com/walmart/otto/configurator/Configurator.java
- Flank/src/main/java/com/walmart/otto/tools/GcloudTool.java
Fixes #63 
Adds support for the test orchestrator. Can be enabled by the `use-orchestrator` flag in the `config.properties` file.
> add support for --use-orchestrator

- Flank/src/main/java/com/walmart/otto/configurator/ConfigReader.java
- Flank/src/main/java/com/walmart/otto/configurator/Configurator.java
- Flank/src/main/java/com/walmart/otto/tools/GcloudTool.java
Might be useful for some, especially to try newer features/behaviors in the `gcloud beta`.
Can be enabled via the `use-gcloud-beta` flag in the `config.properties` file.
> add support to use gcloud beta

- Flank/src/main/java/com/walmart/otto/shards/ShardExecutor.java
- Flank/src/main/java/com/walmart/otto/tools/GcloudTool.java
- Flank/src/main/java/com/walmart/otto/tools/GsutilTool.java
- Flank/src/main/java/com/walmart/otto/tools/ProcessBuilder.java
Using the same result-dir value causes some results artifacts (video, logcat, etc) to be overwritten because they all have the same name. In this PR we are changing the results-dir format to include the shard so that they will be in separate folders.
We additionally have to change the way we delete the upload app/instrumentation apks because looks like Firebase copies them to the all the result directories.
> Include shard index to results-dir name

- Flank/build.gradle
- Flank/src/main/java/com/walmart/otto/Flank.java
- Flank/src/main/java/com/walmart/otto/configurator/ConfigReader.java
- Flank/src/main/java/com/walmart/otto/configurator/Configurator.java
- Flank/src/main/java/com/walmart/otto/models/Device.java
- Flank/src/main/java/com/walmart/otto/shards/ShardExecutor.java
- Flank/src/main/java/com/walmart/otto/tools/GcloudTool.java
- Flank/src/test/java/com/walmart/otto/models/DeviceTest.java
- README.md
As [the official documentation](https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run), Firebase Test Lab has depretaced the use of `--device-ids`, `--locales`, `--orientations` and `--os-version-ids` in order to accept multiple `--device` entries.
This PR adds the possibility to use the `--device` entries by configuring, on `config.properties` the list of devices configurations.  For example:
```
environment-variables=coverage=true,coverageFile=/sdcard/tempDir/coverage.ec
directories-to-pull=/sdcard
shard-timeout=5
shard-duration=120  
devices=model:Nexus5X;version:23;orientation:portrait;locale:en,\
model:Nexus6P;version:24,\
model:pixel;version:26
numShards=  
shardIndex=
debug-prints=false  
fetch-xml-files=true
fetch-bucket=true
gcloud-path=
gsutil-path=
```
Will …
> Added support for devices specification on config.properties

- Flank/src/main/java/com/walmart/otto/filter/TestFilters.java
- Flank/src/test/java/com/walmart/otto/filter/TestFiltersTest.java
- Flank/src/test/java/com/walmart/otto/filter/TestMethodFixtures.java
This PR fix an issue in which passing the values separated by comma followed by space would not work properly.
> Trim arguments test filters after splitting

- cloud_testing/apis/testing_v1_swagger_2.json
- cloud_testing/kotlin_poc/.gitignore
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/GcTestMatrix.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/GlobalConfig.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/Main.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/MatrixCallable.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/RunConfig.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/TestRunner.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/ToolResultsValue.kt
- cloud_testing/kotlin_poc/src/main/kotlin/task/MergeResults.kt
- cloud_testing/readme.md
I'm working on updating `cloud_testing` to run my suite of ~150 Espresso tests. I created a mock server by converting the API JSON into Swagger. This will allow testing different concurrency techniques (like coroutines) without having to use the real server.
Swagger mock server screenshot:
I found a bug in FTL as part of this work (disabling video recording = 💥 ).
> Cloud testing updates

- cloud_testing/kotlin_poc/src/main/kotlin/ftl/Main.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/util/MatrixState.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/util/StopWatch.kt
Report test execution status instead of matrix status.
**before**
```
pollMatrices
matrix-b5a6sge0q1cw VALIDATING 0m 0s
matrix-b5a6sge0q1cw PENDING 0m 15s
matrix-b5a6sge0q1cw PENDING 0m 30s
matrix-b5a6sge0q1cw PENDING 0m 46s
matrix-b5a6sge0q1cw PENDING 1m 1s
matrix-b5a6sge0q1cw PENDING 1m 16s
matrix-b5a6sge0q1cw PENDING 1m 31s
matrix-b5a6sge0q1cw PENDING 1m 47s
matrix-b5a6sge0q1cw PENDING 2m 2s
matrix-b5a6sge0q1cw PENDING 2m 17s
matrix-b5a6sge0q1cw PENDING 2m 33s
matrix-b5a6sge0q1cw PENDING 2m 48s
matrix-b5a6sge0q1cw FINISHED 3m 3s
```
**after**
```
pollMatrices
0m  0s matrix-2k3bs3s26p24n VALIDATING
0m  6s matrix-2k3bs3s26p24n PENDING
0m 37s matrix-2k3bs3s26p24n Starting attempt 1
0m 37s matrix-2k3bs3s26p24n RUNNING
1m 59s matrix-2k3bs3s26p24n Running instrumentation test. Package: …
```
> Add detailed polling based on gcloud-cli

- Flank/src/main/java/com/walmart/otto/tools/GcloudTool.java
If a gcloud command fails, that means that the build failed. We should
return a -1 error code.
Without this its impossible to know if a single shard failed while all
the other ones succeeded.
Fixes #22
> Report that tests failed if a gcloud command fails.

- cloud_testing/kotlin_poc/flank.yml
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/YamlConfig.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcTestMatrix.kt
- cloud_testing/kotlin_poc/src/test/kotlin/ftl/config/YamlConfigTest.kt
Fix #132 
Ported from Gcloud Python SDK.
> Auto google login

- Flank/src/main/java/com/walmart/otto/configurator/ConfigReader.java
- Flank/src/main/java/com/walmart/otto/configurator/Configurator.java
- Flank/src/main/java/com/walmart/otto/tools/GcloudTool.java
- README.md
There are some issues with firebase test lab caused by play service and
auto-google-login. This adds a flag `disable-google-login` to
config.properties which allows you to disable auto google login.
When the flag is set, `--no-auto-google-login` is added to the command
line arguments to gcloud.
> Add ability to disable google login.

- Flank/src/main/java/com/walmart/otto/configurator/ConfigReader.java
- Flank/src/main/java/com/walmart/otto/configurator/Configurator.java
- Flank/src/main/java/com/walmart/otto/tools/GcloudTool.java
- README.md
[Negative booleans are confusing.](https://www.quora.com/Is-it-bad-practice-to-have-a-negative-boolean-variable-name-like-didntLose-instead-of-didLose)
Also specifies what the default value is, in the README.
> Improve the format for the --no-auto-google-login flag

- README.md
- release_notes.md
Having defaults visible helps people know exactly what is enabled and what they need to customize.
I also changed my username from `sridoodla` -> `doodla`. So some edits for that. :)
> Add defaults for the configuration options to the README

- Flank/src/main/java/com/walmart/otto/tools/GcloudTool.java
- release_notes.md
It seems the format of the time changed from `Test time=8 (secs)`
to `Test time = 8 (secs)`.
Fixes #154
> Fix bug parsing time.

- cloud_testing/xctest_parser/src/test/kotlin/xctest/XctestrunTest.kt
Refs #218, but does not resolve the issue. Tests show that the duplicate
OnlyTestIdentifiers element doesn't seem to be coming from Xctesetrun, which
previously seemed like the mostly candidate.
> Add unit tests for Xctestrun

- cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/YamlConfig.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/run/IosTestRunner.kt
Update validation to allow the gcs path, and skip uploading to gcs if the path
already points to gcs instead of a local zip file.
fix #217
> Allow xctestrunZip to be specified as a gcs path

- cloud_testing/kotlin_poc/src/main/kotlin/ftl/cli/DoctorCommand.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/ios/IosCatalog.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/run/IosTestRunner.kt
- cloud_testing/kotlin_poc/src/test/kotlin/ftl/ios/IosCatalogTest.kt
If supportedVersionIds is null or empty, then don't include it in iosModelIds.
Also add supported method to check if a model/version pair is supported.
Fix #188
> Filter invalid devices from iOS catalog

- cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/YamlConfig.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcIosMatrix.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/run/IosTestRunner.kt
The devices specified in the yaml config are validated against the catalog of
supported ios devices, and passed to the gc api.
Fix #193
> Add device matrix for ios

- cloud_testing/kotlin_poc/.gitignore
- cloud_testing/kotlin_poc/build.gradle.kts
- cloud_testing/kotlin_poc/src/test/kotlin/ftl/MainTest.kt
- cloud_testing/kotlin_poc/src/test/kotlin/ftl/TestArtifact.kt
- cloud_testing/kotlin_poc/src/test/kotlin/ftl/fixtures/flank.ios.yml
- cloud_testing/mock_server/build.gradle.kts
- cloud_testing/mock_server/src/main/kotlin/ftl/Main.kt
While this does not make any assertions along the way, it ensures the process
completes without exception.
This also adds the mock server response for ios device catalog and downloads
temporary fixture build artifacts to tests against.
Fixes #227
> Add end-to-end iOS test

- cloud_testing/kotlin_poc/src/main/kotlin/ftl/cli/RefreshCommand.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/cli/RunCommand.kt
Both the refresh and run command get a -c/--config option for specifying the
flank.yml file to be used. Defaults to old value of "./flank.yml".
> Add cli arg for config file path

- cloud_testing/kotlin_poc/src/main/kotlin/ftl/android/AndroidCatalog.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/json/SavedMatrix.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/reports/CostReport.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/util/Billing.kt
- cloud_testing/kotlin_poc/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
- cloud_testing/kotlin_poc/src/test/kotlin/ftl/ios/IosCatalogTest.kt
- cloud_testing/kotlin_poc/src/test/kotlin/ftl/util/BillingTest.kt
- cloud_testing/mock_server/src/main/kotlin/ftl/Main.kt
Calculate the estimated cost from each execution device based its form
(virtual or physical). This is also summing all devices instead of only looking
at the first.
fix #232
> Update cost estimates by device form

- cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/AndroidConfig.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/IosConfig.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/YamlConfig.kt
- cloud_testing/kotlin_poc/src/main/kotlin/ftl/ios/Xctestrun.kt
- cloud_testing/kotlin_poc/src/test/kotlin/ftl/config/IosConfigTest.kt
- cloud_testing/kotlin_poc/src/test/kotlin/ftl/fixtures/flank2.ios.yml
- cloud_testing/kotlin_poc/src/test/kotlin/ftl/test/util/LocalGcs.kt
iOS requires permission. One way to solve this is by defining a set of grant permission tests that always run at the beginning of each shard. The tests will request and accept all required permissions (for example camera & microphone).
> Always run

- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
Ensure that we find existing result buckets, even if we have a lot of them
> Ensure that we find existing result buckets 

- test_runner/src/main/kotlin/ftl/Main.kt
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/cli/FirebaseCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/CancelCommand.kt
- test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
- test_runner/src/main/kotlin/ftl/gc/GcTestMatrix.kt
- test_runner/src/main/kotlin/ftl/run/GenericTestRunner.kt
- test_runner/src/main/kotlin/ftl/run/TestRunner.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/FirebaseCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/CancelCommandTest.kt
Fix #194 
`flank cancel`
The matrices from the last run are processed. Any matrix with state != FINISHED will be cancelled asynchronously.
> Add flank cancel command to cancel unfinished matrices from the last run

- README.md
- test_runner/flank.ios.yml
- test_runner/src/main/kotlin/ftl/ios/Parse.kt
- test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/flank.ios.gcs.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank.ios.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank2.ios.yml
- test_runner/src/test/kotlin/ftl/ios/ParseTest.kt
- test_runner/src/test/kotlin/ftl/ios/XctestrunTest.kt
- test_runner/src/test/kotlin/ftl/test/util/LocalGcs.kt
- Updated the regular expression used for filter the tests.
- Fix #371
> Fix Swift test throws & Add Xcode 10.1 support

- test_runner/build.gradle.kts
- test_runner/src/main/kotlin/ftl/run/TestRunner.kt
> Fetch artifacts in parallel. Treat warnings as errors

- README.md
- test_runner/src/main/kotlin/ftl/json/MatrixMap.kt
- test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt
- test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/main/kotlin/ftl/run/TestRunner.kt
- test_runner/src/main/kotlin/ftl/util/MatrixState.kt
- test_runner/src/main/kotlin/ftl/util/Outcome.kt
- test_runner/src/main/kotlin/ftl/util/StepOutcome.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/CancelCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/RefreshCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/error_result/matrix_ids.json
- test_runner/src/test/kotlin/ftl/json/MatrixMapTest.kt
- test_runner/src/test/kotlin/ftl/json/SavedMatrixTest.kt
- test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt
- test_runner/src/test/kotlin/ftl/test/util/MockServer.kt
- test_runner/src/test/kotlin/ftl/util/OutcomeTest.kt
- test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
- Improved Exit Code based on the execution outcome and state.
- Updated MatrixResultReport to include additional details.
Sample **MatrixResultReport** Looks like below
```
MatrixResultsReport
0 / 2 (0.00%)
2 matrices failed
Failed matrix:
Matrix Id: matrix-teex1a295m17a
Reason: abortedByUser
Web Link: https://console.firebase.google.com/project/delta-essence-114723/testlab/histories/bh.58317d9cd7ab9ba2/matrices/7994869754124771736/executions/bs.795779ba6b096d51
Failed matrix:
Matrix Id: matrix-iio3vk6eoqwqa
Web Link: https://console.firebase.google.com/project/delta-essence-114723/testlab/histories/bh.58317d9cd7ab9ba2/matrices/6325378892669071099/executions/bs.b6517c0e72b114f1
```
Fix #329
> Improve exit code reporting

- README.md
- test_runner/src/main/kotlin/ftl/util/TestMatrixExtension.kt
- test_runner/src/test/kotlin/ftl/json/SavedMatrixTest.kt
Previously, if a matrix had multiple devices, the link would take you into the details of the first device.
Expected:
Actual:
Now, if there's a single device, it will take you directly to the execution. But if there are multiple devices, it will take you to the root matrix page which lists all the devices.
So, for **ONE** device, you'll still see the execution as before ( second screenshot above ). But for **MULTIPLE** devices, you'll see the matrix base screen ( first screenshot above ).
> Modify the WebLink to point to the matrix root if there are more than one device

- test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/gc/GcTestMatrix.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/main/kotlin/ftl/run/AndroidTestRunner.kt
- test_runner/src/main/kotlin/ftl/run/IosTestRunner.kt
- test_runner/src/main/kotlin/ftl/run/TestRunner.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
`config` and `args` were being synonymously used. But it's confusing to have two terms for the same thing.
> Refactor all references of config to args

- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
> Add android run --app

- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
> --test-targets param

- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/main/kotlin/ftl/reports/xml/JUnitXml.kt
- test_runner/src/main/kotlin/ftl/reports/xml/model/JUnitTestCase.kt
- test_runner/src/main/kotlin/ftl/reports/xml/model/JUnitTestSuite.kt
- test_runner/src/main/kotlin/ftl/shard/Shard.kt
- test_runner/src/test/kotlin/ftl/reports/HtmlErrorReportTest.kt
- test_runner/src/test/kotlin/ftl/reports/xml/JUnitXmlTest.kt
> Fix parsing empty testcase

- release_notes.md
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/shard/Shard.kt
- test_runner/src/main/kotlin/ftl/util/ProgressBar.kt
- test_runner/src/test/kotlin/ftl/util/ProgressBarTest.kt
> Add progress bar when uploading

- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/AndroidGcloudYml.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/config/Device.kt
- test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
> Add --device

- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
> Add --timeout

- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
> Add --async

- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
> Add --xctestrun-file for iOS

- test_runner/build.gradle.kts
To filter default methods annotated with @Test to be treated as runnable test methods
See https://github.com/linkedin/dex-test-parser/issues/20 for more information
> Update DexTestParser to 2.0.1

- README.md
- release_notes.md
- test_runner/build.gradle.kts
- test_runner/src/main/kotlin/com/google/api/client/http/GoogleApiLogger.kt
- test_runner/src/main/kotlin/ftl/Main.kt
- test_runner/src/main/kotlin/ftl/args/yml/GcloudYml.kt
- test_runner/src/main/kotlin/ftl/cli/AuthCommand.kt
- test_runner/src/main/kotlin/ftl/cli/auth/LoginCommand.kt
- test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
- test_runner/src/main/kotlin/ftl/gc/GcAuth.kt
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/http/TimeoutHttpRequestInitializer.kt
- test_runner/src/test/kotlin/ftl/cli/AuthCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/auth/LoginCommandTest.kt
Fix #398 
Flank now allows you to login as a user. Type `flank auth login` and follow the web prompt. User auth is an alternative to using a service account.
> flank auth login

- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt
- test_runner/src/main/kotlin/ftl/args/yml/GcloudYml.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
> Added disableSharding flag

- test_runner/src/main/kotlin/ftl/reports/xml/model/JUnitTestSuite.kt
- test_runner/src/test/kotlin/ftl/fixtures/ftl_junit_xml/ios_large_num.xml
- test_runner/src/test/kotlin/ftl/reports/xml/JUnitXmlTest.kt
> Fix large number merging on iOS

- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/flank.ios.gcs.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank.ios.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank2.ios.yml
> Issue #467: iOS support globs for test-targets

- test_runner/flank.ios.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/main/kotlin/ftl/shard/Shard.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/FlankYmlTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/doctor/DoctorTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/flank.gcs.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank.ios.gcs.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank.ios.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank.local.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank2.ios.yml
- test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
This PR rename testShards parameter to maxTestShards
Fix #490
> Fixes #490 Rename testShards to maxTestShards

- README.md
- docs/smart_flank.md
- release_notes.md
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/YamlDeprecated.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidDoctorCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosDoctorCommand.kt
- test_runner/src/main/kotlin/ftl/doctor/Doctor.kt
- test_runner/src/test/kotlin/ftl/args/yml/YamlDeprecatedTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidDoctorCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosDoctorCommandTest.kt
- test_runner/src/test/kotlin/ftl/doctor/DoctorTest.kt
Print key warnings to console
Auto fix YAML using flank doctor --fix
Error when deprecated keys are no longer supported
Fix #515
> Auto migrate YAML changes

- README.md
- release_notes.md
- test_runner/flank.ios.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt
- test_runner/src/main/kotlin/ftl/args/yml/GcloudYml.kt
- test_runner/src/main/kotlin/ftl/args/yml/YamlDeprecated.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
- test_runner/src/test/kotlin/ftl/args/FlankYmlTest.kt
- test_runner/src/test/kotlin/ftl/args/GcloudYmlTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/yml/YamlDeprecatedTest.kt
- test_runner/src/test/kotlin/ftl/doctor/DoctorTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/flank.gcs.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank.ios.gcs.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank.ios.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank.local.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank2.ios.yml
```
FlankYmlParams
maxTestShards -> max-test-shards
shardTime -> shard-time
repeatTests -> repeat-tests
smartFlankGcsPath -> smart-flank-gcs-path
disableSharding -> disable-sharding
```
> Update to use dash naming on flank yml params

- test_runner/src/main/kotlin/ftl/reports/util/JUnitDedupe.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/main/kotlin/ftl/reports/xml/model/JUnitTestCase.kt
- test_runner/src/main/kotlin/ftl/reports/xml/model/JUnitTestResult.kt
- test_runner/src/main/kotlin/ftl/reports/xml/model/JUnitTestSuite.kt
- test_runner/src/test/kotlin/ftl/reports/utils/JUnitDedupeTest.kt
- test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
Fix #456 
Read in JUnitReport.xml and remove duplicate results when `flaky-test-attempts` is > 0. For each test keep first result. If next result for the same test is successful, keep last successful result.
> Test retry

- test_runner/src/main/kotlin/ftl/run/TestRunner.kt
When a Flank execution hangs (due to a broken test or an FTL outage) and is killed by a timeout (on Jenkins, Bitrise, etc.), it's nice to be able to find the FTL console link associated with each shard in order to debug the issue. These are normally printed to stdout at the end of a test run, but they might not be logged if the run is killed before completing.
Fortunately, Flank also persists a `matrix_ids.json` file to disk that contains the FTL link. This PR increases the frequency with which that file is updated, so that FTL links will make it into the file as soon as they're available.
I was hoping to add a test here but I was having trouble writing one that really covered this logic -- let me know if you have an idea for how to do that 😄
> Update matrix file each time a matrix changes while polling

- release_notes.md
- test_runner/build.gradle.kts
- test_runner/gradle/wrapper/gradle-wrapper.properties
- test_runner/src/test/kotlin/ftl/filter/TestFiltersTest.kt
> Update dex and gradle

- README.md
- docs/smart_flank.md
- release_notes.md
- test_runner/flank.ios.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
Hi, thanks for this great library! I noticed that https://github.com/TestArmada/flank/blob/master/docs/smart_flank.md mentioned the possible improvement to disable uploading smart flank results, so I implemented it.
I have recently added Flank to our test suite at Airbnb, and I'd love this support to allow us to run a subset of tests on some branches without overwriting the master set of results.
> Add option to prevent uploading results for Smart Flank

- release_notes.md
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
Add `--smart-flank-gcs-path` CLI flag
Fix #540
> Rename `--test-shards` CLI flag to `--max-test-shards`

- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ArgsToString.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/AndroidGcloudYml.kt
- test_runner/src/main/kotlin/ftl/args/yml/IosFlankYml.kt
- test_runner/src/main/kotlin/ftl/args/yml/YamlDeprecated.kt
- test_runner/src/main/kotlin/ftl/shard/Shard.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
> Fix empty test targets

- README.md
- release_notes.md
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/AndroidTestShard.kt
- test_runner/src/main/kotlin/ftl/args/ArgsToString.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/AndroidFlankYml.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/RefreshCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/main/kotlin/ftl/run/AndroidTestRunner.kt
- test_runner/src/main/kotlin/ftl/run/GenericTestRunner.kt
- test_runner/src/main/kotlin/ftl/run/IosTestRunner.kt
- test_runner/src/main/kotlin/ftl/run/TestRunner.kt
- test_runner/src/main/kotlin/ftl/util/MatrixUtil.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt
- test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
- test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt
- test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
- test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt
- test_runner/src/test/kotlin/ftl/util/MatrixUtilTest.kt
> Add additional-app-test-apks support

- README.md
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/AndroidGcloudYml.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/test/util/TestHelper.kt
Adds the `--test-runner-class` parameter (which is only applicable for the Android run command): https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run#--test-runner-class
Closes #459.
> Add --test-runner-class

- release_notes.md
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
> Fix iOS CLI

- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
This reverts commit bd6e444bb95f9b05a6a28755948acec459a81f70.
> Revert "Update exit code reporting (#536)"

- test_runner/src/main/kotlin/ftl/run/RunningDevices.kt
- test_runner/src/main/kotlin/ftl/run/TestRunner.kt
- test_runner/src/main/kotlin/ftl/util/StopWatchMatrix.kt
Polling will output information from all test executions contained within a matrix. The device name/version is now included in the message.
Fix #577
```
PollMatrices
0m  0s matrix-22bqg6b74i3i4 NexusLowRes-28 VALIDATING
0m 15s matrix-22bqg6b74i3i4 NexusLowRes-28 PENDING
0m 30s matrix-22bqg6b74i3i4 NexusLowRes-28 Starting attempt 1.
0m 30s matrix-22bqg6b74i3i4 NexusLowRes-28 RUNNING
1m 31s matrix-22bqg6b74i3i4 NexusLowRes-28 Started logcat recording.
1m 31s matrix-22bqg6b74i3i4 NexusLowRes-28 Preparing device.
2m  2s matrix-22bqg6b74i3i4 NexusLowRes-28 Logging in to Google account on device.
2m  2s matrix-22bqg6b74i3i4 NexusLowRes-28 Installing apps.
2m  2s matrix-22bqg6b74i3i4 NexusLowRes-28 Retrieving Pre-Test Package Stats information from the device.
2m  2s matrix-22bqg6b74i3i4 …
```
> Poll all test executions

- test_runner/src/main/kotlin/ftl/run/RunningDevices.kt
- test_runner/src/main/kotlin/ftl/run/TestRunner.kt
Fixes performance regression introduced by https://github.com/TestArmada/flank/pull/584
> Poll devices in parallel

- test_runner/src/main/kotlin/ftl/reports/xml/model/JUnitTestSuite.kt
On my default local `"%.3f".format()` return string like 1,23 instead of 1.23.
So, the `clean()` extention removes the comma and it causes the acc var to get "infinity", which becomes `""` after `clean()` and cause `NumberFormatException`
If I run the unit tests locally it fails: 
```ftl.reports.xml.JUnitXmlTest > merge android FAILED
expected: 6.148
but was : 6,148
at ftl.reports.xml.JUnitXmlTest.merge android(JUnitXmlTest.kt:51)
```
https://stackoverflow.com/questions/43963633/java-double-to-string-format
> fix java.lang.NumberFormatException: empty String

- test_runner/flank.ios.yml
- test_runner/flank.yml
- test_runner/gradle/wrapper/gradle-wrapper.properties
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/GcloudYml.kt
- test_runner/src/main/kotlin/ftl/args/yml/YamlDeprecated.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/main/kotlin/ftl/reports/util/JUnitDedupe.kt
- test_runner/src/main/kotlin/ftl/run/RunningDevices.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/yml/YamlDeprecatedTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
> Rename flaky-test-attempts to num-flaky-test-attempts

- test_runner/src/main/kotlin/ftl/reports/xml/model/JUnitTestSuite.kt
- test_runner/src/test/kotlin/Tmp.kt
- test_runner/src/test/kotlin/ftl/fixtures/ftl_junit_xml/android_pass.xml
- test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
- test_runner/src/test/kotlin/ftl/reports/xml/JUnitXmlTest.kt
- test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
We started getting some failures because some of the junit xml's coming back from FTL had an `testLabExecutionId` attribute on `<testsuite`.
This adds the property to the model class so it can deserialize correctly.
> FTL is now sometimes adding a `testLabExecutionId` on <testsuite

- test_runner/src/main/kotlin/ftl/reports/xml/JUnitXml.kt
- test_runner/src/test/kotlin/ftl/reports/xml/JUnitXmlTest.kt
This makes sure that any future additions to the XML by FTL does not break existing builds of flank and is more permissive in structure about deserialization of unknown properties.
> Disable FAIL_ON_UNKNOWN_PROPERTIES for forward compatibility

- release_notes.md
- test_runner/src/main/kotlin/ftl/json/MatrixMap.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
* Improve exit code logging
* Use matrix outcome to set exit code
> Exit code updates

- release_notes.md
- test_runner/src/main/kotlin/ftl/reports/HtmlErrorReport.kt
> Print HtmlErrorReport location

- README.md
As per [Flank 8.0.0](https://github.com/TestArmada/flank/releases/tag/v8.0.0) new configuration property `num-test-runs`, this PR replaces `repeat-tests` with `num-test-runs` in README.md file.
> Update README.md with num-test-runs

- README.md
- release_notes.md
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/AndroidFlankYml.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/run/TestRunner.kt
- test_runner/src/main/kotlin/ftl/util/ObjPath.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
- test_runner/src/test/kotlin/ftl/util/ObjPathTest.kt
> Add --keep-file-path

- README.md
- test_runner/src/main/kotlin/ftl/args/yml/AndroidFlankYml.kt
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/run/AndroidTestRunner.kt
Currently, when using local apk artifacts, Flank always uploads every
app/test apk pair even if the app apk has already been uploaded. This is
also true for pulling the old JUnitReport from GCS for smart flank where
every test apk re-downloads the results. To fix this we simply cache
uploads and downloads in a ConcurrentHashMap where the key is the GCS
path for downloads and the filename for uploads.
This change also fixes a bug where local test apks would be uploaded and
then re-downloaded to parse their tests. The sharding loop now loops over
the local AppTestPair where it uploads them if necessary and scans for
tests on the local test apk.
All in all this shaves almost 4 minutes off of shard generation for a
project with 20+ modules. There is also likely more work that can be
done to …
> Cache all uploads and downloads to GCS

- test_runner/build.gradle.kts
- test_runner/buildSrc/src/main/kotlin/Deps.kt
Versions haven't been modified, so if this builds and passes tests, we should be good to go.
> Make Deps.kt the source of truth for dependencies

- test_runner/src/main/kotlin/ftl/shard/Shard.kt
- test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
Context: https://github.com/Flank/flank/issues/632
Ran into some local issues running all of the tests (stacktrace below[1]), but I think I covered most if not all of the places that this change touches.
Please leave comments on what I missed, or what I need to get a local build working. I can run unit tests in Android Studio, but hit some issues[2] running `./gradlew build`
[1]
```
java.lang.VerifyError: Stack map does not match the one at exception handler 77
Exception Details:
Location:
com/fasterxml/jackson/databind/deser/std/StdDeserializer._parseDate(Lcom/fasterxml/jackson/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/util/Date; @77: astore
Reason:
Type 'com/fasterxml/jackson/core/JsonParseException' (current frame, stack[0]) is not assignable to …
```
> Pass test time estimate arg to stabilize smart flank without cached results

- test_runner/flank-invalid.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/yml/YamlDeprecated.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/CommandUtil.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidDoctorCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosDoctorCommand.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/TestCommandUtils.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidDoctorCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosDoctorCommandTest.kt
Fixes #448 
When validation of yml file fail, process ends with exit code (1). 
Prints `Valid yml file` message otherwise.
> Flank should exit with code 1 when validation issues

- test_runner/src/main/kotlin/ftl/args/AndroidTestShard.kt
- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/filter/TestFilters.kt
- test_runner/src/main/kotlin/ftl/shard/Shard.kt
- test_runner/src/main/kotlin/ftl/util/FlankTestMethod.kt
- test_runner/src/test/kotlin/ftl/filter/TestFiltersTest.kt
- test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
Fixes #629 
* tests annotated with `@Ignore` are included in test matrix by default (TL skips them anyway)
* user still can filter tests with `@Ignore` with `notAnnotation org.junit.Ignore`
* Ignored tests now have time = 0 (regardless previous results)
* update and refactor unit tests
> Flank should not skip tests annotated with @Ignored

- test_app/app/src/androidTestMultiple/java/com.example.test_app/InstrumentedTest.kt
- test_app/app/src/androidTestMultiple/java/com.example.test_app/bar/BarInstrumentedTest.kt
- test_app/app/src/androidTestMultiple/java/com.example.test_app/foo/FooInstrumentedTest.kt
- test_app/bash/test_filters.sh
- test_runner/src/main/kotlin/ftl/filter/TestFilters.kt
- test_runner/src/test/kotlin/ftl/filter/TestFiltersTest.kt
- test_runner/src/test/kotlin/ftl/filter/fixtures/exclude-tests.txt
> Fix test filters when using both notPackage and notClass

- release_notes.md
- test_runner/src/main/kotlin/ftl/Main.kt
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/AndroidTestShard.kt
- test_runner/src/main/kotlin/ftl/args/ArgsFileVisitor.kt
- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/YamlDeprecated.kt
- test_runner/src/main/kotlin/ftl/config/Device.kt
- test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
- test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/gc/GcTestMatrix.kt
- test_runner/src/main/kotlin/ftl/ios/Parse.kt
- test_runner/src/main/kotlin/ftl/reports/CostReport.kt
- test_runner/src/main/kotlin/ftl/reports/HtmlErrorReport.kt
- test_runner/src/main/kotlin/ftl/reports/JUnitReport.kt
- test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt
- test_runner/src/main/kotlin/ftl/run/GenericTestRunner.kt
- test_runner/src/main/kotlin/ftl/run/TestRunner.kt
- test_runner/src/main/kotlin/ftl/shard/Shard.kt
- test_runner/src/main/kotlin/ftl/util/MatrixUtil.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/MainTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/invalid.yml
- test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt
- test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
Fixes #649 
This PR contains commit [2b92fec](https://github.com/Flank/flank/commit/2b92fec60259256975a58757ecf927ffb4e91a38) which is only small refactor which touches quite big number of files. Please, skip this commit when reviewing.
* wrap `CommandLine(Main()).execute(*args)` with `exitProcess(...)` which closes jvm (this is workaround for bugsnag bug related to thread pool executor"
* add unit tests
> Fix execution hangs

- README.md
- release_notes.md
- test_runner/build.gradle.kts
- test_runner/flank.ios.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ArgsToString.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
- test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
- test_runner/src/main/kotlin/ftl/run/platform/common/BeforeRunTests.kt
- test_runner/src/main/kotlin/ftl/util/MatrixUtil.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/FlankYmlTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/flank.ios.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank.local.yml
- test_runner/src/test/kotlin/ftl/fixtures/simple-android-flank.yml
- test_runner/src/test/kotlin/ftl/util/MatrixUtilTest.kt
Fixes #532 
* implement timeout feature logic
* add new `run-timeout` property to cli/yml
> Flank timeout feature

- release_notes.md
- test_runner/build.gradle.kts
- test_runner/buildSrc/src/main/kotlin/Deps.kt
- test_runner/src/main/kotlin/ftl/config/BugsnagInitHelper.kt
- test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
- test_runner/src/test/kotlin/ftl/config/BugsnagInitHelperTest.kt
Fixes #581 
* Introduce `BugsnagInitHelper` class to handle Bugsnag initialisation logic
* if `useMock` is equal true -- Bugsnag is not enabled
* if user had disabled `gcloud` analytics -- Bugsnag is not enabled
* in other cases -- Bugsnag enabled
* Add `updateFlank` gradle task to update local flank jar
* Add `mockk` library as POC (will replace `mockito` in the future)
> Skip Bugsnag initialisation if user disabled gcloud analytics

- release_notes.md
- test_runner/src/main/kotlin/ftl/Main.kt
- test_runner/src/main/kotlin/ftl/log/LogbackLogger.kt
- test_runner/src/main/kotlin/ftl/log/Loggers.kt
- test_runner/src/test/kotlin/ftl/config/FlankBugsnagInitHelperTest.kt
Fixes #682 
Due to lazy initialization of Kotlin's objects logging level was not set (default was used).
> Fix logging level for both root and Bugsnag not being initialized

- release_notes.md
- test_runner/src/main/kotlin/ftl/reports/api/CreateJUnitTestCase.kt
- test_runner/src/main/kotlin/ftl/reports/api/CreateJUnitTestSuite.kt
- test_runner/src/main/kotlin/ftl/reports/api/CreateTestSuitOverviewData.kt
- test_runner/src/main/kotlin/ftl/reports/api/Utils.kt
- test_runner/src/main/kotlin/ftl/reports/api/data/TestSuiteOverviewData.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/test/kotlin/ftl/reports/api/CreateJUnitTestCaseKtTest.kt
- test_runner/src/test/kotlin/ftl/reports/api/CreateJUnitTestSuiteKtTest.kt
- test_runner/src/test/kotlin/ftl/reports/api/CreateTestSuitOverviewDataKtTest.kt
> Add overhead time to junit test case report

- test_runner/src/main/kotlin/ftl/http/ExecuteWithRetry.kt
When retry occurs error message is printed to user which can be misleading.
> Disable print error message when retry occurs

- release_notes.md
- test_runner/flank.ios.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/GcloudYml.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/TestCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/CommonRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/NetworkProfilesCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/networkprofiles/NetworkProfilesListCommand.kt
- test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/NetworkProfilesCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/networkprofiles/NetworkProfilesListCommandTest.kt
- test_runner/src/test/kotlin/ftl/test/util/TestHelper.kt
> Add support for network-profiles list command & --network-profile option

- release_notes.md
- test_runner/src/main/kotlin/ftl/reports/api/PrepareForJUnitResult.kt
- test_runner/src/main/kotlin/ftl/run/common/PollMatrices.kt
- test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
- test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
Fixes #645
```
4 matrix ids created in 0m 22s
https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-04-01_07-25-03.132000_AQWv/
Matrices webLink
matrix-26tm1277rg3gr: https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/8849499259998194241
matrix-2veeo7xug1f8k: https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/5106500884348802256
matrix-2z6o0hu8tt5bf: https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/4681223845649672500
matrix-2jl1g9zptcs9m: https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/6721963817674217321/executions/bs …
```
> Print web link

- test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
- test_runner/src/main/kotlin/ftl/util/MatrixState.kt
- test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
Implement logic to prevent updating invalid matrices
> Add logic to prevent fetching from invalid test matrices

- test_runner/src/main/kotlin/ftl/http/ExecuteWithRetry.kt
- test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
Flank will wait 1-3-7-20 second respectively for every FTL API call if `IOException` occurs.
If response with status code `429` is returned flank should fail fast since it is fatal error (according to FTL team)
> Add exponential backoff

- release_notes.md
- test_runner/src/main/kotlin/ftl/shard/Shard.kt
- test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
> Fix shards calculation when there are ignored tests and shardTime is -1

- README.md
- release_notes.md
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/CommonRunCommand.kt
- test_runner/src/main/kotlin/ftl/json/MatrixMap.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/main/kotlin/ftl/util/FlankException.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
> Add ignore failed tests option to Flank

- README.md
- release_notes.md
- test_runner/flank.ios.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/AndroidFlankYml.kt
- test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/CommonRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
> Add keep file path for ios

- test_runner/bash/update_flank.sh
- test_runner/src/main/kotlin/ftl/http/ExecuteWithRetry.kt
Fixes #701
Flank will send notifications to Bugsnag when Google API error occurrs. Data can be fetch within api request [API docs](https://bugsnagapiv2.docs.apiary.io/). However authorized account (added to project/organization) is required
> Add detailed api reporting

- test_runner/docs/ascii/flank.jar_-android-run.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-android-run.adoc
Quick fix which add missing `robo-script` and `robo-directives` in ascii docs
> Update ascii docs

- README.md
- release_notes.md
- test_runner/flank.ios.yml
- test_runner/flank.yml
> Sync README.md flank.yml flank.ios.yml

- release_notes.md
- test_runner/build.gradle.kts
- test_runner/src/main/kotlin/ftl/Main.kt
> Print version and revision before each command

- release_notes.md
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/YamlDeprecated.kt
- test_runner/src/main/kotlin/ftl/doctor/Doctor.kt
- test_runner/src/main/kotlin/ftl/mock/MockServer.kt
- test_runner/src/main/kotlin/ftl/reports/xml/JUnitXml.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/yml/YamlDeprecatedTest.kt
- test_runner/src/test/kotlin/ftl/doctor/DoctorTest.kt
> Reduce memory usage by using Reader and Writer instead of ByteArrays

- release_notes.md
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
> Use legacy results for iOS by default

- release_notes.md
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/args/yml/MissingParameterErrorConverter.kt
- test_runner/src/main/kotlin/ftl/args/yml/YamlObjectMapper.kt
- test_runner/src/main/kotlin/ftl/args/yml/errors/ConfigurationErrorMessageBuilder.kt
- test_runner/src/main/kotlin/ftl/args/yml/errors/ConfigurationErrorModel.kt
- test_runner/src/main/kotlin/ftl/args/yml/errors/ConfigurationErrorParser.kt
- test_runner/src/main/kotlin/ftl/args/yml/errors/ErrorNodeResolver.kt
- test_runner/src/main/kotlin/ftl/util/FlankException.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/args/yml/ErrorParserTest.kt
- test_runner/src/test/kotlin/ftl/args/yml/test_error_yaml_cases/flank-no-device-version.yml
- test_runner/src/test/kotlin/ftl/args/yml/test_error_yaml_cases/flank-no-model-name.yml
- test_runner/src/test/kotlin/ftl/args/yml/test_error_yaml_cases/flank-no-model-node.yml
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-multiple-parse-error.yml
- test_runner/src/test/kotlin/ftl/test/util/FlankTestExceptions.kt
- test_runner/src/test/kotlin/ftl/test/util/TestHelper.kt
> Improve error messages

- release_notes.md
- test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
> #699 Fix Bugsnag being initialized during tests

- .github/workflows/macos_workflow.yml
- release_notes.md
Fixes #769 Convert [bitrise macOS workflow](https://app.bitrise.io/app/9767f3e19047d4db/workflow_editor#!/yml) to GitHub actions
This PR will cause that PR checks will be performed on GitHub Actions instead of Bitrise
> #769 Convert bitrise macOS workflow into github actions

- release_notes.md
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/GetAndroidMatrixShards.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt
- test_runner/src/test/kotlin/ftl/run/platform/android/ResolveApksKtTest.kt
> Omit missing app apk if additional-app-test-apks specified

- release_notes.md
- test_runner/src/main/kotlin/ftl/gc/android/CreateAndroidInstrumentationTest.kt
- test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/AndroidTestConfig.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestConfig.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateInstrumentationConfig.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-single-success-disable-sharding.yml
- test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt
- test_runner/src/test/kotlin/ftl/gc/android/CreateAndroidInstrumentationTestTest.kt
> Allow runtime test discovery when sharding is disabled by not setting test-targets. This unblocks cucumber testing

- release_notes.md
- test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt
- test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt
- test_runner/src/main/kotlin/ftl/util/LogTableBuilder.kt
- test_runner/src/main/kotlin/ftl/util/SavedMatrixTableUtil.kt
- test_runner/src/main/kotlin/ftl/util/SystemOutColor.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/util/LogTableBuilderTest.kt
- test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
> #810 Prints matrix error as table

- test_runner/build.gradle.kts
- test_runner/buildSrc/src/main/kotlin/Deps.kt
Add simple dependency check plugin [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin)
It adds `gradle dependencyUpdates` task which produces dependencies version report. With given configuration, only latest stable versions are proposed as update candidate
> Add dependency check plugin

- release_notes.md
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-single-errorFlaky.yml
- test_runner/src/test/kotlin/ftl/gc/android/CreateAndroidInstrumentationTestTest.kt
- test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
> #824 Automatically convert -1 in maximum-test-shards to the maximum shard amount

- release_notes.md
- test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/android/SetupEnvironmentVariables.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-multiple-mixed.yml
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-single-robo.yml
- test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt
> #816 Omit `environment-variables` for robo test executions instead of throwing exception.

- release_notes.md
- test_app/app/src/androidTestMultiple/java/com.example.test_app/InstrumentedTest.kt
- test_app/app/src/androidTestMultiple/java/com.example.test_app/bar/BarInstrumentedTest.kt
- test_app/app/src/androidTestMultiple/java/com.example.test_app/foo/FooInstrumentedTest.kt
- test_app/app/src/androidTestSingle/java/com.example.test_app/InstrumentedTest.kt
- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/args/CalculateShardsResult.kt
- test_runner/src/main/kotlin/ftl/args/IgnoredTestCases.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/reports/api/Utils.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/main/kotlin/ftl/reports/xml/model/SkippedTestJUnitTestSuite.kt
- test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
- test_runner/src/main/kotlin/ftl/run/model/AndroidTestContext.kt
- test_runner/src/main/kotlin/ftl/run/model/AndroidTestShards.kt
- test_runner/src/main/kotlin/ftl/run/model/TestResult.kt
- test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
- test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/GetAndroidMatrixShards.kt
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-multiple-success.yml
- test_runner/src/test/kotlin/ftl/reports/xml/model/SkippedTestJUnitTestSuiteTest.kt
- test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
- test_runner/src/test/kotlin/ftl/run/platform/RunAndroidTestsKtTest.kt
- test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
- test_runner/src/test/kotlin/ftl/run/platform/android/IgnoreTestsAnnotationTest.kt
Fixes #852 
.
Ignored test should't shows on FTL
> Skip @Ignore tests before send it to ftl and reapply to local JUnit Xml

- README.md
run-timeout mentioned 2 times in README with configuration example
> Removed duplicate run-timeout option from README

- docs/bugs/null_no_tests_found.md
Fixes #818 
We don't know what is the reason and how to reproduce it in same way as reported #818. 
We need to collect all information as we can about this issue.
This issue has dedicated [doc](https://github.com/Flank/flank/blob/818-null-no-tests-found/docs/bugs/null_no_tests_found.md).
estimation - dragon
> Null no tests found

- README.md
- release_notes.md
- test_runner/docs/ascii/flank.jar_-android-run.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-android-run.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-ios-run.adoc
- test_runner/docs/ascii/flank.jar_-ios-run.adoc
- test_runner/flank.ios.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/reports/CostReport.kt
- test_runner/src/main/kotlin/ftl/reports/FullJUnitReport.kt
- test_runner/src/main/kotlin/ftl/reports/HtmlErrorReport.kt
- test_runner/src/main/kotlin/ftl/reports/JUnitReport.kt
- test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt
- test_runner/src/main/kotlin/ftl/reports/util/IReport.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/success_result/shard_0/NexusLowRes-28-en-portrait/test_result_1.xml
- test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
Fixes #750 
-Should upload reports to gcloud bucket
> #750 Store test results in gcloud bucket

- release_notes.md
- test_runner/docs/ascii/flank.jar_-android-run.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-android-run.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-ios-run.adoc
- test_runner/docs/ascii/flank.jar_-ios-run.adoc
- test_runner/src/main/kotlin/ftl/reports/api/CreateJUnitTestCase.kt
- test_runner/src/test/kotlin/ftl/reports/api/CreateJUnitTestCaseKtTest.kt
Fixes #867
1. Unit tests pass, and they verify the output and caught the expected changes
2. Ran locally with default configuration:
```(^ 1) [Tue Jun 23 18:50:04] ~/code/flank/test_runner (rainnapper/weblink)
$ java -jar ./build/libs/flank.jar firebase test android run
version: local_snapshot
revision: 59772a4256e76ee65ca7b4c04f685891ad3043e5
...
(^ 0) [Tue Jun 23 19:00:32] ~/code/flank (rainnapper/weblink)
$ cat test_runner/results/2020-06-24_01-50-08.293000_MQbb/JUnitReport.xml
<?xml version='1.0' encoding='UTF-8' ?>
<testsuites>
<testsuite name="NexusLowRes-28-en-portrait" tests="1" failures="0" flakes="0" errors="0" skipped="0" time="0.604" timestamp="2020-06-24T01:51:55" hostname="localhost">
<testcase name="testPasses" …
```
> add weblinks to all test output

- test_runner/build.gradle.kts
Only failed/skipped tests are printed to std out during gradle task run
> Print only skipped/failed tests

- .github/workflows/macos_workflow.yml
- test_runner/gradle/wrapper/gradle-wrapper.properties
There is some problem with the current macOS workflow builds, so in order to fix this gradlew wrapper and cache should be updated
Update  gradle wrapper to 6.5 and github actions to cache@v2
> Update  gradle wrapper to 6.5 and github actions to cache@v2

- release_notes.md
- test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt
Fixes #850 
All matrices failed links are printed in summary below the summary table.
Do not print any data if there are not present failed links.
> #850 fix printing all matrix links

- release_notes.md
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt
- test_runner/src/main/kotlin/ftl/reports/api/CreateJUnitTestResult.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/ValidateDirectoriesToPullAndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/json/SavedMatrixTest.kt
- test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
Fixes #870 
NPE with missing `toolStepResult` was caused because we try to get results for an invalid matrix. Matrix was invalid because FTL rejects the request with invalid `--directories-to-pull` value.
To avoid this issue correct validation of this parameter was introduced, as well as filtering getting results for empty `toolStepResult`.
[Gcloud](https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run#--directories-to-pull) policies were applied to `--directories-to-pull`:
- the path must start with `/sdcard` or `/data/local/tmp`
- the path must contain only characters `a-zA-Z0-9_-./+`
In order to test this issue, please use `--directories-to-pull` value which does not meet this 2 criteria.
> #870 Added --directories-to-pull validation and avoid making request with empty toolStepResult

- docs/permissions_denied_behavior.md
- release_notes.md
- test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
- test_runner/src/main/kotlin/ftl/http/ExecuteWithRetry.kt
- test_runner/src/main/kotlin/ftl/util/FlankException.kt
- test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt
Fixes #874
When user don't have permission to project Flank should returns message like:
```
Flank encountered a 403 error when running on project $project_name. Please verify this credential is authorized for the project.
Consider authentication with a Service Account https://github.com/Flank/flank#authenticate-with-a-service-account
or with a Google account https://github.com/Flank/flank#authenticate-with-a-google-account
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
"code" : 403,
"errors" : [ {
"domain" : "global",
"message" : "The caller does not have permission",
"reason" : "forbidden"
} ],
"message" : "The caller does not have permission",
"status" : "PERMISSION_DENIED"
}
```
When project not found on …
> Enhance permission denied exception logs

- release_notes.md
- test_runner/docs/ascii/flank.jar_-firebase-test-ios.adoc
- test_runner/docs/ascii/flank.jar_-ios.adoc
- test_runner/src/main/kotlin/ftl/cli/firebase/test/IosCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosDoctorCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/models/IosModelsCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/models/IosModelsListCommand.kt
- test_runner/src/main/kotlin/ftl/environment/ListIOsDevices.kt
- test_runner/src/main/kotlin/ftl/ios/IosCatalog.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/models/IosModelsListCommandTest.kt
- test_runner/src/test/kotlin/ftl/ios/IosCatalogTest.kt
Fixes #835 
- `flank firebase test ios models list` or `flank ios models list` - print iOS available devices to test against
<details>
<summary>Sample iOS models list output:</summary>
<p>
```
┌─────────────┬───────────────────────┬─────────────┬────────────────────────┬──────────────────────────────────┐
│  MODEL_ID   │      MODEL_NAME       │ RESOLUTION  │     OS_VERSION_IDS     │               TAGS               │
├─────────────┼───────────────────────┼─────────────┼────────────────────────┼──────────────────────────────────┤
│    ipad5    │ iPad (5th generation) │ 2048 x 1536 │       11.2, 12.0       │         deprecated=11.2          │
│  ipadmini4  │      iPad mini 4      │ 2048 x 1536 │       11.2, 12.0 …
```
> #835 Added printing iOS devices

- release_notes.md
- test_runner/docs/ascii/flank.jar_-android.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-android.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-ios.adoc
- test_runner/docs/ascii/flank.jar_-ios.adoc
- test_runner/src/main/kotlin/ftl/cli/firebase/test/AndroidCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/IosCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidTestEnvironmentCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosTestEnvironmentCommand.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidTestEnvironmentCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosTestEnvironmentCommandTest.kt
Fixes #835 
- `flank firebase test android|ios test-environment` or `flank android|ios test-environment` - print Android|iOS available versions and devices to test against
More listing options of the test environment will be added in the next tasks
> #835 added printing all test environment information

- release_notes.md
- test_runner/docs/ascii/flank.jar_-firebase-test.adoc
- test_runner/docs/ascii/flank.jar_.adoc
- test_runner/src/main/kotlin/ftl/Main.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/TestCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ProvidedSoftwareCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidTestEnvironmentCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosTestEnvironmentCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/providedsoftware/ProvidedSoftwareListCommand.kt
- test_runner/src/main/kotlin/ftl/environment/ListProvidedSoftware.kt
- test_runner/src/main/kotlin/ftl/environment/ProvidedSoftwareCatalog.kt
- test_runner/src/main/kotlin/ftl/mock/MockServer.kt
- test_runner/src/test/kotlin/ftl/environment/ListProvidedSoftwareTest.kt
Fixes #885
- `flank firebase test provided-software list` or `flank provided-software  list` - print provided software version
<details>
<summary>Sample output:</summary>
<p>
```
┌──────────────────────┐
│ ORCHESTRATOR VERSION │
├──────────────────────┤
│        1.0.2         │
└──────────────────────┘
```
</details>
More listing options of the test environment will be added in the next tasks
> #885 Print provided software

- release_notes.md
- test_runner/docs/ascii/flank.jar_-firebase-test-ios-test-environment.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-ios.adoc
- test_runner/docs/ascii/flank.jar_-ios-test-environment.adoc
- test_runner/docs/ascii/flank.jar_-ios.adoc
- test_runner/src/main/kotlin/ftl/cli/firebase/test/IosCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosTestEnvironmentCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesListCommand.kt
- test_runner/src/main/kotlin/ftl/environment/ListLocales.kt
- test_runner/src/main/kotlin/ftl/ios/IosCatalog.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesListCommandTest.kt
- test_runner/src/test/kotlin/ftl/ios/IosCatalogTest.kt
Fixes #884
- `flank firebase test ios locales list` or `flank ios locales list` - print Android available  locales to test against
<details>
<summary>Sample iOS versions list output:</summary>
<p>
```
┌────────┬─────────────────────────────┬───────────────────────────────────┬─────────┐
│ LOCALE │            NAME             │              REGION               │  TAGS   │
├────────┼─────────────────────────────┼───────────────────────────────────┼─────────┤
│   af   │          Afrikaans          │                                   │         │
│ af_NA  │          Afrikaans          │              Namibia              │         │
│ af_ZA  │          Afrikaans          │           South Africa            │         │ …
```
> #884 added printing available locales for iOS devices

- release_notes.md
- test_runner/docs/ascii/flank.jar_-android-locales-list.adoc
- test_runner/docs/ascii/flank.jar_-android-locales.adoc
- test_runner/docs/ascii/flank.jar_-android-screen-orientations-list.adoc
- test_runner/docs/ascii/flank.jar_-android-screen-orientations.adoc
- test_runner/docs/ascii/flank.jar_-android-test-environment.adoc
- test_runner/docs/ascii/flank.jar_-android.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-android-locales-list.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-android-locales.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-android-screen-orientations-list.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-android-screen-orientations.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-android-test-environment.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-android.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-ios-run.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-ios-screen-orientations-list.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-ios-screen-orientations.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-ios.adoc
- test_runner/docs/ascii/flank.jar_-ios-run.adoc
- test_runner/docs/ascii/flank.jar_-ios-screen-orientations-list.adoc
- test_runner/docs/ascii/flank.jar_-ios-screen-orientations.adoc
- test_runner/docs/ascii/flank.jar_-ios.adoc
- test_runner/src/main/kotlin/ftl/android/AndroidCatalog.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/AndroidCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidTestEnvironmentCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesListCommand.kt
- test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesListCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesListCommandTest.kt
Fixes #884
- `flank firebase test android locales list` or `flank android locales list` - print Android available  locales to test against
<details>
<summary>Sample Android versions list output:</summary>
<p>
```
┌────────┬─────────────────────────────┬───────────────────────────────────┬─────────┐
│ LOCALE │            NAME             │              REGION               │  TAGS   │
├────────┼─────────────────────────────┼───────────────────────────────────┼─────────┤
│   af   │          Afrikaans          │                                   │         │
│ af_NA  │          Afrikaans          │              Namibia              │         │
│ af_ZA  │          Afrikaans          │           South Africa …
```
> #884 added printing available locales for Android devices

- release_notes.md
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidDoctorCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosDoctorCommand.kt
- test_runner/src/main/kotlin/ftl/doctor/Doctor.kt
- test_runner/src/test/kotlin/ftl/doctor/DoctorTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/flank_android_failed_configuration.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank_android_failed_tree.yml
Fixes #911 by adding preloading configuration and tree parsing + refactor `Doctor` file
Running command `firebase test android|ios doctor` or `flank android|ios doctor` will show issue when cannot parse 
`.yml` configuration (invalid example in root task).
Previously doctor validates only basic `.yml` parsing, now it pre-load configuration and validate tree to catch more errors
> Added preloading configuration and tree parsing + refactor `Doctor` file

- test_runner/build.gradle.kts
Disable CLI AsciiDoc as per discussion around it creating unnecessary pull request spam
No more AutoDoc generation when we submit pull requests
.
> Disable Auto Doc Generation

- release_notes.md
- test_runner/docs/ascii/flank.jar_-android-run.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-android-run.adoc
- test_runner/docs/ascii/flank.jar_-firebase-test-ios-run.adoc
- test_runner/docs/ascii/flank.jar_-ios-run.adoc
- test_runner/src/main/kotlin/ftl/args/AndroidArgsCompanion.kt
- test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgsCompanion.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidTestEnvironmentCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesListCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/models/AndroidModelsListCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/orientations/AndroidOrientationsListCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/versions/AndroidVersionsListCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosTestEnvironmentCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesListCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/models/IosModelsListCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/orientations/IosOrientationsListCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/versions/IosVersionsListCommand.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsFileTest.kt
Fixes #925 
Try run flank commands for
```
models
orientations
locales
test-environment
network
```
, without flank.yml this should display lists instead of ```flank.yml``` not found
> Run *list commands when flank.yml not found should display right output 

- release_notes.md
- test_runner/build.gradle.kts
Fixes #951 
Change param runningOnBitrise to more generic runningOnCI
Need to run a build to check the version update.
.
> Fix version printing on Flank release 

- release_notes.md
- test_runner/src/main/kotlin/ftl/reports/util/MatrixPath.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
Fixes #947 
When using --legacy-junit-result flank, shouldn't throw an exception.
> Fix crash when --legacy-junit-result set

- contributing.md
- release_notes.md
- test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/test/kotlin/ftl/fixtures/flank.ios.yml
- test_runner/src/test/kotlin/ftl/fixtures/flank.local.yml
- test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
Fixes #902 
#798 introduced a new argument `full-junit-result`. It is false by default. First problem, it is not added to keys list so flank doctor report new argument as unknown key.
Second problem is about junit xml report for smart flank run. `full-junit-result` and `legacy-junit-result` are used to decide to send junit report. As I understand from #798, there are now there junit result, legacy and full. Consideration; when both flag are true, flank can throw exception at argument checking phase.
While using flank without legacy and full junit test report, smart test sharding and junit xml upload need to work.
> Process junit xml even when full junit is not enabled

- release_notes.md
- test_runner/src/main/kotlin/ftl/util/LogTableBuilder.kt
Fixes #958 
Text for any list option (example: `flank android locales list`) is left aligned. Same as for `gcloud`
> Make table text left aligned

- release_notes.md
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Fixes #954 
When full-junit-result and legacy-junit-result set Flank should fast fail with message
```
Parameters conflict, you cannot set: `--legacy-junit-result` and `--full-junit-result` at the same time.
Process finished with exit code 2
```
> Fast fail when full-junit-result and legacy-junit-result 

- flank-scripts/src/main/kotlin/flank/scripts/release/hub/DeleteOldRelease.kt
- release_notes.md
Fixes #960
Old `flank_snapshot` releasees are removed before publishing new one
> Fixing Flood of snapshot  releases 

- .github/workflows/release.yml
- release_notes.md
Fixes #961
Release version should correctly print version after run command `flank --version`
> Fix printing release version

- .github/workflows/release.yml
Refix for #961 
Release version is printed with leading `v`
> Added leading V to version name

- release_notes.md
- test_runner/src/main/kotlin/ftl/cli/firebase/test/NetworkProfilesCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/networkprofiles/NetworkProfilesDescribeCommand.kt
- test_runner/src/main/kotlin/ftl/environment/NetworkConfigurationCatalog.kt
- test_runner/src/main/kotlin/ftl/environment/NetworkProfileDescription.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/NetworkProfilesCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/networkprofiles/NetworkProfileDescribeTest.kt
- test_runner/src/test/kotlin/ftl/test/util/TestHelper.kt
Fixes #963 
Run `flank network-profiles describe LTE` and see the result:
```
downRule:
bandwidth: 16000.0
delay: 0.040s
packetLossRatio: 0.001
id: LTE
upRule:
bandwidth: 16000.0
delay: 0.040s
packetLossRatio: 0.001
```
Compare it with `gcloud alpha firebase test network-profiles describe LTE` output
> Implement network-profiles describe feature

- release_notes.md
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Improve error message on IOS when test or xctestrun-file not found
Fixes #937 
Tested for the cases where test and xctestrun-file not specified. Instead of an exception an appropriate message that correlates to what is outputted by android is displayed.
> Improve error message on IOS

- .opensource/project.json
- release_notes.md
Added .opensource for firebaseopensource
There is still a requirement for the description to be updated with an issue attached to the firebaseopensource github.
Fixes #860 
It will appear on the firebaseopensource.com website
.
> Firebaseopensource.com addition

- README.md
- docs/analytics.md
- docs/error_monitoring.md
- docs/readme.md
- release_notes.md
> docs: Analytics addition to readme

- release_notes.md
- test_projects/android/app/src/androidTestMultiple/java/com.example.test_app/InstrumentedTest.kt
- test_projects/android/app/src/androidTestSingle/java/com.example.test_app/InstrumentedTest.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
- test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
- test_runner/src/test/kotlin/ftl/run/platform/android/IgnoreTestsAnnotationTest.kt
Fixes #984
Tests marked with annotation  `androidx.test.filters.Suppress` or  `android.support.test.filters.Suppress` are treated like `org.junit.Ignore`.
If you run tests with this annotation you could see that these tests are ignored.
You could also run with `--dump-shards` option to check if the required test is included in `junit-ignored` section
> fix: exclusion of @Suppress test

- release_notes.md
- test_runner/src/main/kotlin/ftl/android/AndroidCatalog.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/versions/AndroidVersionsCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/versions/AndroidVersionsDescribeCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/versions/IosVersionsCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/versions/IosVersionsDescribeCommand.kt
- test_runner/src/main/kotlin/ftl/environment/android/AndroidSoftwareVersionDescription.kt
- test_runner/src/main/kotlin/ftl/environment/ios/IosSoftwareVersionDescription.kt
- test_runner/src/main/kotlin/ftl/ios/IosCatalog.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/versions/AndroidVersionsDescribeCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/versions/IosVersionsDescribeCommandTest.kt
- test_runner/src/test/kotlin/ftl/environment/android/AndroidSoftwareVersionDescriptionTest.kt
- test_runner/src/test/kotlin/ftl/environment/ios/IosSoftwareVersionDescriptionTest.kt
Fixes #975
When run 
```
flank firebase test android|ios versions describe VERSION_ID
```
flank should return output like gcloud cli when execute
```
gcloud alpha firebase test android|ios versions describe VERSION_ID
```
example for ``` flank firebase test android versions describe 28 ```
```
apiLevel: 28
codeName: Pie
id: '28'
releaseDate:
day: 6
month: 8
year: 2018
versionString: 9.x
```
example for ``` flank firebase test ios versions describe 11.2 ```
```
id: '11.2'
majorVersion: 11
minorVersion: 2
supportedXcodeVersionIds:
- 10.2.1
- 10.3
- 11.0
- 11.1
- 11.2.1
- 11.3.1
tags:
- default
```
example for the wrong VERSION_ID ``` flank firebase test android versions describe test ```
```
ERROR: 'test' is not a valid OS version
```
Some …
> feat: add versions description command for ios and android

- release_notes.md
- test_runner/src/main/kotlin/ftl/android/AndroidCatalog.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesDescribeCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesDescribeCommand.kt
- test_runner/src/main/kotlin/ftl/environment/LocalesDescription.kt
- test_runner/src/main/kotlin/ftl/ios/IosCatalog.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesDescribeCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesDescribeCommandTest.kt
- test_runner/src/test/kotlin/ftl/environment/LocalesDescribeTest.kt
Fixes #966 
When run 
```
flank firebase test android|ios locales describe LOCALE_ID
```
flank should return output like gcloud cli when execute
```
gcloud alpha firebase test android|ios locales describe LOCALE_ID
```
example for ``` flank firebase test android locales describe en ```
```
id: en
name: English
tags:
- default
```
example for ``` flank firebase test android locales describe pl ```
```
id: pl
name: Polish
```
example for the wrong LOCALE_ID ``` flank firebase test android locales describe test ```
```
ERROR: 'test' is not a valid locale
```
> feat: add locales description command for ios and android

- release_notes.md
- test_runner/src/main/kotlin/ftl/android/AndroidCatalog.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/models/AndroidModelDescribeCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/models/AndroidModelsCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/models/IosModelDescribeCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/models/IosModelsCommand.kt
- test_runner/src/main/kotlin/ftl/environment/android/AndroidModelDescription.kt
- test_runner/src/main/kotlin/ftl/environment/ios/IosModelDescription.kt
- test_runner/src/main/kotlin/ftl/ios/IosCatalog.kt
- test_runner/src/test/kotlin/ftl/environment/android/AndroidModelDescriptionTest.kt
- test_runner/src/test/kotlin/ftl/environment/ios/IosModelDescriptionTest.kt
Fixes #976 
When run 
```
flank firebase test android|ios models describe MODEL_ID
```
flank should return output like gcloud cli when execute
```
gcloud alpha firebase test android|ios models describe MODEL_ID
```
example for ``` flank firebase test android  models describe walleye ```
```
brand: Google
codename: walleye
form: PHYSICAL
formFactor: PHONE
id: walleye
manufacturer: Google
name: Pixel 2
screenDensity: 420
screenX: 1080
screenY: 1920
supportedAbis:
- arm64-v8a
- armeabi-v7a
- armeabi
supportedVersionIds:
- 26
- 27
- 28
tags:
- default
thumbnailUrl: https://lh3.googleusercontent.com/j4urvb3lXTaFGZI6IzHmAjum2HQVID1OHPhDB7dOzRvXb2WscSX2RFwEEFFSYhajqRO5Yu0e6FYQ
```
example for ``` flank firebase test ios  models describe iphone6s ```
``` …
```
> feat: Implement command `models describe` for ios/android

- .github/workflows/release_notes_generation.yml
Release notes are generated for the next release.
What is missing in the previous PR is that tags are not fetched by default on Github Actions
> fix: generation of release notes

- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidTestEnvironmentCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosTestEnvironmentCommand.kt
Fixes #1001 
Run `flank android test-environment` and `flank ios test-environment` and see a table with IPs printed at the bottom
> feat: Add ip-blocks command to test-environment command

- .mergify.yml
Fixes #1008 
- According to [mergify documentation ](https://doc.mergify.io/examples.html#automatic-merge-when-ci-works-and-approving-reviews )our configuration is correct for auto-merge changes based on master branch protection rules. However we should make a `rebase` before each merge to avoid failing continuous integration on master branch, as described [here](https://doc.mergify.io/merge-action.html).
- Also added posting a comment to PR when title is not good
> ci: Update mergify configuration

- flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/AppendReleaseNotes.kt
- flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/ConventionalCommitFormatter.kt
- flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GenerateChangeLog.kt
- flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GenerateReleaseNotesCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/ReleaseNotesWithType.kt
- flank-scripts/src/main/kotlin/flank/scripts/release/hub/ReleaseFlank.kt
- flank-scripts/src/main/kotlin/flank/scripts/utils/MarkdownFormatter.kt
- flank-scripts/src/test/kotlin/flank/scripts/ci/releasenotes/AppendReleaseNotesTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/ci/releasenotes/ConventionalCommitFormatterTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/ci/releasenotes/ReleaseNotesWithTypeTest.kt
Fixes #1019
Release notes are better organized in categories:
`flankScripts ci generateReleaseNotes --token=<PAT> --release-notes-file=<PATH TO FILE>`
<details>
<summary>example output:</summary>
- [#919](https://github.com/Flank/flank/pull/919) Rate limit exceeded ([pawelpasterz](https://github.com/pawelpasterz), [jan-gogo](https://github.com/jan-gogo))
- [#1005](https://github.com/Flank/flank/pull/1005) Generation of release notes ([piotradamczyk5](https://github.com/piotradamczyk5))
- [#1007](https://github.com/Flank/flank/pull/1007) Failing tests ([piotradamczyk5](https://github.com/piotradamczyk5))
- [#990](https://github.com/Flank/flank/pull/990) Exclusion of @Suppress test ([piotradamczyk5](https://github.com/piotradamczyk5))
- …
> feat: Make release notes more organized

- test_runner/src/main/kotlin/ftl/json/OutcomeDetailsFormatter.kt
- test_runner/src/test/kotlin/ftl/json/OutcomeDetailsFormatterTest.kt
Fixes #1026 
Flank not throwing an NPE when otherNativeCrash is null. 
The unit test passes.
> fix: otherNativeCrash NPE

- .github/workflows/release.yml
Because GitHub packages [does not allow to delete public packages](https://docs.github.com/en/packages/publishing-and-managing-packages/deleting-a-package), we should publish flank to it only on stable releases:
```
About public package deletion
To avoid breaking projects that may depend on your packages, you cannot delete an entire public package or specific versions of a public package.
Under special circumstances, such as for legal reasons or to conform with GDPR standards, you can ask GitHub Support to delete a public package for you, using our contact form.
```
Only stable releases are published to GitHub Packages( with unique version number)
> ci: Disable publishing snapshot to Github Packages

- test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt
- test_runner/src/main/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummary.kt
- test_runner/src/main/kotlin/ftl/reports/outcome/TestOutcome.kt
Small improvement for PR #1028
> Remove vars from updatedSavedMatrix

- config/detekt.yml
Fixes master not compiling due to flank-scripts formatting error
Unfortunately Flanks-scripts was not checked with the new detekt modifications and is causing master to fail to compile
> fix: master not compiling

- README.md
- test_runner/flank.ios.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
- test_runner/src/main/kotlin/ftl/shard/Shard.kt
- test_runner/src/main/kotlin/ftl/shard/ShardCount.kt
- test_runner/src/main/kotlin/ftl/shard/TestCasesCreator.kt
- test_runner/src/main/kotlin/ftl/shard/TestMethodTime.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
- test_runner/src/test/kotlin/ftl/shard/ShardTestCommon.kt
- test_runner/src/test/kotlin/ftl/shard/TestCasesCreatorTest.kt
feat: Added options for default time and average time
Fixes #977
Default test time is set for using when calculating Shards.
The average time is used after enabling option when using SmartShard.
Please check the documentation for more details
> feat: Added option for default test time and average time for smart shard

- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
Flank is detecting more tests than there are in my test suit (there should be about 2,000 give or take, but it’s running 12,000). When I look at the junit test report in each matrix, I see that some tests are being ran once as expected, but some are being ran 5 times and some even 40+ times. Each test only appears once in my source code, num-test-runs is set to 1, and num-flaky-test-attempts is set to 0.
Flank version: v20.08.3
Example of android_shards.json with duplicated tests: https://gist.github.com/MatthewTPage/99dcf8a1876716f815b802c0bc2a5d41
(note that I obfuscated the class and method names, but the important information of "the tests are duplicated" is there).
Flank configuration that produced the above (with some bucket and apk names obfuscated): …
> fix: Flank finding and running duplicate tests

- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
- test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
Fixes #1049 
Task #1048 is covered with tests
> test: Added missing test t cover duplicated tests issue

- docs/bugs/smart_flank_upload_results_rules.md
- test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
After some discussion with @jan-gogo about https://github.com/Flank/flank/issues/936, this solution can be useful to avoid override results by different result types.  
Fixes #1057 
1. If we set FullJUnitResult.xml in ```smart-flank-gcs-path``` and in run we haven't set flag ```--full-junit-result``` flank should fast fail
2. If we set JUnitResult.xml in ```smart-flank-gcs-path``` and in run we have set flag ```--full-junit-result``` flank should fast fail
3. If user set different XML name in ```smart-flank-gcs-path``` flank shouldn't validate type.
> feat: Added validation of smart-flank-gcs-path to not override different junit results

- .github/workflows/release.yml
Fixes potential 1033 but for now in test. Will update accordingly
Want to test it on our GOGO apps first as we must wait for the permission to post to firebase.
An app (Flank Release Test Bot) is created and installed on GoGoApps slack and pointing towards a test_channel. This will be triggered for releases.
Firebase community has had the official Flank Release Bot permission requested to be installed and we are waiting for the result.
To update for firebase simply changing the oauthkey in the GitHub secrets and pointing to the correct channel will work.
> ci: Post slack message about releases

- test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidDoctorCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosDoctorCommandTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-with_local_result_dir.yml
Fixes #1065 
Doctor command does not fail when `local-result-dir` is present
> fix: Bad validation of `local-result-dir` by Doctor

- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
Fixes #1068 
Flank should display a warning instead of throw exception while creating bucket fails.
> fix: Avoid fast fail while creating a bucket

- test_runner/build.gradle.kts
Fixes #1063 
Tests passes and tested manually with bash files ./update-flank and the executable flank.
For example: `flank firebase test android run --output-style=single -c=../src/test/kotlin/ftl/fixtures/test_app_cases/flank-multiple-flaky.yml --project=flank-open-source` 
`flank-multiple-flaky.yml` needs a minor update if run from the bash folder, the pathing is incorrect. eg:
```
app: ../src/test/kotlin/ftl/fixtures/tmp/apk/app-debug.apk
test: ../src/test/kotlin/ftl/fixtures/tmp/apk/app-multiple-flaky-debug-androidTest.apk
```
The difficulty associated with minimizing a build results in possible missing classes within the shadowJar which is a difficult thing to pick up as you need integration tests rather than unit tests to achieve this. The tests were …
> build: Added options to minimize the shadowJar process

- .github/workflows/release.yml
Fixes #1086 
Now release action not updating tags on fetch, this causes issues when we try to reuse tag like in the case with ```v20.09.0``` version. I add ```-f``` parameter to allow update tags.
You can try run command
```
git fetch --prune  --tags
```
Git should return information like (in my case return information about other tags)
```
! [rejected]        v20.09.0                -> v20.09.0  (would clobber existing tag)
```
second run command with ```-f``` param
```
```
git fetch --prune  --tags -f
```
```
Git should return information about the update tags.
> fix: Fix release action

- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
- test_runner/src/main/kotlin/ftl/run/RefreshLastRun.kt
- test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
- test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
Fixes #1094
On the end of the output Flank should reprint matrices webLinks like:
```
MatrixResultsReport
1 / 1 (100.00%)
┌─────────┬──────────────────────┬────────────────────────────┬──────────────────────┐
│ OUTCOME │      MATRIX ID       │      TEST AXIS VALUE       │     TEST DETAILS     │
├─────────┼──────────────────────┼────────────────────────────┼──────────────────────┤
│ success │ matrix-a6sbyeuihlwta │ NexusLowRes-28-en-portrait │ 20 test cases passed │
└─────────┴──────────────────────┴────────────────────────────┴──────────────────────┘
Uploading MatrixResultsReport.txt .
Uploading JUnitReport.xml .
Matrices webLink
matrix-a6sbyeuihlwta https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/ …
```
> feat: print the matrices web link at the end of a run

- .github/workflows/macos_workflow.yml
- README.md
Fixes #296
Flank compiles with the JDK 11.
> build: update info to build with Java 11

- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt
Fixes #1099 
If the file does not exist on GCS `FlankGeneralError` is thrown
> feat: check if gcs path exist before run

- .github/workflows/release.yml
changes the release to run on ubuntu
> fix: Fixes release workflows

- flank-actions/Dockerfile
Removed the test command from docker file
Tests run fine locally however needs a production run
> fix: dockerfile fix for slack message send

- .env
- docs/test_artifacts.md
- flank-scripts/bash/flankScripts
- test_projects/android/bash/generate-multi-modules-apks.sh
- test_projects/android/bash/generate_apks.sh
- test_projects/android/bash/generate_duplicated_names_apks.sh
- test_projects/android/ops.sh
- test_projects/ios/EarlGreyExample/.gitignore
- test_projects/ios/EarlGreyExample/EarlGreyExample.xcodeproj/project.pbxproj
- test_projects/ios/EarlGreyExample/EarlGreyExample.xcodeproj/xcshareddata/xcschemes/EarlGreyExampleSwiftTests.xcscheme
- test_projects/ios/EarlGreyExample/ops.sh
- test_projects/ops.sh
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-multiple-duplicated.yml
Fixes #899 
1. Source the `.env` file by running `source .env` in your project root.
2. Run `update_test_artifacts all` and wait until the process will finish with no errors.
3. Check if test artifacts in `test_runner/src/test/kotlin/ftl/fixtures/tmp` are updated correctly.
> ci: add new bash scripts for test artifacts generation

- test_runner/src/main/kotlin/ftl/json/OutcomeDetailsFormatter.kt
- test_runner/src/main/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummary.kt
- test_runner/src/main/kotlin/ftl/reports/outcome/CreateTestSuiteOverviewData.kt
- test_runner/src/main/kotlin/ftl/reports/outcome/TestOutcome.kt
- test_runner/src/main/kotlin/ftl/reports/outcome/TestOutcomeContext.kt
- test_runner/src/main/kotlin/ftl/run/platform/common/BeforeRunMessage.kt
- test_runner/src/test/kotlin/ftl/json/OutcomeDetailsFormatterTest.kt
- test_runner/src/test/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummaryKtTest.kt
Fixes #1120 
Flank should reflect gcloud's output for robo tests:
Use this [SCRIPT](https://gist.github.com/pawelpasterz/cb0bdab77fc92ba8d83d3394faee3002) to simulate failing robo
All other functionalities related to running tests remain the same
> fix: Reflect gclouds outcome for robo tests

- integration_tests/src/test/kotlin/IntegrationTests.kt
Currently, iOS has only physical devices. Integration tests are launched at every commit for PR and both combined causes the` flank-open-source` project hits the quota limit extremely fast.
With quota limit exceeded PR automerge is blocked (IT tests are failing - quota limit)
This PR disables IT for iOS.
> build: Disable IT for iOS

- docs/using_different_environment_variables_in_different_matrices.md
- test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/AppTestPair.kt
- test_runner/src/main/kotlin/ftl/gc/android/SetupEnvironmentVariables.kt
- test_runner/src/main/kotlin/ftl/run/model/AndroidTestContext.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/AndroidTestConfig.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateInstrumentationConfig.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
- test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt
Fixes #1090 
Doc can be found [here](docs/using_different_environment_variables_in_different_matrices.md)
1. Configure test apks with enabled coverage
2. Prepare yaml config for flank like
```
gcloud:
app: ./src/test/kotlin/ftl/fixtures/tmp/apk/app-debug.apk
test: ./src/test/kotlin/ftl/fixtures/tmp/apk/app-multiple-success-debug-androidTest.apk
environment-variables:
coverage: true
coverageFile: /sdcard/main.ec
clearPackageData: true
directories-to-pull:
- /sdcard/
use-orchestrator: false
flank:
disable-sharding: false
max-test-shards: 2
files-to-download:
- .*/sdcard/[^/]+\.ec$
additional-app-test-apks:
- test: ./src/test/kotlin/ftl/fixtures/tmp/apk/app-multiple-success-debug-androidTest.apk
environmentVariables:
coverageFile: /sdcard/module_1.ec
- test: …
```
> feat: Allow Flank using different environment variables between test-apks

- .gitignore
- README.md
- test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
Fixes #1106 
This PR updates documentation for `test-targets-always-run` feature - test execution order is not guaranteed by flank.
> docs: Update documentation related with test-targets-always-run feature

- test_runner/src/main/kotlin/ftl/android/AndroidCatalog.kt
- test_runner/src/main/kotlin/ftl/reports/outcome/BillableMinutes.kt
- test_runner/src/test/kotlin/ftl/reports/outcome/BillableMinutesTest.kt
- test_runner/src/test/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummaryKtTest.kt
Fixes #1135 
Due to an incorrect device model check, all android models were considered as physical ones.
1) Start test run for any virtual device, observe cost report calculated for virtual device
2) Start test run for both, virtual and physical device, observe cost report consists of a section for physical and virtual devices
> fix: Fix cost report

- test_runner/src/main/kotlin/ftl/mock/TestArtifact.kt
This is fast fix for broken test artifacts url that causes test fails on CI
Test artifacts should be downloaded correctly on CI when [test_artifacts](https://github.com/Flank/test_artifacts) repo contains more than one release.
> ci: Fix test artifacts url

- flank-actions/Dockerfile
- flank-actions/entrypoint.sh
- flank-actions/slackService.kt
Fixes #1156 
The release notes were having AUTH issues. Fixed it as bash in GitHub actions was splitting the incoming cookie into multiple args instead of one. 
It is very difficult to test as it requires a full release.
Need to release this to the marketplace and then do another pull request to fix the action.
> fix: release notes slack tweaks

- test_runner/src/main/kotlin/ftl/json/MatrixMap.kt
- test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt
- test_runner/src/main/kotlin/ftl/reports/outcome/OutcomeMessageEnum.kt
- test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt
- test_runner/src/main/kotlin/ftl/run/exception/FlankException.kt
- test_runner/src/test/kotlin/ftl/json/MatrixMapTest.kt
- test_runner/src/test/kotlin/ftl/json/SavedMatrixTest.kt
Fixes #1155 
In command line
1. go to test_project dir
2. run ```./gradlew assembleRelease```
3 run flank with unsigned apk
```
gcloud:
app: ./test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-single-success-release-unsigned.apk
test: ./test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-single-success-debug-androidTest.apk
flank:
disable-sharding: true
```
4. flank should return user-friendly message reflecting gcloud cli message
Example:
```
┌─────────┬──────────────────────┬─────────────────┬──────────────┐
│ OUTCOME │      MATRIX ID       │ TEST AXIS VALUE │ TEST DETAILS │
├─────────┼──────────────────────┼─────────────────┼──────────────┤
│ INVALID │ matrix-1qa9ad1v8gswc │                 │ NO_SIGNATURE │ …
```
> feat: Improve error message on matrix failures

- flank-scripts/src/test/kotlin/flank/scripts/ci/nexttag/NextReleaseTagCommandTest.kt
Fixes #1176 
`./gradlew clean test` finishes without error
> fix: Fix flank-scripts test

- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/main/kotlin/ftl/run/DumpShards.kt
- test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/json/MatrixMapTest.kt
Fixes #1160 
1. Flank should dump shards and upload them to gcs on every run.
2.  When --disable-results-upload set, Flank should dump shards to file but not upload them to gcs.
> feat: Dump shards and upload on every run

- docs/bugs/914_falsy_positive_outcome_for_flaky_tests.md
Fixes #918 
This is only documentation. I cannot reproduce this issue so I update documentation only.
> docs: Investigation incorrect outcome for flaky tests

- test_runner/src/test/kotlin/ftl/json/SavedMatrixTest.kt
Fixes #918 
Ignored test should be removed from SavedMatrixTest
> test: Remove verification test for edge cases of incorrect outcome in flaky tests

- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/json/MatrixMapTest.kt
This reverts commit 256147fd951ea5949a3f7a79d3f2dfa8b674b8f8.
Feature to be implemented in https://github.com/Flank/flank/issues/1184
> fix: Revert "feat: Dump shards and upload on every run (#1171)"

- README.md
- docs/cucumber_support.md
Answers #1118 
This is documentation about using Cucumber in Flank. 
More work-related to Cucumber support will probably continue in task #1189
> docs: Added documentation about Cucumber support

- README.md
- test_runner/flank.yml
Fixes #1183 
All options are documented both in `.yml` example and `README.md` on main page
> docs: Added documentation about missing options

- .github/workflows/release.yml
This is a hotfix for missing env variables in the release workflow.
> fix: Release job missing env

- flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/ResolveArtifacts.kt
Fixes #1231 
1. Change branch to different than `master` or create new from the latest master.
1. Make sure there are no dedicated artifacts for the current branch.
1. Run `./gradlew clean test`.
1. `test_runner:testArtifacts` task shouldn't fail, tests should start correctly.
> fix: test_runner:resolveArtifacts task

- .github/workflows/integration_tests.yml
- .github/workflows/windows-non-wsl-workflow.yml
- .github/workflows/wsl-workflow.yml
Hotfix for empty branch name in workflows:
* `windows-non-wsl-workflow`
* `wsl-workflow and integration_tests`
* `integration_tests`
> fix: Empty branch name in workflows

- test_projects/android/app/src/androidTestMultiple/java/com.example.test_app.similar/SimilarNameTest1.kt
- test_projects/android/app/src/androidTestMultiple/java/com.example.test_app.similar/SimilarNameTest10.kt
- test_runner/src/main/kotlin/ftl/filter/TestFilters.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
- test_runner/src/test/kotlin/ftl/filter/TestFiltersTest.kt
- test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
Fixes #1227, #1234 
Similar class/method names were considered as one due to `testMethod.testName.startsWith(className)` check, with:
```
test-targets:
- class foo.bar.TestClass1
```
all `foo.bar.TestClass1`, `foo.bar.TestClass121`, `foo.bar.TestClass1aaaa` return `true` for `shouldRun` check. The same is applicable for test methods
1. build finish without any errors
1. generate apks with `[flank root] ./test_projects/android/bash/generate_apks.sh ~`
1. start flank run with config: 
```yaml
gcloud:
app: ~/app-debug.apk
test: ~/app-multiple-success-debug-androidTest.apk
test-targets:
- class com.example.test_app.similar.SimilarNameTest1
```
and observe only 3 tests are launched
1. start flank run with config: 
```yaml
gcloud:
app: ~/app-debug.apk
test: …
```
> fix: Fix withClassName filter

- .github/workflows/release.yml
- README.md
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/Type.kt
- test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
> feat: Add type

- .github/workflows/update_dependencies.yml
Fixes #1239 
Adds current date to dependency update PR title and branch name:
`dependencies-update-2020-10-15`
`build: Dependencies updates [2020-10-15]`
> ci: Add current date to dependecy PR

- test_runner/build.gradle.kts
Fixes incorrect revision for locally built shadowJar.
1. Run `./gradlew updateFlank/flankFullRun/shadowJar`
1. Run `flank -v`
1. Compare revision with latest commit hash on current branch
> fix: Disable cache for :test_runner:shadowJar task

- README.md
Proper link redirects to the documentation page
> fix: Flank web documentation link

- .github/workflows/wsl-workflow.yml
- flank-scripts/bash/buildFlankScripts.bat
- flank-scripts/bash/buildFlankScripts.sh
- flank-scripts/bash/flankScripts.bat
- test_runner/build.gradle.kts
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
Fixes #1237 
Please do not merge this PR if any Windows job fails
Flank workflows on Windows work properly
> fix: Fix running flank workflows on Windows

- .github/workflows/release_notes_generation.yml
Fixes #1213 
Github app token is generated using [this](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens) instructions
All jobs are run properly in created PR (builds + integration tests when 2+ approves) when run release notes jobs.
> ci: Use Github app token for creating release notes

- test_runner/src/main/kotlin/ftl/args/IArgs.kt
Fixes #1241 
Virtual test shards limit increased to 500
> feat: Update test shard limits

- test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
- test_runner/src/test/kotlin/ftl/run/platform/RunAndroidTestsKtTest.kt
Fixes #1258 
1. When ```num-test-runs``` set Flank should add to the matrix directory name ```_$index``` on end.
2. When ```num-test-runs``` not set directory name shouldn't contain an additional index.
> fix: Add additional index to matrix when multiple test runs

- .github/workflows/integration_tests.yml
- .github/workflows/windows-non-wsl-workflow.yml
- .github/workflows/wsl-workflow.yml
Fixes #1264 
To prevent merging code which is not stable, Integration tests should run for each new push to pull request (within 2+ approves)
> ci: Refresh integration tests

- docs/index.md
- test_runner/flank.ios.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
- test_runner/src/main/kotlin/ftl/config/common/CommonGcloudConfig.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/android/Utils.kt
- test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/UploadOtherFiles.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
Fixes #1199
Other files could be sent using `--other-files` CLI or `other-files` YAML config for iOS
> feat: Add Other Files for iOS

- docs/index.md
- test_runner/flank.ios.yml
- test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
- test_runner/src/main/kotlin/ftl/config/ios/IosGcloudConfig.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/android/Utils.kt
- test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/UploadApks.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
Fixes #1195
1. Add additional ipa using `--additional-ipas` or using `.yaml` option `additional-ipas`.
2. Check if `.ipa` files are uploaded
> feat: Add Additional Ipas option to iOS

- test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
- test_runner/src/test/kotlin/ftl/ios/XctestrunTest.kt
> test: Disable iOS test for Windows

- .github/workflows/integration_tests.yml
PR number for event `pull_request_review` is not correctly delivered withing `${{github.event.number}}`.
It needs to be fetched from `$GITHUB_REF`
> fix: Fix getting PR number on pull_request_review

- .github/workflows/integration_tests.yml
- docs/windows_and_github_actions.md
- test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
Fixes #1282 
Integration tests on windows should works
> fix: Integration tests on windows

- .github/workflows/ubuntu-workflow.yml
`github-actions[bot]` comments are updated instead of creating a new one.
Used GMT+0 timezone for the timestamp
> ci: Update existing bot comment

- docs/index.md
- test_runner/flank.ios.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/Type.kt
- test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
- test_runner/src/main/kotlin/ftl/config/common/CommonGcloudConfig.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/yml/TypeTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
Fixes #1194 
Flank properly read type passed to `gcloud` configuration `.yaml` block or using CLI option `--type`.
Later on it will be used to run gameloop in #1277
> feat: Add Type to iOS

- docs/index.md
- test_runner/flank.ios.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
- test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
- test_runner/src/main/kotlin/ftl/config/common/CommonGcloudConfig.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
> feat: ios scenario numbers

- docs/index.md
- test_projects/ios/EarlGreyExample/EarlGreyExample.xcodeproj/project.pbxproj
- test_projects/ios/EarlGreyExample/EarlGreyExampleSwift/ViewController.swift
- test_projects/ios/FlankExample/FlankExample/ViewController.swift
- test_runner/flank.ios.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
- test_runner/src/main/kotlin/ftl/config/common/CommonGcloudConfig.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/android/Utils.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
Fixes #1198 
Can set ```directories-to-pull``` in iOS
> feat: iOS add directories-to-pull 

- docs/index.md
- test_runner/flank.ios.yml
- test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/config/ios/IosGcloudConfig.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
Fixes #1197 
`--test-special-entitlements` is properly passed as a parameter using CLI and `yaml` config.
I've tested this option using Gcloud and Flank and behavior is the same.
I do not know how to test the impact  of this option on tests
> feat: Add --test-special-entitlements for iOS

- test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Fixes #1294 
1. Prepare config, for instance:
```
gcloud:
app: [any app]
flank:
legacy-junit-result:
```
(notice no value for `legacy-junit-result`)
1. Run flank with created config
1. Flank run should terminate with a message `Invalid value for [legacy-junit-result]: no argument value found` and without any stack trace
1. Run again but with `--legacy-junit-result` flag
1. Flank should proceed normally and `legacy-junit-result` should be equal `true`
> fix: Print formatted message instead of throwing NPE

- .gitignore
- test_runner/src/main/kotlin/ftl/run/DumpShards.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
Fixes #1296 
1. Prepare config:
```
gcloud:
app: [app from test artifacts]
test: [multiple-success test apk]
flank:
max-test-shards: 50
```
1. Run flank for android with --dump-shards
1. Observe `Saved 15 shards to android_shards.json` is being printed.
> fix: Fix incorrect printed shards number

- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/config/Credentials.kt
- test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/gc/GcTesting.kt
- test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
- test_runner/src/main/kotlin/ftl/gc/UserAuth.kt
- test_runner/src/main/kotlin/ftl/http/ExecuteWithRetry.kt
- test_runner/src/main/kotlin/ftl/run/exception/FlankException.kt
- test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt
- test_runner/src/test/kotlin/ftl/gc/UserAuthTest.kt
Fixes #1293
When there is a problem with the token listed in the checklist, a proper message with fix instructions is displayed and a bad token file is deleted
> fix: Handling broken token issues

- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
- test_runner/src/main/kotlin/ftl/mock/MockServer.kt
- test_runner/src/main/kotlin/ftl/reports/api/PerformanceMetrics.kt
- test_runner/src/main/kotlin/ftl/reports/api/ProcessFromApi.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt
- test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt
- test_runner/src/test/kotlin/ftl/reports/api/PerformanceMetricsTest.kt
- test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
Fixes #1285
Performance metrics are uploaded for each Android run on physical device
> feat: Added Performance Metrics for Android

- docs/index.md
- test_runner/flank.ios.yml
- test_runner/flank.yml
Fixes #1297 
Adds names and updates docs
> docs: Update documentations & Add Headings

- test_runner/src/main/kotlin/ftl/util/MatrixUtil.kt
- test_runner/src/test/kotlin/ftl/util/MatrixUtilTest.kt
Fixes #1309 
Nested directories are supported out of the box in GCloud results upload. 
However Flank has an issue that it throws an exception because it did not properly store results in the local directory.
In order to support nested directories, local issue must be fixed
1. Set configuration to contains nested result directories usimg `results-dir`
ex: 
```yaml
gcloud:
...
results-dir: nested/results
....
```
2. Run tests and see that results are properly updated to  GCloud storage and stored locally
> fix: Nested subdirectories in results-dir

- .mergify.yml
Mergify will use PR title and body as commit message and description when will merge PR.
It prevents us for having dummy message as commit messages and long list of unsquashed messages in description
> chore: use title+body for commit message

- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/reports/api/PerformanceMetrics.kt
- test_runner/src/main/kotlin/ftl/util/ProgressBar.kt
- test_runner/src/test/kotlin/ftl/reports/api/PerformanceMetricsTest.kt
- test_runner/src/test/kotlin/ftl/util/ProgressBarTest.kt
Fixes #1322 
1. Run flank on Android physical device. For example with configuration entry:
```yaml
gcloud:
...
device:
- model: OnePlus6T
version: 28
...
```
2. Run Flank with multiple matrices. Example with using option
```yaml
...
flank:
num-test-runs: 2
...
```
3. Check that `performanceMetrics.json` is uploaded for each matrix
> fix: Uploading performance metrics for multiple matrices

- test_runner/src/main/kotlin/ftl/android/AndroidCatalog.kt
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
- test_runner/src/main/kotlin/ftl/ios/IosCatalog.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Fixes #1328 
1. Run Flank with a configured device with not supported API level
```
device:
- model: OnePlus6T
version: 19
```
or if you want to check how the message looks when we have more than one supported version
```
device:
- model: Nexus7
version: 28
```
2. Error message should look like:
```
Incompatible model, 'OnePlus6T', and version, '19'
Supported version ids for 'OnePlus6T': 28
```
> fix: Fix printing supported versions id 

- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/main/kotlin/ftl/run/DumpShards.kt
- test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
- test_runner/src/main/kotlin/ftl/run/RefreshLastRun.kt
- test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt
- test_runner/src/main/kotlin/ftl/run/common/UpdateMatrixFile.kt
- test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
- test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/UploadApks.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/UploadOtherFiles.kt
- test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
- test_runner/src/main/kotlin/ftl/run/platform/common/BeforeRunMessage.kt
- test_runner/src/main/kotlin/ftl/run/platform/common/BeforeRunTests.kt
- test_runner/src/main/kotlin/ftl/util/FileReference.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
- test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
- test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt
- test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
- test_runner/src/test/kotlin/ftl/run/platform/RunAndroidTestsKtTest.kt
This PR is a cherrypicked refactor from #1321 
After merging this one, the #1321 will slim down a little.
> refactor: Simplify beforeRunTests return singature

- .github/workflows/integration_tests.yml
Fixes #1337 
This PR adds step for IT workflow. It checks with `git diff` if any modified/removed/created/moved files were in `test_runner` and/or `integration_tests` directory.
No straightforward way to do this. The added step is a simple bash script that sets output either to true or false.
To verify you can copy the script and run locally
```
git diff --name-only --diff-filter=AMDR HEAD^ HEAD > diffs.txt
echo "---------------"
cat diffs.txt
echo "---------------"
SHOULD_RUN='false'
while IFS= read -r file
do
if [[ $file == test_runner/* ]] || [[ $file == integration_tests/* ]]; then
SHOULD_RUN='true'
break
fi
done < diffs.txt
rm diffs.txt
echo "Should run IT: ${SHOULD_RUN}"
echo "::set-output name=should_run::${SHOULD_RUN}"
```
If case there are any …
> ci: Add directory filter for IT

- docs/onboarding/5_code_review.md
- mkdocs.yml
This pull request adds a missing page about code review to documentation.
> docs: Add documentation about code review by step

- .github/workflows/create_new_release.yml
- .github/workflows/pr_checks.yml
- .github/workflows/release.yml
- .github/workflows/release_flank_scripts.yml
- .github/workflows/release_notes_generation.yml
- .github/workflows/update_dependencies.yml
- build.gradle.kts
- flank-scripts/build.gradle.kts
- test_runner/build.gradle.kts
Fixes #1347
`flank-scripts` is now published to JFrog Bintray [1], so instead of building `flank-scripts` each time when running some workflow on GitHub actions or when you need it, you could just download it using simple gradle task[2].
`flank-scripts` support now versioning, so there is a requirement to update its version each time you changed some files inside `flank-scripts` directory, otherwise, detekt task will fail[3].
Each GitHub actions workflow is updated to download latest version instead of building `flank-scripts` to save time and resources.[4]
[1] 
1. Run `gradlew :flank-scripts:bintrayUpload` (bintray account needed)
1. Flank scripts should be updated on bintray
[2]
1. Run `gradlew :flank-scripts:download`
1. `flankScripts.jar` should be …
> ci: Publishing and downloading flank scripts

- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/utils/Git.kt
When cannot get the branch name from git or `HEAD_REF` is missing. Tests artifacts are downloaded for master branch
> fix: Add fallback when cannot get reference to avoid failing tests on release

- docs/index.md
- test_runner/flank.ios.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/config/common/CommonGcloudConfig.kt
- test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
- test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Fixes (N/A)
Ran a locally built jar in CI, verified that this flag is behaving as expected.
When a matrix hits an infrastructure errors, it is automatically retried. This can cause issues in time sensitive scenarios, as results can take ~5-15m longer to report after an infrastructure error occurs. This PR exposes this flag via the CLI.
> feat: Add support for "fail fast" feature on FTL

- .github/workflows/release_flank_scripts.yml
- flank-scripts/README.md
- flank-scripts/bash/flankScripts.bat
- flank-scripts/build.gradle.kts
Fixes #1368
**Version check should be performed also vs local file changes**
When some `flanks-scripts` are changed `detekt`/`check` or `checkIfVersionUpdated` do not fail if version is updated. No matter if in local files or committed to the branch
**Tasks should run on demand**
Task run only when using `gradlew :flank-scripts:checkIfVersionUpdated` or any other task which depends on `detekt`
> fix: Fix Flank Scripts version verification tasks

- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GenerateChangeLog.kt
- flank-scripts/src/main/kotlin/flank/scripts/exceptions/FlankScriptsExceptionMappers.kt
- flank-scripts/src/main/kotlin/flank/scripts/github/GithubApi.kt
- flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubCommit.kt
- flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubCreateIssue.kt
- flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubCreateIssueComment.kt
- flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubUpdateIssue.kt
- flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubWorkflowRun.kt
- flank-scripts/src/main/kotlin/flank/scripts/github/objects/GithubPullRequest.kt
- flank-scripts/src/main/kotlin/flank/scripts/pullrequest/FindReferenceIssue.kt
- flank-scripts/src/main/kotlin/flank/scripts/pullrequest/SetLabels.kt
- flank-scripts/src/main/kotlin/flank/scripts/utils/Serialization.kt
- flank-scripts/src/test/kotlin/flank/scripts/GithubMockServerHandler.kt
- flank-scripts/src/test/kotlin/flank/scripts/github/GithubApiTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/pullrequest/FindReferenceIssueTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/utils/SerializationTest.kt
Fixes #1377 
This PR adds new requests for flank's GH client. Currently not used. Commit was cherry-picked to make future PR (related to flank scripts/IT) smaller
N/A
> ci: Update GH API

- docs/index.md
- docs/smart_flank.md
- test_runner/.gitignore
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/main/kotlin/ftl/reports/xml/JUnitXml.kt
- test_runner/src/main/kotlin/ftl/reports/xml/model/JUnitTestResult.kt
- test_runner/src/test/kotlin/ftl/fixtures/empty_result/.gitignore
- test_runner/src/test/kotlin/ftl/fixtures/empty_result/JUnitReport.xml
- test_runner/src/test/kotlin/ftl/fixtures/empty_result/matrix_ids.json
- test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
- test_runner/src/test/kotlin/ftl/reports/xml/JUnitXmlTest.kt
Fixes #1382 
TLDR;
* fix NPE when `<testsuites/>` was deserialized (a workaround was needed though)
* prevent XML results from being uploaded (for smart flank) if contain no results
When an infrastructure error occurs result matrix is empty which leads to empty `JUnitTestResult`being created. Flank should not upload empty results to prevent old data corruption. 
Flank should also handle XML results with a self-closed root element (XML results for smart flank can be also uploaded manually). That could be easily fixed by changing `EMPTY_ELEMENT_AS_NULL` to false but flank uses this configuration quite extensively (ex skipped tag), so it's not an option. A small workaround was implemented: when the XML file is parsed flank checks if the string contains `<testsuites/>`. If does, an empty …
> fix: Fix NPE

- docs/test_sharding.md
Fixes #1386 
Firebase updated orchestrator version to ```1.3.0```.  Here is a link with information https://firebase-community.slack.com/archives/C1MTSQ5QT/p1607451331260800?thread_ts=1607442552.258900&cid=C1MTSQ5QT
> docs: Update orchestrator version in docs

- integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
- integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
- test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
Fixes #1388 
1. run ios test with config
```
gcloud:
test: [path to zip]
xctestrun-file: [path to xctestrun]
flank:
test-targets:
- nonExisting/Class
```
1. Flank should print args before any validation (ios and android)
1. Exit code should be 1
1. Integration tests should works
> fix: Print args when iOS tests are not found

- test_runner/src/test/kotlin/ftl/cli/firebase/CancelCommandTest.kt
Fixes #1403 
1. If exist remove ```test_runner/results```
1. run only ```CancelCommandTest.cancelCommandRuns``` test
1. Test should pass
1. If exist remove ```test_runner/results```
1. run ```./gradlew check```
1. Test should pass
1. You should have ```test_runner/results``` with some subdirectories with test results
1. Check ```test_runner/results``` contains ```a``` directory without ```matrix_ids.json```. This directory cause problem on Ubuntu workflow. Remove rest of directories (```test_runner/results``` should contain only ```a``` directory)
1. run only ```CancelCommandTest.cancelCommandRuns``` test
1. Test should pass
> fix: cancelCommandRuns should works independent

- integration_tests/src/test/kotlin/integration/GameloopIT.kt
- integration_tests/src/test/resources/cases/flank_android_gameloop_success.yml
- integration_tests/src/test/resources/compare/GameloopIT-android-compare
Fixes #1348 
1. Run ```./gradlew IntegrationTests```
1. ```integration.GameloopIT``` should run
1. All integration tests should pass
> feat: Add basic gameloop IT for Android

- .github/workflows/full_suite_integration_tests.yml
- integration_tests/build.gradle.kts
Fixes #1349
Current flows:
1. Schedule and manual trigger
- should cancel other builds in progress
- should run full integration tests on master branch
- should process results using flank scripts
2. Comment trigger
- should get pr number
- should post an issue comment
- should run full integration tests on PR branch
- should update comment based on test results
Integration tests run:
1. Integration tests build flank when the environmental variable `CI` is set to true
2. Integration tests do not build flank locally( when variable `CI` is set to false)
Comment trigger
1. Integration tests full suite is triggered by posting comment `@flank-it`
2. When Github action started 👀  are displayed under user comment
3. When Integration tests started comment is …
> ci: trigger integration tests from pr comment

- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/dependencies/update/DependenciesResultCheck.kt
- flank-scripts/src/main/kotlin/flank/scripts/dependencies/update/DependencyExtensions.kt
- flank-scripts/src/main/kotlin/flank/scripts/dependencies/update/DependencyUpdate.kt
- flank-scripts/src/main/kotlin/flank/scripts/dependencies/update/GradleDependency.kt
- flank-scripts/src/main/kotlin/flank/scripts/dependencies/update/UpdateGradle.kt
- flank-scripts/src/main/kotlin/flank/scripts/dependencies/update/UpdateVersionsInFile.kt
- flank-scripts/src/main/kotlin/flank/scripts/utils/Version.kt
- flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/DependencyExtensionsTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/UpdateGradleTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/UpdateVersionsInFileTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/testfiles/expected_gradle-wrapper.properties_RC.test
- flank-scripts/src/test/kotlin/flank/scripts/utils/TestParsers.kt
- flank-scripts/src/test/kotlin/flank/scripts/utils/VersionParseTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/utils/VersionToStringTest.kt
Fixes #1411 
Implement `Version` class (and related logic) to handle dependencies versioning
1. run 
```
git checkout master &&\
./gradlew clean assemble &&\
./gradlew dependencyUpdates -DoutputFormatter=json -DoutputDir=. &&\
java -jar ./flank-scripts/build/libs/flank-scripts.jar  dependencies update &&\
git diff >> dep_master
```
1. run
```
git checkout . &&\
git checkout 1411-implement-version &&\
./gradlew clean assemble &&\
./gradlew dependencyUpdates -DoutputFormatter=json -DoutputDir=. &&\
java -jar ./flank-scripts/build/libs/flank-scripts.jar  dependencies update &&\
git diff >> dep_version
```
1. compare dep files
```
diff dep_master dep_version
```
1. there should be no differences (nothing is printed to the console, exit code = 0)
> ci: 1411 implement version

- test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
This is a fix for failing https://scans.gradle.com/s/b76gcx7urgj7e/tests/:test_runner:test/ftl.shard.ShardTest/performance%20calculateShardsByTime#1
Basically, `mockArgs` method is extremely CPU consuming and its time should not be measured
> fix: Fix calculate shards test

- test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
This is another fix for the test issue https://github.com/Flank/flank/runs/1576759651?check_suite_focus=true, |
because the previous one (https://github.com/Flank/flank/pull/1413) was not enough.
The UT `performance calculateShardsByTime` seems to be flaky because the results depend on CPU performance and usage. 
My proposition is to rerun shards calculation if run time in ms grater than expected or attempt number not reached max value.
> fix: Add attempts to performance test

- docs/index.md
- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
- test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
- test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
- test_runner/src/test/kotlin/ftl/args/FetchProjectIdTest.kt
- test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt
Fixes #1407 
Flank will now use `GOOGLE_APPLICATION_CREDENTIALS` env first, to parse and get project id. (previously the first one was `GOOGLE_CLOUD_PROJECT`
1. build flank
1. remember to use the fat jar to launch test runs `java -jar ./test_runner/build/libs/flank.jar`
1. create dummy `echo '{"project_id":"any funny project id here"}' >> test.json`
1. export variable `export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/test.json"`
1. export variable `export GOOGLE_CLOUD_PROJECT="another project id"`
1. run any flank test run (within the same terminal window)
1. If you are creative enough you should get 404 (interesting fact: I used `ddd` project id during local tests and it turned out there is such project, I received 403 instead 😄 ) with a message 
1. 404 -> …
> feat: Default project Id - use GOOGLE_APPLICATION_CREDENTIALS first, then GOOGLE_CLOUD_PROJECT

- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/github/GithubApi.kt
- flank-scripts/src/main/kotlin/flank/scripts/github/commons/LastWorkflowRunDate.kt
- flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubCommit.kt
- flank-scripts/src/main/kotlin/flank/scripts/integration/WorkflowSummary.kt
- flank-scripts/src/main/kotlin/flank/scripts/pullrequest/GitHubIssuePropertiesCopy.kt
- flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/FirebaseCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/apiclient/GenerateJavaClientCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/apiclient/UpdateApiJsonCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/zenhub/ZenHubAPI.kt
- flank-scripts/src/main/kotlin/flank/scripts/zenhub/ZenHubIssue.kt
- flank-scripts/src/test/kotlin/flank/scripts/FuelMockServer.kt
- flank-scripts/src/test/kotlin/flank/scripts/GithubMockServerHandler.kt
- flank-scripts/src/test/kotlin/flank/scripts/ZenHubMockServerHandler.kt
- flank-scripts/src/test/kotlin/flank/scripts/zenhub/ZenHubCopyEstimationsTest.kt
Fixes #1431 
No new logic implemented. Unit tests + integration tests should be enough.
> refactor: Small changes in flank-scripts module

- .github/workflows/update_dependencies_and_client.yml
- common/src/main/kotlin/flank.common/Strings.kt
- flank-scripts/README.md
- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/github/GithubApi.kt
- flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/FirebaseCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/CheckForSDKUpdateCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/CommitList.kt
- flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/Extensions.kt
- flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/LastSDKUpdateRun.kt
- flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/OpenedUpdates.kt
- flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/SDKUpdateContext.kt
- flank-scripts/src/main/kotlin/flank/scripts/zenhub/ZenHubAPI.kt
- flank-scripts/src/main/kotlin/flank/scripts/zenhub/objects/ConvertToEpicRequest.kt
- flank-scripts/src/test/kotlin/flank/scripts/shell/firebase/sdk/SDKUpdateTest.kt
Fixes #1422 
TLDR;
Fetch and parse `gcloud SDK` release notes to find new features/changes. If there are any -- create an epic with each new feature/change as a separate issue.
1. Get the latest commit (current master sha)
1. Get previously checked commit (one that was previously 'latest')
1. Get new and old versions (fetch `VERSION` file) based on commits
1. If `new` == `old` -- no updates, exit process
1. Fetch `RELEASE_NOTES` file from the current master
1. Extract (with regex) section with chnages from `new` (included) till `old` (excluded)
1. Extract `Firebase Test Lab` changes only
1. Create a list of changes (each `*` is considered as a separate change/feature)
1. Create issues for each change
1. Create an issue with all changes and convert it to epic
1. Link 'change issues' to the …
> feat: 1422 autodetect new gcloud features

- .github/workflows/update_dependencies_and_client.yml
Fixes broken update dependency workflow.
TLDR; generated token cannot be shared between jobs (GitHub deletes it automatically)
> ci: Fix dependency update workflow

- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Fixes #1444
`test-runner-class` has a default value (the last name extracted from the APK manifest), so it is not needed to fast fail if this option is not specified
1. Set `gcloud.type: instrumentation` to your `flank.yml`.
2. Run `flank run android`
3. Do not set `test-runner-class`
4. Tests do not fast fail
> fix: Fix problem with test-runner-class

- .github/workflows/cla.yml
- contributing.md
Fixes #638
Added Github action which requires the contributor to sign CLA agreement by making a comment `I have read the CLA Document and I hereby sign the CLA`
Flank organization members do not need to sign contribution, as well as bots
1. User create Pull request
1. CLA assistant make a comment that User needs to sign CLA
3. User sign CLA by posting a comment `I have read the CLA Document and I hereby sign the CLA`
4. User signature is stored in `cla/v1/signatures.json` on `cla_signatures` branch
5. CLA assistant make a comment that all committers signed CLA
**The real testing scenario will be done in the next PR to make sure that everything works correctly!!!**
> ci: Added CLA assistant

- .githooks/linkHooks.bat
- .githooks/linkHooks.sh
- .gitignore
- buildSrc/src/main/kotlin/Versions.kt
- common/src/main/kotlin/flank.common/Files.kt
- docs/onboarding/1_environment_setup.md
- docs/onboarding/2_contribution.md
- flank-scripts/README.md
- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/Main.kt
- flank-scripts/src/main/kotlin/flank/scripts/contribution/ContributionCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/contribution/githooks/GitHooksLinkCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/contribution/ideaktlint/IdeaKtlintCodeStyleCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/pullrequest/GitHubIssuePropertiesCopy.kt
- flank-scripts/src/main/kotlin/flank/scripts/utils/ShellExecute.kt
- flank-scripts/src/test/kotlin/flank/common/FilesTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/integration/ProcessResultTest.kt
Fixes #1423 
Tested for Windows.
> feat: Rewrite pre-commit hook & ktlint apply to idea into Flank Scripts

- .github/workflows/full_suite_integration_tests.yml
- .github/workflows/integration_tests_pointer.yml
- .github/workflows/update_dependencies_and_client.yml
- .github/workflows/update_dependencies_pointer.yml
- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/integration/WorkflowSummary.kt
- flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/LastSDKUpdateRun.kt
Due to GH API limitation workflow is unable to fetch info about itself. Dates of previous runs are used in scripts. An empty array is returned instead.
As a workaround to overcome those limitations two new workflows are introduced.
Their intention is "just to be triggered" and therefore preserve the date which is used in dependencies and IT workflows.
There is no easy way to test the implementation. This PR introduced 2 new workflows which can be triggered after the merge to master.
> ci: Use pointer workflows to preserve run date

- buildSrc/src/main/kotlin/Versions.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/CommonRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
- test_runner/src/main/kotlin/ftl/config/Create.kt
Fixes #1452 
Picocli latest version causes that Flank does not work, it was caused by breaking changes that prevent the class to contain nested `@Mixin` annotated configuration classes.
It turns out that we do not need to change our logic of reading data in `mutableMap<String, Any?>`
All tests passed.
Flank works normally
> refactor: Update picocli to latest version

- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/github/commons/LastWorkflowRunDate.kt
- test_runner/src/main/kotlin/ftl/run/common/SaveSessionId.kt
`SaveSessionId` is using `Path.of` which is available since java 11. This PR changes logic to use `Paths.get` (available in java 8)
> fix: Fix incorrect method usage on master

- .github/workflows/full_suite_integration_tests.yml
- .github/workflows/update_dependencies_and_client.yml
- common/src/main/kotlin/flank/common/Files.kt
- common/src/test/kotlin/flank/common/FilesTest.kt
- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/github/commons/LastWorkflowRunDate.kt
- flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/LinkArtifacts.kt
- flank-scripts/src/test/kotlin/flank/scripts/shell/firebase/sdk/SDKUpdateTest.kt
Fixes #1434 
Simple solution. Increases space used but works without process elevation.
works on Pro + Home.
> fix: Resolve Fails on Windows

- common/src/main/kotlin/flank/common/PathHelper.kt
- test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt
- test_runner/src/main/kotlin/ftl/util/CrashReporter.kt
Fixes #
What was done?
* Fix NPE that was causing initialization error and flank crash as a result
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class flank.common.config.FlankPropertiesKt
at ftl.util.CrashReporterKt.report(CrashReporter.kt:31)
at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:78)
at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:12)
at ftl.Main$Companion.main(Main.kt:54)
at ftl.Main.main(Main.kt)
```
* `GoogleApiLogger` (all actually) was incorrectly enabled during Sentry client initialization. As result, output was flooded with logs if at least one FTL `IOException` was thrown
```
Jan 20, 2021 8:40:28 PM com.google.api.client.http.HttpRequest execute
CONFIG: …
```
> fix: Fix NPE and logging

- build.gradle.kts
- docs/index.md
- test_runner/flank.ios.yml
- test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
- test_runner/src/main/kotlin/ftl/config/ios/IosFlankConfig.kt
- test_runner/src/main/kotlin/ftl/ios/xctest/XcTestData.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/ios_test_plan.yml
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-single-only-test-configuration-ios.yml
- test_runner/src/test/kotlin/ftl/ios/xctest/XcTestDataTest.kt
Fixes #1379 
This PR adds to new options for flank: 
- `skip-test-configuration`
- `only-test-configuration`
Flank users can filter test configurations (inside of a test plan).
From project root:
```
. .env
cd ./test_runner/
flankScripts shell buildFlank 
flank ios run -c ./src/test/kotlin/ftl/fixtures/ios_test_plan.yml
```
additionally, edit `os_test_plan.yml` for testing different configurations.
> feat: Filtering test configurations (iOS TestPlans)

- integration_tests/src/test/kotlin/integration/GameloopIT.kt
Fixes #1522 
Integration tests work
> fix: Windows Integration tests

- .github/workflows/windows_workflow.yml
- common/src/main/kotlin/flank/common/Files.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/ios/xctest/common/InstallParseBinaries.kt
- test_runner/src/test/kotlin/ftl/analytics/UsageStatisticsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/ios/xctest/common/InstallParseBinariesTest.kt
- test_runner/src/test/kotlin/ftl/ios/xctest/common/ParseObjTestsKtTest.kt
- test_runner/src/test/kotlin/ftl/ios/xctest/common/ParseSwiftTestsKtTest.kt
Fixes #1528
Windows workflow runs and passes
> ci: Added Windows workflow

- .github/workflows/full_suite_integration_tests.yml
Fixes #1527 
Need it to be merged before its actual testing
> ci: Integration Test for all OS's

- buildSrc/src/main/kotlin/Versions.kt
- flank-scripts/build.gradle.kts
- flank-scripts/src/test/kotlin/flank/common/FilesTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/FuelMockServer.kt
What was done?
* remove `Should download file and store it and destination` test (it tests `downloadFile` which is actually a wrapper for fuel's download functionality)
* use `TemporaryFolder`
All workflows should finish without any error (especially `ubuntu-workflow`)
> fix: Fix flaky FilesTest

- .github/workflows/full_suite_integration_tests.yml
- common/src/main/kotlin/flank/common/Files.kt
- common/src/test/kotlin/flank/common/FilesTest.kt
- test_runner/src/main/kotlin/ftl/ios/xctest/common/InstallParseBinaries.kt
Fixes Nothing for now due to more changes to come
> A again more changes.
Need to test if these changes fix IT tests.
> fix: windows issues

- docs/flank-scripts/command_overview.md
Fixes #1545
This PR contains documentation for the proposition of restructuring flank-scripts CLI commands as well as a basic description of each of it
> docs: Flank-scripts command overview

- test_runner/build.gradle.kts
Fixes #1577 
Increase heap size for `test` task in `test_runner` module. This should mitigate `OutOfMemory` error during tests
1. Run `./gradlew clean flankFullRun` -- should finish without any error
2. We can rerun `ubuntu-workflow` a couple of times and each should end with success
> fix: Increase heap size

- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/cli/shell/BuildFtlCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/cli/shell/RunFtlLocalCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/cli/shell/UniversalFrameworkCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/cli/shell/buildexample/BuildExampleCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/ci/AppendReleaseNotes.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/ci/CreateReleaseNotes.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/common/ConventionalCommitFormatter.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/common/EarlGreyExampleConsts.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/common/GenerateChangeLog.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/common/ReleaseNotesWithType.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/release/hub/ReleaseFlank.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/shell/SetupIosEnv.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/BuildEarlGreyExample.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/BuildExample.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/BuildFtl.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/BuildIosIPA.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/BuildIosTestArtifacts.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/IosBuildCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/LipoHelper.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/RunFtlLocal.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/UniversalFramework.kt
- flank-scripts/src/test/kotlin/flank/scripts/ops/ci/releasenotes/AppendReleaseNotesTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/ops/ci/releasenotes/ConventionalCommitFormatterTest.kt
- flank-scripts/src/test/kotlin/flank/scripts/ops/ci/releasenotes/ReleaseNotesWithTypeTest.kt
Fixes #1543 
The tests should pass. Scripts should work as before.
> refactor: Flank scripts features not depends on each other

- docs/flank-scripts/ops_structure.md
Fixes #1542 
This is a proposal on how to organize `ops` package inside **flank-scripts**
> docs: flank-scripts ops package organization

- docs/flank-github-action/flank_github_acton_sdd.md
Fixes #1419 
This is a proposal on how to implement Github action for running Flank 🎉
> docs: Github action SDD proposal

- common/src/main/kotlin/flank/common/Os.kt
- integration_tests/src/test/kotlin/integration/GameloopIT.kt
Fixes #1586 
Needs to be merged before tested.
> fix: Remove GameloopIT test for IOS

- .github/workflows/release_flank_scripts.yml
- build.gradle.kts
- buildSrc/src/main/kotlin/Plugins.kt
- buildSrc/src/main/kotlin/Versions.kt
- flank-scripts/build.gradle.kts
Fixes #1565
- [Flank scripts is released to Github Packages](https://github.com/Flank/flank/packages/628838)
- [Flank scripts is released to Github Releases](https://github.com/Flank/flank/releases/tag/flank-scripts-1.6.3)
- Above functions could be run using (`./gradlew flank-scripts:releaseFlankScripts`) ([Github CLI tool required](https://github.com/cli/cli))
- Download function works properly (`./gradlew :flank-scripts:download`) ([Github CLI tool required](https://github.com/cli/cli))
> ci: Publish Flank-scripts to Github

- docs/feature/1532-explore-test-target-for-shards-with-extra-features.md
> docs: Explore test-targets-for-shards SDD

- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/cli/release/ReleaseCommand.kt
Adds missing `NextTagCommand` and `GenerateReleaseNotesCommand` to the `release` command
> ci: Add missing subcommands

- .github/workflows/full_suite_integration_tests.yml
- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/ProcessIntegrationTestsResult.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/ITResult.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/IntegrationResultContext.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/PrepareMessage.kt
- flank-scripts/src/test/kotlin/flank/scripts/ops/integrationtests/ProcessResultTest.kt
PR adds missing IT workflow logic
1. run `./gradlew build`
2. run
```
export IT_STATE='{
"windows-latest": "success",
"windows-latest-bs": "any/url/windows",
"ubuntu-latest": "SUCCESS",
"ubuntu-latest-bs": "any/url/ununtu",
"macos-latest": "success",
"macos-latest-bs": "any/url/mac"
}'
```
3. (?) optional -- you can change flank scripts settings (for example repo address) in`common/flank-debug.properties`
4. run
```
java -jar ./flank-scripts/build/libs/flank-scripts.jar integration_tests process_results \
--global-result=failure \
--rr=$IT_STATE  \
--github-token=[your gh token] \
--run-id=123456
```
5. A new issue is created, an example from my fork https://github.com/pawelpasterz/flank/issues/123
Full workflow can be tested once merged only
> ci: Update workflow file

- .github/workflows/release.yml
- test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
- test_runner/src/main/kotlin/ftl/reports/api/CreateTestExecutionData.kt
- test_runner/src/test/kotlin/ftl/reports/api/CreateTestExecutionDataKtTest.kt
Fixes #1634
Existing tests should not be broken
> fix: JUnitReport.xml only contained 50 test results

- .github/workflows/full_suite_integration_tests.yml
> ci: Treat env json as a string

- .github/workflows/release.yml
Snapshots are published to maven central
> fix: Snapshot publish by disabling closing staging artifacts

- test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
Fixes #1649
PR adds NPE handling when fetching results
1. build workflows finish with success
2. IT pass
> fix: Fix NPE in GcToolResults

- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
- test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
- test_runner/src/test/kotlin/ftl/test/util/FlankTestRunner.kt
- test_runner/src/test/kotlin/ftl/test/util/LocalGcs.kt
Fixes #1578 
Change description:
* there are only 2 tests that require pre-uploaded files -- now they upload filed on their own (`ArgsHelperTest#assertGcsFileExists succeeds` & `TestRunnerTest#mockedAndroidTestRun gcsAndHistoryName`)
* Google API provides `FakeStorageRpc` which is created with `LocalStorageHelper.getOptions()`
* `FakeStorageRpc` can be cleaned/reseted only by calling `LocalStorageHelper.getOptions()` (both its hashmaps are cleared)
* Above is, unfortunately, the only way to clear `FakeStorageRpc` -- storage has `reset` method but it's not exposed
* The `TestStorageProvider` is introduced to wrap additional test logic
* Intention behind `TestStorageProvider` is `GcStorage` should not be aware of how it is used (tests or production )
* The `TestStorageProvider` has nullable …
> test: Implement logic to clear LocalGcs after each test

- docs/flank-output-investigation/flank_current_output.md
- docs/flank-output-investigation/flank_output_propositon.md
- docs/flank-output-investigation/gcloud_current_output.md
Fixes #1555 
Please check **flank_output_propositon.md** for new output proposition.
**flank_current_output.md** and **gcloud_current_output.md** are added for comparsion
> docs: Add Flank output research docs

- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/ops/firebase/SaveServiceAccount.kt
Fixes #
When ```./config/gcloud``` path does not exist flank scripts should create directories.
> fix: Saving service account by flank script

- docs/feature/1609-add-apk-name-to-result-matrix.md
Fixes #1609 
Adds SDD for [Add apk name or module name to result matrix Result maxrix](https://github.com/Flank/flank/issues/1609)
You can see it [HERE](https://github.com/Flank/flank/blob/1609-add-apk-name-to-result-table-sdd/docs/feature/1609-add-apk-name-to-result-matrix.md)
> docs: Add SDD for 1609 feature request

- action.yml
Fixes #1598
Flank Github action works properly 🎉 
Please see [the test repository for running examples](https://github.com/Flank/flank-github-action-testing/actions/runs/636330677)
> feat: Run Flank Github action with config provided by user

- action.yml
- test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
- test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
Fixes #1599
Stores output path and gcloud path in file `flank-links.log`
Returns local and gcloud path after running flank.
<TODO>
> feat: Return directories path in Flank Github action

- common/src/main/kotlin/flank/common/Files.kt
- common/src/test/kotlin/flank/common/FilesTest.kt
- test_runner/src/main/kotlin/ftl/reports/output/OutputReport.kt
- test_runner/src/test/kotlin/ftl/reports/output/OutputReportTest.kt
When a user tries to dump shards AND the output report is enabled an error is thrown. This is due to the fact flank is trying to create `outputReport.json` file inside result directory which does not exist for dump shard run, to reproduce run on the current master:
1. add `output-report: json` to the config file
2. start flank with `--dump-shards`
3. see `FileNotFound` error
1. add `output-report: json` to the config file
2. start flank with `--dump-shards`
3. no error is thrown and flank finishes run normally
> fix: Fix output report error with dump shards

- action.yml
As you can see for [example in this run](https://github.com/Flank/flank-github-action-testing/runs/2087337805?check_suite_focus=true), output contains file name:
```
Local directory: /home/runner/work/flank-github-action-testing/flank-github-action-testing/results/2021-03-11_15-13-11.697000_GzOA/android_shards.json
Gcloud: https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2021-03-11_15-13-11.697000_GzOA
```
but it should be:
```
Local directory: /home/runner/work/flank-github-action-testing/flank-github-action-testing/results/2021-03-11_15-13-11.697000_GzOA
Gcloud: https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2021-03-11_15-13-11.697000_GzOA
```
This is a quick workaround to avoid making a new Flank …
> fix: Output path to local results github action

- common/build.gradle.kts
- flank-scripts/build.gradle.kts
- integration_tests/build.gradle.kts
- test_runner/build.gradle.kts
PR removes a couple of unused dependencies
Both build and IT run finish without any error
> refactor: Clean up dependencies

- README.md
- docs/flank-github-action/store_documentation.md
Fixes #1600
This is the description of the Flank Github action which goes to the Github marketplace.
Unfortunately, we could not point to custom documentation, so I have added a link to the main documentation
> docs: Create Github marketplace documentation for Flank action

- integration_tests/src/test/kotlin/integration/IntergrationTestsUtils.kt
- integration_tests/src/test/resources/compare/SanityRoboIT-compare
- test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt
- test_runner/src/main/kotlin/ftl/json/SavedMatrixTableUtil.kt
- test_runner/src/main/kotlin/ftl/reports/output/OutputReportLoggers.kt
- test_runner/src/test/kotlin/ftl/json/SavedMatrixTest.kt
- test_runner/src/test/kotlin/ftl/reports/output/OutputReportLoggersTest.kt
Fixes #1674
PR adds a new column (`APP NAME`) to the result table and updates the` outputReport.json` structure with an apk file name.
1. Launch test run with flank with `output-report: json`
2. When the run is finished you should see the additional column in the result table with the header `APP NAME`
3. There should be apk's file name used in the test
4. Open `outputReport.json` 
5. Check if `test_results` structure is similar to
```
"test_results": {
"matrix-afvw8zv215owa": {
"app": "app-debug.apk",
"test-axises": [
```
> feat: Add app name to the test result

- integration_tests/src/test/resources/compare/AllTestFilteredIT-android-compare
- integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare
- integration_tests/src/test/resources/compare/GameloopIT-android-compare
- integration_tests/src/test/resources/compare/GameloopIT-ios-compare
- integration_tests/src/test/resources/compare/IgnoreFailedIT-compare
- integration_tests/src/test/resources/compare/MultipleApksIT-compare
- integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
- integration_tests/src/test/resources/compare/RunTimeoutIT-compare
- integration_tests/src/test/resources/compare/SanityRoboIT-compare
- integration_tests/src/test/resources/compare/TestFilteringIT-compare
- test_runner/flank.ios.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
- test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Fixes #1710
2. launch test run with config:
```
flank:
max-test-shards: 5000000
```
3. you should see a validation error message `max-test-shards must be ...`
4. launch test run with config:
```
flank:
max-test-shards: 5000000
skip-config-validation: true
```
5. test run proceeds normally
> feat: Add option to skip config validation

- test_runner/src/main/kotlin/ftl/Main.kt
- test_runner/src/main/kotlin/ftl/cli/MainCommand.kt
- test_runner/src/test/kotlin/Debug.kt
- test_runner/src/test/kotlin/ftl/MainTest.kt
- test_runner/src/test/kotlin/ftl/test/util/TestHelper.kt
Fixes #1723 
It's just refactoring, all unit tests should pass.
> refactor: Separate main function from MainCommand

- docs/hld/flank-component-diagram.puml
Fixes #1510 
The architecture model above is based on well-known [PresentationDomainDataLayering](https://www.martinfowler.com/bliki/PresentationDomainDataLayering.html) proposed by Martin Fowler.
Basing on the model above will be easy to:
* scale the presentation layer by adding necessary implementations.
* replace external data providers.
* separate third-party library code from the domain, for keeping code clean.
* consider each layer as a separate module if needed.
* deliver output builds for different configurations.
* deliver domain layer even as a standalone library.
> docs: Add flank component diagram

- integration_tests/src/test/kotlin/integration/ManyTestsOnSingleShardIT.kt
- integration_tests/src/test/resources/cases/flank_android_many_tests_on_single_shard.yml
> test: Add IT for large shard test suite

- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidLocalesCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesDescribeCommand.kt
- test_runner/src/main/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesListCommand.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesDescribeCommandTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesListCommandTest.kt
Fixes #1706 
Rename package `ftl.cli.firebase.test.android.configuration` to `ftl.cli.firebase.test.android.locales`
Flank build and run as usual
> refactor: Rename cli package

- docs/feature/1692_test_case_based_retries.md
Fixes #1692
[Documentation for Test case based retries](https://github.com/Flank/flank/blob/1692_tcb_retries_docs/docs/feature/1692_test_case_based_retries.md)
> docs: Add HLD for Test case based retries

- test_runner/src/main/kotlin/ftl/ios/xctest/common/InstallParseBinaries.kt
- test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseObjTests.kt
- test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseSwiftTests.kt
- test_runner/src/main/kotlin/ftl/util/Bash.kt
Fixes #1686 
IT tests will work
> feat: Windows IOS integration tests

- test_runner/build.gradle.kts
- test_runner/src/main/kotlin/ftl/Main.kt
- test_runner/src/test/kotlin/ftl/MainTest.kt
Fixes #1780 
1. Run `./gradlew flankFullRun`
2. Unit tests pass
3. Follow 'steps to reproduce' in https://github.com/Flank/flank/issues/1780
1. Update flank in fladle to 21.04.0 with flankVersion = '21.04.0'
2. `./gradlew runFlank`
3. task proceeds without error
> fix: Fix entrypoint file name

- integration_tests/src/test/kotlin/integration/DumpShardsIT.kt
Fixes #1781 
Skip the failing IT test for now as there are more important tasks with more priority.
> fix: Skip Dump shards IT test

- docs/feature/1665-custom-sharding.md
- test_runner/src/main/kotlin/ftl/ios/xctest/XcTestData.kt
- test_runner/src/main/kotlin/ftl/run/DumpShards.kt
- test_runner/src/main/kotlin/ftl/util/ObfuscationGson.kt
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/custom_sharding_ios_v1.json
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/custom_sharding_ios_v2.json
- test_runner/src/test/kotlin/ftl/ios/xctest/XcTestDataTest.kt
- test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
Fixes #1665 
This is the first implementation of the custom sharding feature, below assumptions were made:
1. flank does not validate provided json -- we trust the user that he/she knows what is doing
2. `sharding-json` is the source of truth -- no smart sharding applied
3. dump shards structure was required to be updated
1. build flank `./gradlew flankFullRun`
2. create config yml 
```
gcloud:
test: [PATH]/EarlGreyExample.zip
xctestrun-file: [PATH]/EarlGreyExampleSwiftTests.xctestrun
flank:
max-test-shards: 2
disable-results-upload: true
disable-usage-statistics: true
```
3. run `flank firebase test ios run -c=[YOUR CONFIG] --dump-shards`
4. copy `ios_shards.json`, rename it and play around with shards, example: add another shard, move tests etc
5. add …
> feat: Implement custom sharding -- iOS

- docs/hypershard_android.md
- mkdocs.yml
Fixes #606 
Added tutorial and usage guide for using android
> docs: Hypershard android usage guide

- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/RefreshCommandTest.kt
Fixes #1789 
FTL API does not work properly with upper case letters in the project name, it does not report any issues, but results are empty. The project name could be just lower case, so this PR makes all projects names lower case, to make them work properly with FTL API
1. Run tests with the real project name, but make some letters upper case (ex. `Flank-Open-Source`)
2. All tests should run normally without any problems
> fix: Added workaround for uppercase project name

- docs/hypershard_ios.md
- mkdocs.yml
Fixes #766
Added tutorial and usage guide for using hypershard-ios
> docs: Added hypershard-ios setup tutorial

- docs/index.md
- test_runner/flank.ios.yml
- test_runner/flank.yml
Fixes #1792 
These changes fix bad information that flank requires project name instead of project id
> docs: Fix information about project id

- test_runner/src/main/kotlin/ftl/adapter/GoogleUserAuthorizationRequest.kt
- test_runner/src/main/kotlin/ftl/adapter/google/Credentials.kt
- test_runner/src/main/kotlin/ftl/adapter/google/UserAuth.kt
- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/data/UserAuthorization.kt
- test_runner/src/main/kotlin/ftl/domain/LoginGoogleAccount.kt
- test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
- test_runner/src/main/kotlin/ftl/gc/GcTesting.kt
- test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
- test_runner/src/test/kotlin/ftl/adapter/google/UserAuthTest.kt
Fixes #1740 
- Code is refactored according to the description in #1740 
- command `flank auth login` runs without any problems
> refactor: Refactor data scratch-authorization

- .github/workflows/pr_checks.yml
- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/cli/github/CopyIssuePropertiesCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/github/CopyGitHubProperties.kt
Estimations are not copied when creating a new pull request.
> ci: Disabled estimations copying

- integration_tests/src/test/kotlin/integration/LegacyResultIT.kt
- integration_tests/src/test/resources/cases/flank_android_single_legacy.yml
- integration_tests/src/test/resources/cases/flank_ios_single_legacy.yml
- test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
Fixes #1778 
All tests should pass, when using android tests with legacy mode Flank should generate JUnitReport in the results directory, performance metrics file should be created.
This pr is a revert of @piotradamczyk5 change related to ```performanceMetrics.json``` creation. I was checking this feature and still works fine. 
To test if ```performanceMetrics.json```  are created:
1. Run any test case with a physical device for e.g.
```  
device:
- model: starqlteue
version: 26
```
1.  Check if the Flank output contains a line about uploading ```performanceMetrics.json``` to gcs
```
Uploading [performanceMetrics.json] to https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2021-04-19_07-59-02.195180_AbIK/matrix_0/... …
```
> fix: Fix missing junit report in legacy mode

- integration_tests/build.gradle.kts
- integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
- integration_tests/src/test/kotlin/integration/CustomShardingIT.kt
- integration_tests/src/test/kotlin/integration/DumpShardsIT.kt
- integration_tests/src/test/kotlin/integration/GameloopIT.kt
- integration_tests/src/test/kotlin/integration/IgnoreFailedIT.kt
- integration_tests/src/test/kotlin/integration/LegacyResultIT.kt
- integration_tests/src/test/kotlin/integration/ManyTestsOnSingleShardIT.kt
- integration_tests/src/test/kotlin/integration/MultipleApksIT.kt
- integration_tests/src/test/kotlin/integration/MultipleDevicesIT.kt
- integration_tests/src/test/kotlin/integration/RunTimeoutIT.kt
- integration_tests/src/test/kotlin/integration/SanityRoboIT.kt
- integration_tests/src/test/kotlin/integration/TestFilteringIT.kt
- integration_tests/src/test/kotlin/integration/config/Categories.kt
PR introduces a category approach in IT. Tests are divided into `AndroidTest` and `IosTest` category. It can be achieved with annotating tests with either `@Category(AndroidTest::class)` or `@Category(IosTest::class)` 
There are slightly different rules applied to each category.
`AndroidTest` category:
* runs in parallel
* no fail-fast
* runs first
`IosTest` category:
* runs tests sequentially
* with fail-fast
* depends on `AndroidTest` category
For each category 2 new gradle tasks were created `instrumentationTestsAnroid` and `instrumentationTestsIos` -- each runs corresponding category.
`instrumentationTests` task was refactored and now it depends on android and ios tasks, forcing android category tests to run before iOS
Flank project keeps facing exceeded quota problem, mainly due to …
> test: Optimize quota usage in IT

- test_runner/src/main/kotlin/ftl/adapter/GoogleDeviceModel.kt
- test_runner/src/main/kotlin/ftl/adapter/google/DeviceModelAdapter.kt
- test_runner/src/main/kotlin/ftl/api/DeviceModels.kt
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
- test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
- test_runner/src/main/kotlin/ftl/domain/DescribeAndroidModels.kt
- test_runner/src/main/kotlin/ftl/domain/DescribeAndroidTestEnvironment.kt
- test_runner/src/main/kotlin/ftl/domain/DescribeIosModels.kt
- test_runner/src/main/kotlin/ftl/domain/DescribeIosTestEnvironment.kt
- test_runner/src/main/kotlin/ftl/domain/ListAndroidModels.kt
- test_runner/src/main/kotlin/ftl/domain/ListIosModels.kt
- test_runner/src/main/kotlin/ftl/environment/TestEnvironmentInfo.kt
- test_runner/src/main/kotlin/ftl/environment/android/AndroidModelDescription.kt
- test_runner/src/main/kotlin/ftl/environment/android/ListAndroidDevices.kt
- test_runner/src/main/kotlin/ftl/environment/ios/IosModelDescription.kt
- test_runner/src/main/kotlin/ftl/environment/ios/ListIOsDevices.kt
- test_runner/src/main/kotlin/ftl/environment/ios/ListIOsSofwareVersions.kt
- test_runner/src/main/kotlin/ftl/ios/IosCatalog.kt
- test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
- test_runner/src/test/kotlin/ftl/args/SupportedDeviceConfigTest.kt
- test_runner/src/test/kotlin/ftl/args/ValidateIosArgsTest.kt
- test_runner/src/test/kotlin/ftl/environment/android/AndroidModelDescriptionTest.kt
- test_runner/src/test/kotlin/ftl/environment/ios/IosModelDescriptionTest.kt
- test_runner/src/test/kotlin/ftl/ios/IosCatalogTest.kt
Fixes #1745
- Code is refactored according to the description in #1745
- commands working property
- `android models describe`
- `ios models describe`
- `android models list`
- `ios models describe`
- iOS and Android run validation works properly
> refactor: Refactor data scratch-device model

- test_runner/src/main/kotlin/ftl/adapter/GooglePerformanceMetricsFetch.kt
- test_runner/src/main/kotlin/ftl/adapter/google/PerfMetricsAdapter.kt
- test_runner/src/main/kotlin/ftl/api/PerfMetrics.kt
- test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
- test_runner/src/main/kotlin/ftl/reports/api/PerformanceMetrics.kt
- test_runner/src/main/kotlin/ftl/util/StopWatch.kt
- test_runner/src/test/kotlin/ftl/adapter/google/PerfMetricsAdapterTest.kt
- test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt
- test_runner/src/test/kotlin/ftl/reports/api/PerformanceMetricsTest.kt
Fixes #1752
- Code is refactored according to the description in #1752
- Performance metrics are stored and uploaded like before
> refactor: Refactor data scratch-performance metrics

- corellium/shard/README.md
- corellium/shard/build.gradle.kts
- corellium/shard/src/main/kotlin/flank/corellium/shard/Internal.kt
- corellium/shard/src/main/kotlin/flank/corellium/shard/Shard.kt
- corellium/shard/src/test/kotlin/flank/corellium/shard/ShardKtTest.kt
- docs/corellium/sharding-class.puml
- settings.gradle.kts
Fixes #1801 
The implementation of multi-module sharding
[README](https://github.com/Flank/flank/blob/1801_Multi-module_sharding_algorithm/corellium/shard/README.md)
Unit test passes
> feat: Add sharding implementation for corellium

- corellium/api/build.gradle.kts
- corellium/api/src/main/kotlin/flank/corellium/api/AndroidApps.kt
- corellium/api/src/main/kotlin/flank/corellium/api/AndroidInstance.kt
- corellium/api/src/main/kotlin/flank/corellium/api/AndroidTestPlan.kt
- corellium/api/src/main/kotlin/flank/corellium/api/Authorization.kt
- corellium/api/src/main/kotlin/flank/corellium/api/CorelliumApi.kt
- corellium/api/src/main/kotlin/flank/corellium/api/Request.kt
- settings.gradle.kts
Related to #1799 
Declaration of interfaces and structures with java doc:
https://github.com/Flank/flank/tree/1799_Corellium_api_layer/corellium/api/src/main/kotlin/flank/corellium/api
> feat: API layer for corellium MVP

- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/test/kotlin/ftl/args/ValidateDirectoriesToPullAndroidArgsTest.kt
Fixes #1873 
Updated the tests in `ValidateDirectoriesToPullAndroidArgsTest` to include changes in this PR
> fix: Add storage dir support

- .github/workflows/release.yml
This is workaround to prevent failing release when using `ubuntu` machines
> fix: Fix release job

- test_runner/src/main/kotlin/ftl/api/NetworkProfile.kt
- test_runner/src/main/kotlin/ftl/domain/DescribeNetworkProfiles.kt
- test_runner/src/main/kotlin/ftl/environment/NetworkProfileDescription.kt
- test_runner/src/main/kotlin/ftl/presentation/Output.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/networkprofiles/NetworkProfilesDescribeCommand.kt
Fixes #1853 
- Code is refactored according to the description in #1853 
- File reference has been replaced and is acting as expected.
> refactor: Refactor DescribeNetworkProfiles logging

- test_runner/src/main/kotlin/ftl/domain/DescribeAndroidModels.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/models/AndroidModelDescribeCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/models/describe/AndroidModelDescription.kt
- test_runner/src/test/kotlin/ftl/environment/android/AndroidModelDescriptionTest.kt
Fixes #1846
- Code is refactored according to #1846
- Android describe models command works like previously
> refactor: Structural output Android models describe

- test_runner/src/main/kotlin/ftl/domain/ListAndroidLocales.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/locales/AndroidLocalesListCommand.kt
Fixes #1854 
Unit tests pass & refactored inline with #1854
> refactor: list android locales

- test_runner/src/main/kotlin/ftl/domain/DescribeAndroidLocales.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/locales/AndroidLocalesDescribeCommand.kt
Fixes #1845 
Code is refactored according to the description in #1845
Runs as expected,` ./gradlew clean build` runs as expected.
> refactor: Android locales describes

- test_runner/build.gradle.kts
- test_runner/src/main/kotlin/ftl/adapter/GcFetchArtifacts.kt
- test_runner/src/main/kotlin/ftl/adapter/google/FetchArtifacts.kt
- test_runner/src/main/kotlin/ftl/api/Artifacts.kt
- test_runner/src/main/kotlin/ftl/client/google/GcStorage.kt
- test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt
- test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
- test_runner/src/main/kotlin/ftl/run/RefreshLastRun.kt
- test_runner/src/main/kotlin/ftl/run/common/FetchAllArtifacts.kt
- test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt
- test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
- test_runner/src/test/kotlin/ftl/test/util/FlankTestRunner.kt
- test_runner/src/test/kotlin/ftl/test/util/LocalGcs.kt
Fixes #1758 
- Code is refactored according to the description in #1758
- File reference has been replaced and is acting as expected.
> refactor: Fetching artifacts

- test_runner/src/main/kotlin/ftl/adapter/GoogleTestEnvironment.kt
- test_runner/src/main/kotlin/ftl/api/OsVersion.kt
- test_runner/src/main/kotlin/ftl/api/TestEnvironment.kt
- test_runner/src/main/kotlin/ftl/client/google/IosCatalog.kt
- test_runner/src/main/kotlin/ftl/domain/DescribeAndroidTestEnvironment.kt
- test_runner/src/main/kotlin/ftl/domain/DescribeIosTestEnvironment.kt
- test_runner/src/main/kotlin/ftl/environment/TestEnvironmentInfo.kt
- test_runner/src/main/kotlin/ftl/environment/ios/ListIOsSofwareVersions.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/AndroidTestEnvironmentCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/environment/TestEnvironmentInfo.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/IosTestEnvironmentCommand.kt
Fixes #1847 #1851 
2. run `flank android test-environment`
3. run `flank ios test-environment`
3. 🎉
> refactor: Logging refactor - android/ios test environment

- test_runner/src/main/kotlin/ftl/domain/CancelLastRun.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/CancelCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/MatrixCancelStatusMapper.kt
- test_runner/src/main/kotlin/ftl/run/CancelLastRun.kt
- test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
Fixes #1844
- Code is refactored according to description in #1844
- `flank firebase cancel` command works like previously
> refactor: Structural output cancel last run

- test_runner/src/main/kotlin/ftl/adapter/GoogleDeviceModel.kt
- test_runner/src/main/kotlin/ftl/adapter/GoogleTestEnvironment.kt
- test_runner/src/main/kotlin/ftl/api/DeviceModels.kt
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/domain/DescribeAndroidModels.kt
- test_runner/src/main/kotlin/ftl/domain/ListAndroidModels.kt
- test_runner/src/main/kotlin/ftl/environment/android/ListAndroidDevices.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/models/AndroidModelsListCommand.kt
- test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
Fixes #1856 
* Implementation should follow the specification described in #1728 
* All tests should pass
> refactor: Structural output for list android models

- corellium/junit/build.gradle.kts
- corellium/junit/src/main/kotlin/flank/junit/JUnit.kt
- corellium/junit/src/main/kotlin/flank/junit/mapper/Structural.kt
- corellium/junit/src/main/kotlin/flank/junit/mapper/Xml.kt
- corellium/junit/src/test/kotlin/flank/junit/FailOnInvalidJUnitReport.kt
- corellium/junit/src/test/kotlin/flank/junit/GenerateJUnitReport.kt
- corellium/junit/src/test/kotlin/flank/junit/ParseAndFormatJUnitReport.kt
- corellium/junit/src/test/kotlin/flank/junit/ParseEmptyJUnitReport.kt
- corellium/junit/src/test/kotlin/flank/junit/Util.kt
- corellium/junit/src/test/resources/JUnit.xsd
- corellium/junit/src/test/resources/JUnitReport.xml
- corellium/junit/src/test/resources/JUnitReport_empty_1.xml
- corellium/junit/src/test/resources/JUnitReport_empty_2.xml
- corellium/junit/src/test/resources/JUnitReport_empty_3.xml
- corellium/junit/src/test/resources/JUnitReport_invalid.xml
- settings.gradle.kts
Fixes #1827 
* The JUnit structures are bases on those taken from the `test_runner` but applying some fixes like reducing the number of nullable fields.
* The `JUnit.xsd` is added just for convenience as a referential scheme.
Unit tests pass
> feat: Add junit module

- test_runner/src/main/kotlin/ftl/client/google/ProvidedSoftwareCatalog.kt
- test_runner/src/main/kotlin/ftl/domain/ListProvidedSoftware.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/orientations/AndroidOrientationsListCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/environment/TestEnvironmentInfo.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/providedsoftware/ListProvidedSoftware.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/providedsoftware/ProvidedSoftwareListCommand.kt
- test_runner/src/test/kotlin/ftl/environment/ListProvidedSoftwareTest.kt
Fixes #1865
Code is refactored according to #1865 
`firebase test provided-software list` works like previously
> refactor: Structural output list provided software

- test_runner/src/main/kotlin/ftl/domain/ListNetworkProfiles.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/locales/AndroidLocalesListCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/orientations/AndroidOrientationsListCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/environment/TestEnvironmentInfo.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/configuration/IosLocalesDescribeCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/configuration/IosLocalesListCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/orientations/IosOrientationsListCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/networkprofiles/ListNetworkConfiguration.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/networkprofiles/NetworkProfilesListCommand.kt
- test_runner/src/main/kotlin/ftl/util/CastingUtils.kt
- test_runner/src/test/kotlin/ftl/cli/firebase/test/networkprofiles/NetworkProfilesListCommandTest.kt
Fixes #1864
- code is refactored as described in #1864
- `flank firebase test network-profiles list` works like before
> refactor: Structural output list network profiles

- test_runner/src/main/kotlin/ftl/adapter/GoogleTestEnvironment.kt
- test_runner/src/main/kotlin/ftl/adapter/IosVersionsFetch.kt
- test_runner/src/main/kotlin/ftl/api/OsVersion.kt
- test_runner/src/main/kotlin/ftl/domain/DescribeIosVersions.kt
- test_runner/src/main/kotlin/ftl/domain/ListIosVersions.kt
- test_runner/src/main/kotlin/ftl/environment/ios/ListIOsSofwareVersions.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/versions/IosVersionsListCommand.kt
Fixes #1862 
1. Run flank ```flank  ios versions list```
2. See output
```
┌───────────────┬───────────────┬───────────────┬─────────┬──────────────────────────────┐
│ OS_VERSION_ID │ MAJOR_VERSION │ MINOR_VERSION │  TAGS   │ SUPPORTED_XCODE_VERSION_IDS  │
├───────────────┼───────────────┼───────────────┼─────────┼──────────────────────────────┤
│     10.3      │      10       │       3       │         │ 10.3, 11.6, 11.7, 12.1, 12.3 │
│     11.2      │      11       │       2       │         │ 10.3, 11.6, 11.7, 12.1, 12.3 │
│     11.4      │      11       │       4       │         │ 10.3, 11.6, 11.7, 12.1, 12.3 │
│     12.0      │      12       │ UNKNOWN       │         │ 10.3, 11.6, 11.7, 12.1, 12.3 │
│     12.1      │      12       │       1       │ …
```
> refactor: Structural output list ios versions

- corellium/shard/dump/README.md
- corellium/shard/dump/build.gradle.kts
- corellium/shard/dump/src/main/kotlin/flank/corellium/shard/Dump.kt
- corellium/shard/dump/src/main/kotlin/flank/corellium/shard/Internal.kt
- corellium/shard/dump/src/test/kotlin/flank/corellium/shard/DumpTest.kt
- settings.gradle.kts
Fixes #1818
~~This PR is blocked by #1920, and will be changed to ready for review after the #1920 merge.~~
Unit tests pass.
> feat: Dump shards

- test_runner/src/main/kotlin/ftl/client/junit/PrepareForJUnitResult.kt
- test_runner/src/main/kotlin/ftl/domain/junit/StackTraceRemover.kt
- test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
- test_runner/src/test/kotlin/ftl/domain/junit/StackTraceRemoverTest.kt
- test_runner/src/test/kotlin/ftl/reports/api/PrepareForJUnitResultKtTest.kt
Simple JunitReport does not contain stack traces for flaky tests
> refactor: Add removing stack traces for simple report

- corellium/shard/README.md
- corellium/shard/obfuscate/README.md
- corellium/shard/obfuscate/build.gradle.kts
- corellium/shard/obfuscate/src/main/kotlin/flank/corellium/shard/Internal.kt
- corellium/shard/obfuscate/src/main/kotlin/flank/corellium/shard/Obfuscate.kt
- corellium/shard/obfuscate/src/test/kotlin/flank/corellium/shard/ObfuscateTest.kt
- corellium/shard/src/main/kotlin/flank/corellium/shard/Shard.kt
- settings.gradle.kts
Related to #1818
Unit tests pass.
> feat: Obfuscate shards

- corellium/domain/build.gradle.kts
- corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestAndroidCorellium.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/util/Transform.kt
- settings.gradle.kts
Related to #1802 
The public API of the domain layer is required for CLI integration.
The rest of the domain layer implementation will be added in another PR.
> feat: Public API of corellium domain layer

- corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
- corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
- corellium/domain/build.gradle.kts
- corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
- corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumExample.kt
- corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestMockApiAndroid.kt
- corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestParsingAndroid.kt
- corellium/domain/src/test/kotlin/flank/corellium/domain/Utils.kt
Related to #1802 
This is a bunch of several minor changes cherry-picked from #1897 for splitting code review into smaller parts.
* Fix some names
* Add tests for RunTestAndroidCorellium
Unit tests pass.
> fix: Several minor corellium changes - part 3.

- .github/workflows/full_suite_integration_tests.yml
- .github/workflows/release.yml
- .github/workflows/ubuntu-workflow.yml
- .github/workflows/wsl-workflow.yml
- docs/windows_wsl_guide.md
Fixes #1928 
Revert to latest, ubuntu-latest and include fixes.
> ci: Ubuntu updates

- corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
- test_runner/build.gradle.kts
- test_runner/src/main/kotlin/ftl/presentation/cli/CorelliumCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/MainCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/corellium/TestCommand.kt
- test_runner/src/main/kotlin/ftl/presentation/cli/corellium/test/AndroidCommand.kt
- test_runner/src/test/kotlin/ftl/MainTest.kt
Fixes #1944 
* Unit tests pass
* `$ flank corellium test android run` is executing `flank.corellium.cli.RunTestCorelliumAndroidCommand`
> feat: Integrate flank.jar with corellium CLI

- test_runner/src/main/kotlin/ftl/api/TestAndroidMatrix.kt
- test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/AppTestPair.kt
- test_runner/src/main/kotlin/ftl/client/google/run/android/GcAndroidTestMatrix.kt
- test_runner/src/main/kotlin/ftl/config/android/AndroidFlankConfig.kt
- test_runner/src/main/kotlin/ftl/mock/MockServer.kt
- test_runner/src/main/kotlin/ftl/run/model/AndroidTestContext.kt
- test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestMatrixType.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-multiple-mixed.yml
- test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
Fixes #
**This PR is a rework of #1898. A PR was merged recently which refactors some of the code I was using and introduced merge conflicts in #1898. This PR implements the same functionality with the refactored code.**
This PR adds the ability to specify `max-test-shards` and `client-details` for tests under additional-app-test-apks like so:
```
additional-app-test-apks:
- test: lib1-test.apk
max-test-shards: 3
- test: lib2-test.apk
max-test-shards: 1
client-details:
modulename: lib2
key2: val2
```
These configurations really improves support for multi-module projects, usually the thing I want to change the most is number of shards used to test a module. It also lets me differentiate between modules by setting key/values under `client-details`.
Added …
> feat: added max-test-shards and client-details to additional-app-test-apks

- corellium/domain/README.md
- corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/Authorize.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/CleanUpInstances.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/CreateOutputDir.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/DumpShards.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTests.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/Finish.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/GenerateReport.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/InstallApks.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/InvokeDevices.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseApkInfo.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseTestCases.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/PrepareShards.kt
- docs/corellium/steps-dependencies-class.puml
Fixes #1802 
This PR adds a domain logic for `RunTestCorelliumAndroid`.
List of features:
* Parsing test cases & other info from apk.
* Creating and/or invoking android instances on demand.
* Advanced sharding.
* Many apps and tests in one shard.
* Tests from one app in many shards.
* Dumping shards to file.
* Executing tests
* Generating JUnitReport.xml
What is currently not supported:
* Smart sharding (using test case durations from previous runs).
* Flaky tests.
* Cleaning up devices after tests.
* Some other not listed stuff.
Module [README.md](https://github.com/Flank/flank/blob/corellium-domain/corellium/domain/README.md)
Unit tests pass.
`$ flank corellium test android run -c="flank-corellium-android.yml"` is invoking a fully integrated feature.
> feat: Domain layer implementation for android test run Corellium MVP

- corellium/adapter/src/main/kotlin/flank/corellium/Api.kt
- corellium/api/src/main/kotlin/flank/corellium/api/CorelliumApi.kt
- corellium/apk/build.gradle.kts
- corellium/apk/src/main/kotlin/flank/apk/Apk.kt
- corellium/apk/src/main/kotlin/flank/apk/internal/Parse.kt
- corellium/apk/src/test/kotlin/flank/apk/ParseApkTest.kt
- corellium/cli/build.gradle.kts
- corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
- corellium/domain/build.gradle.kts
- corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseApkInfo.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseTestCases.kt
- corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumExample.kt
- corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestMockApiAndroid.kt
- corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestParsingAndroid.kt
- settings.gradle.kts
This PR is fixing the wrong design which mixes parsers with API adapters by moving parsers to the dedicated module.
> refactor: Move apk parsers to dedicated module

- docs/architecture.md
- docs/hld/architecture-template.puml
- mkdocs.yml
> docs: Add architecture abstraction

- test_runner/src/main/kotlin/ftl/client/google/Credentials.kt
Fixes #1792 #1831 
This pr contains changes requested in #1831 and may fix #1792. 
1. Flank firstly should try to use credentials from env variable ```GOOGLE_APPLICATION_CREDENTIALS``` [here](https://github.com/Flank/flank/blob/c643f859e053dfdb890170a087d783c23eacbb11/test_runner/src/main/kotlin/ftl/client/google/Credentials.kt#L22)
1. If this method fails Flank should try to load credentials from ```./user_home/.flank``` directory [here](https://github.com/Flank/flank/blob/c643f859e053dfdb890170a087d783c23eacbb11/test_runner/src/main/kotlin/ftl/client/google/Credentials.kt#L26) or if it's windows from ```%USER_HOME%/.config/gcloud/application_default_credentials.json``` [here](https://github.com/Flank/flank/blob/c643f859e053dfdb890170a087d783c23eacbb11/tes …
> fix: Service account as default 

- buildSrc/src/main/kotlin/Versions.kt
- common/src/main/kotlin/flank/common/Os.kt
- corellium/adapter/build.gradle.kts
- corellium/adapter/src/main/kotlin/flank/corellium/adapter/ExecuteAndroidTestPlan.kt
- corellium/adapter/src/main/kotlin/flank/corellium/adapter/InvokeAndroidDevices.kt
- corellium/client/src/main/kotlin/flank/corellium/client/core/Api.kt
- corellium/shard/calculate/src/test/kotlin/flank/corellium/shard/CalculateShardsTest.kt
- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/ops/common/GenerateChangeLog.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/ITResult.kt
- flank-scripts/src/test/kotlin/flank/scripts/utils/VersionParseTest.kt
- integration_tests/src/test/kotlin/integration/CustomShardingIT.kt
- integration_tests/src/test/kotlin/integration/MultipleApksIT.kt
- integration_tests/src/test/kotlin/integration/MultipleDevicesIT.kt
- integration_tests/src/test/kotlin/utils/OutputHelper.kt
- test_runner/build.gradle.kts
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
- test_runner/src/main/kotlin/ftl/args/IosArgs.kt
- test_runner/src/main/kotlin/ftl/client/junit/CreateTestSuiteOverviewData.kt
- test_runner/src/main/kotlin/ftl/reports/output/OutputReportType.kt
- test_runner/src/main/kotlin/ftl/run/status/OutputStyle.kt
- test_runner/src/main/kotlin/ftl/shard/ShardCount.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
- test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
Fixes #1962
Code compiles without any problem, there should not be any errors and warnings
> build: update kotlin to 1.5.10 and remove warnings

- test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
- test_runner/src/main/kotlin/ftl/client/google/IosCatalog.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/args/ValidateIosArgsTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/android_catalog.json
- test_runner/src/test/kotlin/ftl/fixtures/ios_catalog.json
- test_runner/src/test/kotlin/ftl/reports/outcome/BillableMinutesTest.kt
Fixes #1892 
2. run `flank firebase test ios models list` and compare with `gcloud firebase test ios models list` -- there should be no different
3. run `flank firebase test android models list` and compare with `gcloud firebase test android models list` -- there should be no different
> fix: Filter devices without supported versions

- integration_tests/src/test/kotlin/utils/OutputReportParser.kt
- test_runner/src/main/kotlin/ftl/adapter/google/GoogleTestMatrixAdapter.kt
- test_runner/src/main/kotlin/ftl/api/TestMatrix.kt
- test_runner/src/main/kotlin/ftl/domain/testmatrix/UpdateTestMatrix.kt
- test_runner/src/main/kotlin/ftl/json/SavedMatrixTableUtil.kt
- test_runner/src/main/kotlin/ftl/reports/output/OutputReportLoggers.kt
- test_runner/src/test/kotlin/ftl/reports/output/OutputReportLoggersTest.kt
Fixes #1803 
1. Run `./gradlew flankFullRun`
2. Run any flank test run (android/ios)
3. Result table should have the `TEST FILE` column with the correct debug/xctest/json file name.
> feat: Add test file column to result table

- corellium/client/src/main/kotlin/flank/corellium/client/agent/Connect.kt
- corellium/client/src/main/kotlin/flank/corellium/client/console/Connect.kt
- test_configs/.gitignore
- test_configs/flank-corellium.yml
Fixes #1979 
Add the configuration file `test_configs/corellium_auth.yml` and call:
```shell
.  .env
flankScripts assemble flank
flank corellium test android run -c="test_configs/flank-corellium.yml"
```
The execution should pass without exceptions.
> fix: CIOEngineContainer not found

- corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
- docs/flank_corellium.md
- mkdocs.yml
Fixes #1976 
[User guide](https://github.com/Flank/flank/blob/1976_Add_user_guide_for_Corellium_MVP/docs/flank_corellium.md)
> docs: Add user guide for Corellium MVP

- corellium/README.md
- corellium/client/README.md
> fix: puml diagram links

- corellium/adapter/src/main/kotlin/flank/corellium/adapter/InvokeAndroidDevices.kt
- corellium/api/src/main/kotlin/flank/corellium/api/AndroidInstance.kt
- corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
- corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
- corellium/client/src/main/kotlin/flank/corellium/client/data/DTOs.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/InvokeDevices.kt
Fixes #1983 
1. Remove previously created virtual devices in Corellium project.
2. Run `flank corellium test android run -c="./flank_corellium.yml"`
3. Check the newly created devices have enabled GPU acceleration
* Debug `RunTestAndroidCorelliumExample` and check `flank.corellium.adapter.getCreatedInstances` are returning instances with properly configured `BootOptions`|
* Or find another way for checking if GPU acceleration is enabled.
> feat: Enable GPU acceleration for new instances

- corellium/instrument/command/src/main/kotlin/flank/instrument/command/FormatAmInstrumentCommand.kt
- corellium/instrument/command/src/test/kotlin/flank/instrument/command/FormatAmInstrumentCommandKtTest.kt
Espresso tests require animations to be disabled. On firebase test lab, animations are disabled by default.
This PR is adding `--no-window-animation` to `am instrument` command
1. Run `flank corellium test android run -c="./test_configs/flank-corellium.yml"`
2. Observe log lines like: `Sending command: am instrument -r -w --no-window-animation -e class com.example...`
> feat:  Disable window animation in tests by default

- .github/workflows/release_notes_generation.yml
Fixes: #1995
Generating release is failing because of the ASCII generator task, which is blocking the crucial release.
This PR disables ASCII doc generation as a temporary fix.
references:
* https://github.com/Flank/flank/actions/runs/895343619
* https://scans.gradle.com/s/upwhryz6ss3gy/failure#1
> fix: Disable ASCII doc generation (release blocker)

- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
Flank was showing:
> Warning: Failed to make bucket for ...
> Cause: Sorry, that name is not available. Please try a different one.
It didn't find the bucket but it was there, the reason is the list of buckets was never set.
It's been broken since: https://github.com/Flank/flank/pull/531/files#diff-81920894b2478868a06b5f2210f003afaf3ca682d7cb61afe1c8dec2cecdb191R127
Tested manually but looking if on how to write an automated test
I have read the CLA Document and I hereby sign the CLA
> Fix: bucket not found but can't be created

- test_runner/src/main/kotlin/ftl/http/ExecuteWithRetry.kt
- test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt
- test_runner/src/main/kotlin/ftl/util/CrashReporter.kt
Fixes #1958
When a Google infrastructure issue occurs(FlankGoogleApiError, InfrastructureError) it is logged with log level DEBUG.
You could throw this exception on your own `InfrastructureError("test").report(SentryLevel.DEBUG)`. This feature will be used for creating Sentry notification about critical errors to the newly created channel `#sentry-errors`
> feat: Set Google api issues level as DEBUG

- docs/index.md
- integration_tests/src/test/kotlin/integration/MultipleApksIT.kt
- integration_tests/src/test/resources/cases/flank_android_multiple_apk.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/adapter/GoogleTestMatrixAndroid.kt
- test_runner/src/main/kotlin/ftl/api/TestAndroidMatrix.kt
- test_runner/src/main/kotlin/ftl/args/ArgsToString.kt
- test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/yml/AppTestPair.kt
- test_runner/src/main/kotlin/ftl/client/google/run/android/GcAndroidTestMatrix.kt
- test_runner/src/main/kotlin/ftl/config/android/AndroidFlankConfig.kt
- test_runner/src/main/kotlin/ftl/run/model/AndroidTestContext.kt
- test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestMatrixType.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/UploadApks.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-multiple-mixed.yml
- test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt
- test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
- test_runner/src/test/kotlin/ftl/run/platform/RunAndroidTestsKtTest.kt
- test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
- test_runner/src/test/kotlin/ftl/run/platform/android/ResolveApksKtTest.kt
- test_runner/src/test/kotlin/ftl/test/util/TestHelper.kt
Fixes #1815
This PR introduces a couple of changes:
1. from now on each android test context will have its own copy of `AndroidConfig`
2. each copy will be overwritten with values defined by the user
3. each copy will be validated
With the above enhancements, we can extend `additional-test-app-pairs` easier in the future. For now, only community-requested options are implemented.
1. Run `./gradlew flankFullRun`
2. Example config:
```yaml
gcloud:
app: ...
test: ...
flank:
max-test-shards: 2
additional-app-test-apks:
- test: ...
max-test-shards: 5
- test: ...
device:
- model: Nexus6P
version: 27
```
3. Yous should receive 3 matrices with different set up:
1. 2 shards, NexusLowRes device (default one)
2. 5 shards, NexusLowRes device
3. 2 shards, Nexus6P …
> feat: Additional config options for test pairs

- test_runner/build.gradle.kts
Fixes #1997 
1. Run `./gradlew test_runner:generateCliAsciiDoc`
2. Documentation should be generated without any issues
> fix: Fix generating documentation

- test_runner/src/main/kotlin/ftl/adapter/TestMatrixRefresh.kt
- test_runner/src/main/kotlin/ftl/api/TestMatrix.kt
- test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
Fixes #2021 
It is impossible to test whole flow in sensible and reliable way. It would require mocking lots of methods and since the problem is related with multithreading I think it's not the best idea. What's more, test might be unreliable due to differences in CPU configurations on different machines.
@asadsalman was asked to verify fix, as a proof (thanks!)
> fix: Fix flank freezes when large number of matrices is launched

- corellium/client/src/main/kotlin/flank/corellium/client/agent/Agent.kt
- corellium/client/src/main/kotlin/flank/corellium/client/agent/Connect.kt
- corellium/client/src/main/kotlin/flank/corellium/client/agent/UploadFile.kt
- corellium/client/src/main/kotlin/flank/corellium/client/agent/Util.kt
- corellium/client/src/main/kotlin/flank/corellium/client/console/Api.kt
- corellium/client/src/main/kotlin/flank/corellium/client/util/Retry.kt
- corellium/sandbox/src/main/kotlin/flank/corellium/sandbox/android/AndroidExampleNoVPN.kt
Related to #1999 
* Remove unneeded print lines from `:corellium:client`
* Optimize internal implementation of `:corellium:client`
This PR is implementing fixes required by #2032.
Merging this will simplify #2032.
> feat: Remove print lines from Corellium client

- build.gradle.kts
- docs/index.md
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/config/FlankDefaults.kt
- test_runner/src/main/kotlin/ftl/config/android/AndroidFlankConfig.kt
- test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Part 1 for Fixes of #2023 
Its tested. At this point the new param does not influence flank but this PR is to discuss its addition is in the right place and to move forward. 
Part 2 will be actual implementation.
Issue wont be connected so its not moved to done when closed.
Again take note that this is a set of new options to give users of flank better control over the use of Parameterized tests.
Apart of the #1720
> feat: Added new Parameterized Test Option

- settings.gradle.kts
- tool/log/README.md
- tool/log/build.gradle.kts
- tool/log/format/README.md
- tool/log/format/build.gradle.kts
- tool/log/format/src/main/kotlin/flank/log/Builder.kt
- tool/log/format/src/main/kotlin/flank/log/Formatter.kt
- tool/log/format/src/test/kotlin/flank/log/LoggingTest.kt
- tool/log/src/main/kotlin/flank/log/Event.kt
- tool/log/src/main/kotlin/flank/log/Logger.kt
Related to #1999 
This PR is adding simple tools for structural logging and formatting, required by PR #2032. 
Merging this will simplify #2032.
Unit test passes.
> feat: Add tools for structural logging

- test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
Fixes #2018 
`commonArgs` -> `data` field is redundant. It is represented by yml file read as a raw string. Flank copies `yml` file and all values (from config) are present in report json in dedicated fields. Therefor I think we can make it transient (not serializable)
1. run any flank test
2. open `outputReport.json`
3. There should be no `data` field in `commonArgs`
> refactor: Data field should not be serialized

- .github/workflows/create_new_release.yml
- .github/workflows/pr_checks.yml
- .github/workflows/release.yml
- .github/workflows/release_notes_generation.yml
Fixes #2006 
What was done?
* 3 new secrets for failure slack notification
* notifications added in crucial release workflows
* PR checks should not be performed for release notes
This is impossible to verify PR prior to its merge.
> feat: Implement slack notifications for failed release

- corellium/client/src/main/kotlin/flank/corellium/client/util/Retry.kt
- flank-scripts/build.gradle.kts
- flank-scripts/src/main/kotlin/flank/scripts/cli/assemble/FlankCommand.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/assemble/BuildFlank.kt
- flank-scripts/src/main/kotlin/flank/scripts/utils/GradleCommand.kt
The PR is fixing incorrect behaviour of the retry method that was always looping 5 times.
Additionally adds `--dirty` option to `flankScripts assemble flank` this will speed up builds for local testing purpose.
> fix: Corellium client request retry 

- corellium/adapter/build.gradle.kts
- corellium/adapter/src/main/kotlin/flank/corellium/Api.kt
- corellium/adapter/src/main/kotlin/flank/corellium/adapter/ClientReference.kt
- corellium/adapter/src/main/kotlin/flank/corellium/adapter/ExecuteAndroidTestPlan.kt
- corellium/adapter/src/test/kotlin/flank/corellium/adapter/ExecuteAndroidTestPlanKtTest.kt
- corellium/api/src/main/kotlin/flank/corellium/api/CorelliumApi.kt
- corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
- corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTests.kt
- corellium/domain/src/test/kotlin/flank/corellium/domain/AdbLog.kt
- corellium/domain/src/test/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTestsKtTest.kt
- docs/flank_corellium.md
Fixes #2037 
Improvements:
* Save `am instrument` logs to file in `adb_log` output directory.
* Catch `am instrument` output parsing error and mark affected lines in the error message.
* Close console connection without waiting for idle, if receive expected results or error.
* Unit test passes. 
* Running `flank corellium test android run` creates `adb_log` inside output directory with dumped `am instrument` console outputs.
* If parsing tests results from `am instrument` log fails the error message in the console will communicate file with lines where the error occurs.
> feat: Save `am instrument` logs to file & handle parsing error.

- test_runner/src/main/kotlin/ftl/analytics/PrepareConfiguration.kt
- test_runner/src/main/kotlin/ftl/analytics/StatisticDataFilters.kt
- test_runner/src/main/kotlin/ftl/analytics/UsageStatistics.kt
- test_runner/src/test/kotlin/ftl/analytics/UsageStatisticsTest.kt
Fixes #1792 
In case when we don't have a default project id, Flank should not fail when trying to compare default android configuration and user-defined configuration.
> fix: Removed filtering default args when sending statistics to mixpanel

- corellium/api/src/main/kotlin/flank/corellium/api/Authorization.kt
- corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
This PR is fixing a bad design where the CLI layer is defining default arguments. 
The change is the CLI now is depending on defaults from the domain module.
> refactor: Make the domain a source of defaults

- corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
- corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
- corellium/domain/build.gradle.kts
- corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTests.kt
- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseTestCases.kt
- corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestMockApiAndroid.kt
- docs/flank_corellium.md
- test_configs/flank-corellium.yml
- tool/apk/src/main/kotlin/flank/apk/Apk.kt
- tool/apk/src/main/kotlin/flank/apk/internal/Info.kt
- tool/apk/src/main/kotlin/flank/apk/internal/PackageName.kt
- tool/apk/src/main/kotlin/flank/apk/internal/TestCases.kt
- tool/apk/src/test/kotlin/flank/apk/ParseApkTest.kt
Fixes #2051
Requires #2055
Enchanted by #2062
* Add test targets argument for filtering test cases.
* Add filtering option to Apk.ParseTestCases.
* Log AndroidTestPlan.Config on ExecuteTests start.
* Refactor `:tool:apk` module
build flank
```shell
. .env
flankScripts assemble flank -d
```
and run 
```shell
flank corellium test android run -c="./test_configs/flank-corellium.yml"
```
using configuration
```yml
auth: "test_configs/corellium_auth.yml"
apks:
- path: "test_artifacts/master/apk/app-debug.apk"
tests:
- path: "test_artifacts/master/apk/app-multiple-flaky-debug-androidTest.apk"
test-targets:
- "package com.example.test_app.parametrized"
- "notClass com.example.test_app.parametrized.EspressoParametrizedClassTestParameterized"
- "package …
```
> feat: Test targets option for Corellium

- corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/LoadPreviousDurations.kt
- tool/junit/src/main/kotlin/flank/junit/JUnit.kt
- tool/junit/src/main/kotlin/flank/junit/internal/CalculateMedianDurations.kt
- tool/junit/src/main/kotlin/flank/junit/internal/MergeDurations.kt
- tool/junit/src/main/kotlin/flank/junit/mapper/Structural.kt
- tool/junit/src/test/kotlin/flank/junit/internal/MergeDurationsKtTest.kt
- tool/junit/src/test/kotlin/flank/junit/mapper/StructuralKtTest.kt
Fixes #2052 
* Adds to module `:tool:junit` function for merging test methods into test-class with accumulated duration.
* Merges test methods for given class names while loading previous durations.
Build flank:
```shell
. .env
flankScripts assemble flank -d
```
Run the following command twice:
```shell
flank corellium test android run -c="./test_configs/flank-corellium.yml"
```
The second run should calculate durations for parameterized classes.
Check generated `android-shards.json` each parameterized class should have a duration different than the default (120).
> feat: Merge test method duration for parameterized classes

- corellium/cli/build.gradle.kts
- corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
- settings.gradle.kts
- tool/config/README.md
- tool/config/build.gradle.kts
- tool/config/src/main/kotlin/flank/config/Config.kt
Just adds module `:tool:config` and moves `Config.kt` for making CLI not defining any tool by itself.
> refactor: Move Config.kt into :tool:config module.

- test_runner/src/main/kotlin/ftl/reports/CostReport.kt
Fixes #
In mixpanel ```devices_cost. total_cost ``` event should be the sum of virtual cost and physical cost instead of the sum of physical and virtual minutes
> fix: Fix calculating total test cost in Mixpanel

- docs/index.md
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Fixes #2024 
Parameterized tests are sharded into separate shards and run as expected.
A true smart shard that can take into account the amount of shards is most likely a fruitless pursuit at this point.
> feat: Parameterized Tests - multiple 

- corellium/domain/build.gradle.kts
- corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
- settings.gradle.kts
- tool/execution/linear/build.gradle.kts
- tool/execution/linear/src/main/kotlin/flank/exection/linear/Transform.kt
Just adds module `:tool:execution:linear` and moves `Transfrom.kt` for making domain not defining any tool by itself.
> refactor: Move legacy execution tool to standalone module.

- tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Create.kt
- tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Parallel.kt
- tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Select.kt
- tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/ContextProvider.kt
- tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Execution.kt
- tool/log/src/main/kotlin/flank/log/Event.kt
Related to #2083
* Expose function for wrapping state into context in ContextProvider.
* Add generic function for creating state property which static type checking.
* Improve DeadlockError message.
* Remove redundant data value from DependenciesError messages.
> feat: Improvements for :tool:execution:parallel

- tool/junit/src/main/kotlin/flank/junit/internal/MergeDurations.kt
- tool/junit/src/main/kotlin/flank/junit/internal/ParseJUnitTestResults.kt
- tool/junit/src/test/kotlin/flank/junit/internal/MergeDurationsKtTest.kt
Related to #2083 
Fixes following behaviors:
* Loads only the latest JUnit results used for calculating durations of previous test cases instead of random.
* Avoids merging parameterized tests cases durations from different shards.
> fix: Incorrect calculations in JUnit tool

- test_runner/src/main/kotlin/ftl/domain/RunTestAndroid.kt
- test_runner/src/main/kotlin/ftl/domain/RunTestIos.kt
- test_runner/src/main/kotlin/ftl/util/CrashReporter.kt
Fixes #2071
There's currently no way to identify which companies need help when flank crashes. this ticket will solve that.
Each Sentry reported crash will contain information about the project id
> feat: Added project ID to sentry

- test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
- test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
- test_runner/src/test/kotlin/ftl/run/platform/android/ResolveApksKtTest.kt
Fixes #2111 
2. create config with
```
additional-app-test-apks:
- test: [...].apk
environment-variables:
someVariable: true
```
3. Your app from `additional` should see overridden variables
> fix: Envs from additional apks not override default values

- test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
- test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
- test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
- test_runner/src/main/kotlin/ftl/util/Utils.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/fixtures/flank.local.yml
Fixes #1882
2. export env variable with test targets, i.e. 
```
export TEST_TARGETS="class your.test.Clazz, notAnnotation your.any.Annotation"
```
3. update your config with env:
```
test-targets:
- $TEST_TARGETS
```
4. start flank test run and see test targets being applied
> feat: Implement env parsing

- flank_wrapper/.gitignore
- flank_wrapper/build.gradle.kts
- tool/analytics/mixpanel/build.gradle.kts
- tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/internal/Send.kt
- tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/internal/Utils.kt
- tool/analytics/mixpanel/src/test/kotlin/flank/tool/analytics/mixpanel/internal/UtilsTest.kt
Fixes #2141 
When mixpanel send failed then you will not see any crash and also it will try to retry the request once
> fix: Add retry and silent crash to mixpanel send method

- test_runner/src/main/kotlin/ftl/api/JUnitTestResult.kt
- test_runner/src/test/kotlin/ftl/domain/junit/StackTraceRemoverTest.kt
Fixes #2145
2. build finish normally
3. start flank run with flaky tests
4. observe the `flaky` flag being added to the flaky cases (previously missing)
> fix: Fix flaky flag

- test_runner/src/main/kotlin/ftl/client/junit/JUnitXmlParser.kt
Fixes #2144
iOS XML report is changed:
- Test suite is now empty
- Previous testsuite name is added as a prefix to the classname
1. Run iOS tests without option `async: true`
2. Check generated XML report
Before:
```xml
<?xml version='1.0' encoding='UTF-8' ?>
<testsuites>
<testsuite name="iphone8-11.4-en_US-portrait#EarlGreyExampleSwiftTests" tests="1" failures="0" errors="0" skipped="0" time="1.969" hostname="localhost">
<testcase name="testLayout()" classname="EarlGreyExampleSwiftTests" time="1.968">
<webLink>https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.a3b607c9bb6d0088/matrices/7816289963561003834/executions/bs.4bace0b897feb88b</webLink>
</testcase>
</testsuite>
</testsuites>
```
After
```xml
<?xml version='1.0' …
```
> feat: Adapt new iOS xml structure

- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/Versions.kt
- docs/index.md
- test_runner/build.gradle.kts
- test_runner/src/main/kotlin/ftl/client/google/Credentials.kt
Fixes #2175. The addition of the Jboss logging dependency is required to avoid a missing class exception when the HTTP transport is created; it bridges the logback instance to the logging in use inside of the network-related code.
This implementation is based off of the model code in https://github.com/googleapis/google-auth-library-java#configuring-a-proxy.
Following the steps described in #2175, I have validated that flank behaves the same when mitmproxy requires credentials as when it does not.
> feat: Support HTTP proxies with credentials.

- build.gradle.kts
- test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
- test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
- test_runner/src/main/kotlin/ftl/client/google/IosCatalog.kt
- test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
- test_runner/src/test/kotlin/ftl/reports/outcome/BillableMinutesTest.kt
Fixes #2179
Ran reduced test case via `Debug.kt` Verified ` PHYSICAL used as fallback` message does not appear. Checked that the cost calculation is correct.
```
gcloud:
test: "./test_runner/src/test/kotlin/ftl/fixtures/tmp/ios/EarlGreyExample/EarlGreyExample.zip"
xctestrun-file: "./test_runner/src/test/kotlin/ftl/fixtures/tmp/ios/EarlGreyExample/EarlGreyExampleSwiftTests.xctestrun"
device:
- model: "iphone11pro"
version: "14.7"
locale: "en"
orientation: "portrait"
```
```
CostReport
Physical devices
$0.08 for 1m
```
> fix: Detect iOS devices as physical

- test_projects/android/app_many_tests/build.gradle
- test_projects/android/app_many_tests/src/main/java/com/example/app/many/tests/MainActivity.kt
- test_projects/android/app_many_tests/src/main/res/layout/activity_main.xml
FTL is deprecating support for the Android Test Orchestrator that is
part of the legacy/deprecated Android Test Support libraries.
This CL updates the app_many_tests test app to the new AndroidX
libraries, as this app is used in integration tests that enable Test
Orchestrator.
Note, users can still use Android Support and Android Test Support
libraries. They just cannot use the legacy Test Orchestrator.
Fixes #
.
> test: Update app_many_tests to AndroidX libraries

- test_runner/src/main/kotlin/ftl/run/model/AndroidTestContext.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestMatrixType.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
- test_runner/src/main/kotlin/ftl/run/platform/android/UploadApks.kt
- test_runner/src/test/kotlin/ftl/run/platform/android/ResolveApksKtTest.kt
Fixes #2206
Passes all tests and also tested on the production Dropbox app with our robo-directives
.
> fix: Add support for robo-directives

- buildSrc/src/main/kotlin/Versions.kt
Unit tests passed. I tested the fix on my app and it worked.
> fix: Fix BufferUnderflowException when parsing dex file with Espresso 3.4.0 Fixes #2203

- docs/index.md
Fix some broken links in the Flank docs that came about as a result of https://github.com/Flank/flank/pull/1247
Fixes #
Manually tested documentation by clicking preview link
.
- [yes] Documented
- [n/a] Unit tested
- [n/a] Integration tests updated
> chore: Fix broken links in docs

- integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
Fixes #2251 
It's just fixing an integration test
> Fix integration tests, broken because FlankNoTestsError with Exit code 3

- .github/workflows/create_new_release.yml
Reverts Flank/flank#2315.
Switching back to automatic releases when the `release_notes_generation` PR is generated and merged.
> Revert "chore: Update create_new_release workflow to be manually run"

- .github/workflows/update_dependencies.yml
No need to auto-run this for now.
> chore: Remove schedule from update_dependencies

- settings.gradle.kts
Remove Gradle Enterprise from flank builds as we currently don't have ownership of a Gradle Enterprise account.
> build: remove Gradle Enterprise plugin/config

- docs/index.md
> docs: fix list formatting in "Authenticate with a service account" section

- .github/workflows/generate_release_notes.yml
- .github/workflows/macos_workflow.yml
- .github/workflows/release.yml
- .github/workflows/release_flank_scripts.yml
- .github/workflows/release_flank_wrapper.yml
- .github/workflows/run_integration_tests.yml
- .github/workflows/tag_next_release.yml
- .github/workflows/ubuntu_workflow.yml
- .github/workflows/update_dependencies.yml
- .github/workflows/windows_workflow.yml
- .github/workflows/wsl_workflow.yml
Gradle Enterprise as removed in https://github.com/Flank/flank/pull/2324
> build: remove GRADLE_ENTERPRISE_ACCESS_KEY from workflows

- docs/index.md
- docs/onboarding/1_environment_setup.md
- integration_tests/src/test/kotlin/integration/CustomShardingIT.kt
- integration_tests/src/test/resources/cases/flank_android_custom_sharding.yml
- integration_tests/src/test/resources/cases/flank_android_multiple_apk.yml
- integration_tests/src/test/resources/cases/flank_android_multiple_devices.yml
- integration_tests/src/test/resources/cases/flank_android_run_timeout.yml
- integration_tests/src/test/resources/compare/AllTestFilteredIT-android-compare
- integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare
- integration_tests/src/test/resources/compare/GameloopIT-android-compare
- integration_tests/src/test/resources/compare/GameloopIT-ios-compare
- integration_tests/src/test/resources/compare/IgnoreFailedIT-compare
- integration_tests/src/test/resources/compare/MultipleApksIT-compare
- integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
- integration_tests/src/test/resources/compare/RunTimeoutIT-compare
- integration_tests/src/test/resources/compare/SanityRoboIT-compare
- integration_tests/src/test/resources/compare/TestFilteringIT-compare
- test_projects/flutter/flutter_example/build_and_run_tests_firebase.sh
- test_runner/flank.ios.yml
- test_runner/flank.yml
- test_runner/src/main/kotlin/ftl/mock/MockServer.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
- test_runner/src/test/kotlin/ftl/args/yml/ErrorParserTest.kt
- test_runner/src/test/kotlin/ftl/args/yml/test_error_yaml_cases/flank-bad-yaml-formatting.yml
The previous project, 'flank-open-source', is not owned/managed by Google and the team now maintaining Flank. Move to a new project, 'ftl-flank-open-source', which is owned/managed by Google. The service account credentials used in the integration test workflow have also been updated to a service account associated with the new project.
Local integration tests are passing
> test: update Google cloud project used in tests

- action.yml
use an invocation of `find` that works on macOS as well as ubuntu
Fixes #2332 
macOS before:
```
$ find -name "flank-links.log"
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```
macOS after:
```
$ find . -name "flank-links.log"
./test_runner/flank-links.log
./integration_tests/flank-links.log
```
ubuntu:
```
$ find . -name "flank-links.log"
./test_runner/flank-links.log
```
The important bit is that the find command succeeds.
> update action to support macOS

- test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
- test_runner/src/main/kotlin/ftl/client/google/GcTestMatrix.kt
- test_runner/src/main/kotlin/ftl/client/google/GcToolResults.kt
- test_runner/src/main/kotlin/ftl/client/google/IosCatalog.kt
- test_runner/src/main/kotlin/ftl/client/google/OsVersion.kt
- test_runner/src/main/kotlin/ftl/client/google/run/android/GcAndroidTestMatrix.kt
- test_runner/src/main/kotlin/ftl/client/google/run/ios/GcIosTestMatrix.kt
- test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
- test_runner/src/test/kotlin/ftl/reports/outcome/BillableMinutesTest.kt
Flank does not pass the the HTTP header flag X-Goog-user-Project with project Id when using end user credentials. This results in HTTP error 403 (PERMISSION_DENIED). This fix sets the flag so the tests can be run by the user.
Fixes #2347
Before:
> ./gradlew runFlank
`
"message": "Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the testing.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/. If you are getting this error with …
> Fixes missing HTTP header X-Goog-User-Project

- test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
- test_runner/src/main/kotlin/ftl/client/google/GcTestMatrix.kt
- test_runner/src/main/kotlin/ftl/client/google/GcToolResults.kt
- test_runner/src/main/kotlin/ftl/client/google/IosCatalog.kt
- test_runner/src/main/kotlin/ftl/client/google/OsVersion.kt
- test_runner/src/main/kotlin/ftl/client/google/run/android/GcAndroidTestMatrix.kt
- test_runner/src/main/kotlin/ftl/client/google/run/ios/GcIosTestMatrix.kt
- test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
- test_runner/src/test/kotlin/ftl/reports/outcome/BillableMinutesTest.kt
Reverts Flank/flank#2348
Unfortunately, this has unintended consequences for authorization with service accounts. Reverting/releasing a new version to limit the spread of the versions containing this change.
> fix: Revert "Fixes missing HTTP header X-Goog-User-Project"

- test_runner/src/main/kotlin/ftl/adapter/google/GoogleTestMatrixAdapter.kt
- test_runner/src/main/kotlin/ftl/api/TestMatrix.kt
- test_runner/src/main/kotlin/ftl/client/junit/CreateJUnitTestCase.kt
- test_runner/src/main/kotlin/ftl/client/junit/CreateJUnitTestSuite.kt
- test_runner/src/main/kotlin/ftl/client/junit/CreateTestSuiteOverviewData.kt
- test_runner/src/main/kotlin/ftl/reports/api/data/TestSuiteOverviewData.kt
- test_runner/src/test/kotlin/ftl/json/OutcomeDetailsFormatterTest.kt
- test_runner/src/test/kotlin/ftl/reports/api/CreateJUnitTestCaseKtTest.kt
- test_runner/src/test/kotlin/ftl/reports/api/CreateJUnitTestSuiteKtTest.kt
- test_runner/src/test/kotlin/ftl/reports/api/CreateTestSuiteOverviewDataKtTest.kt
test case time overhead calculation was incorrectly processing deflake reruns & reporting negative test case times.
Overhead (as described in #557) no longer exists in FTL, so this feature is not useful anymore.
Fixes #2363
Unit tests updated
> fix: Removed test case time overhead calculation

- action.yml
Fixes #
Illegal use of `secrets`, see comment in this PR for more context
https://github.com/Flank/flank/pull/2360
I'm working on a way to resolve the original issue (rate-limiting) without breaking things, but this pull request will at least fix the new problem in the meantime.
.
> fix: Remove usage of secrets to fix failing builds

- test_runner/src/main/resources/android_catalog.json
- test_runner/src/main/resources/ios_catalog.json
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
This is a prerequisite for fixing #2401 because arm devices are not included in the current version of the catalog.
> chore: update device catalogs and associated tests

- test_runner/src/main/kotlin/ftl/args/IArgs.kt
- test_runner/src/main/kotlin/ftl/args/PrepareAndroidCommonConfig.kt
- test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
- test_runner/src/main/kotlin/ftl/config/Device.kt
- test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Current correct behavior:
* If max-test-shards is set to `-1`, **AND ONLY** physical devices are configured, Flank will adjust max-test-shards to the upper limit for physical devices
* If max-test-shards is set to `-1`, **AND ONLY** virtual devices are configured, Flank will adjust max-test-shards to the upper limit for virtual devices
* If max-test-shards is set to a value higher than the upper limit for physical devices **AND ONLY** physical devices are configured, Flank will throw a configuration error
* If max-test-shards is set to a value higher than the upper limit for physical devices **AND BOTH** physical and virtual devices are configured, Flank will adjust max-test-shards to the upper limit for physical devices
* If max-test-shards is set to a value higher than the upper limit …
> fix: set correct max test shards when arm devices are configured

- docs/index.md
- test_runner/flank.ios.yml
- test_runner/flank.yml
Fixes #
Update the results-dir docs to avoid mistakes where unique objects are not created.
Note: ideally, we'd have some string to approximate the unique object behavior, e.g., ${TIMESTAMP}_tmp or something of the like, but given the lack of this, let's guide folks away from setting this at all.
just a docs update
> Update docs to guide folks away from mistakes with results-dir and non-unique names.

- test_runner/src/main/kotlin/ftl/client/google/GcStorage.kt
Fixes #
> Client configuration only, no reliable way to recreate this issue.
> feat: Add retry configuration to Google Cloud Storage client

- .github/workflows/release.yml
- docs/release_process.md
- flank-scripts/src/main/kotlin/flank/scripts/ops/github/DeleteOldRelease.kt
- flank-scripts/src/main/kotlin/flank/scripts/ops/github/ReleaseFlank.kt
hub was removed as part of https://github.com/actions/runner-images/issues/8362
This change removes our dependency on hub and replaces all references with gh.
Github Actions are broken, so we will know this is working when we can release in an automated fashion.
> fix: Replace hub with GitHub CLI 'gh' for GitHub Actions

- .github/workflows/release.yml
- flank-scripts/src/main/kotlin/flank/scripts/ops/github/ReleaseFlank.kt
`GIT_SHORT_HASH` and its resulting usage seems to only be used in places where it becomes a human readable description. The release was recently switched to the `gh` command instead of `hub`, which seems to require a full sha rather than the short version.
> ci: pass full commit sha through release command

- test_runner/src/main/kotlin/ftl/args/IArgs.kt
Fixes #
Client configuration only. Already has unit tests.
> fix: Update shard limit for Arm devices to 200

- test_runner/src/main/kotlin/ftl/domain/testmatrix/UpdateTestMatrix.kt
- test_runner/src/test/kotlin/ftl/api/TestMatrixTest.kt
This PR fixes the issue where `isRoboTest` was initially set to false by default, and was not being updated for Robo test matrices. The fix adds `isRoboTest = newMatrix.isRoboTest` to the updateProperties function, ensuring that the `isRoboTest` field is correctly set when the matrix properties are updated.
fixes https://github.com/Flank/flank/issues/2497
.
> fix: set isRoboTest to true for robo tests

- docs/feature/summary_output.md
Fixed formatting in the `summary_output.md` file to ensure the "Possible outputs" section renders correctly in HTML.
fixes https://github.com/Flank/flank/issues/2371
Visit https://flank.github.io/flank/feature/summary_output/ to verify the fix.
> Fix markdown formatting on github pages

- .github/workflows/macos_workflow.yml
- .github/workflows/release.yml
- .github/workflows/release_flank_scripts.yml
- .github/workflows/release_flank_wrapper.yml
- .github/workflows/run_integration_tests.yml
- .github/workflows/tag_next_release.yml
- .github/workflows/ubuntu_workflow.yml
- .github/workflows/update_dependencies.yml
- .github/workflows/windows_workflow.yml
- .github/workflows/wsl_workflow.yml
Also updates gradle action according to this: https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlegradle-build-action-has-been-replaced-by-gradleactionssetup-gradle
Fixes #https://github.com/Flank/flank/issues/2544
> ci: update ubuntu_workfow to use GITHUB_STEP_SUMMARY instead of posting comments

- .github/workflows/release.yml
Fixes 
```
Run flankScripts github make_release --input-file=./test_runner/build/libs/flank.jar --git-tag=$RELEASE_TAG --commit-hash=$GITHUB_SHA --snapshot
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
Error: Process completed with exit code 4.
```
> ci: add GH_TOKEN to some ci steps
