Flank/flank

Flank/src/main/java/com/walmart/otto/tools/GsutilTool.java
**After**
```
Uploading: app.apk to bucket: gs://apk-bucket-2017-05-26-11-35
Creating gs://apk-bucket-2017-05-26-11-35/...
Uploading: test.apk to bucket: gs://apk-bucket-2017-05-26-11-35
```
**Before**
```
Uploading: app.apk to bucket: gs://apk-bucket-2017-05-26-10-05
Creating gs://apk-bucket-2017-05-26-10-05/...
Copying file://app.apk [Content-Type=application/vnd.android.package-archive]...
/ [0 files][    0.0 B/ 30.7 MiB]
-
- [0 files][792.0 KiB/ 30.7 MiB]
\
\ [0 files][  2.3 MiB/ 30.7 MiB]
|
/
/ [0 files][  3.9 MiB/ 30.7 MiB]
-
- [0 files][  5.4 MiB/ 30.7 MiB]
\
|
| [0 files][  7.0 MiB/ 30.7 MiB]
/
/ [0 files][  8.5 MiB/ 30.7 MiB]
-
\
\ [0 files][ 10.1 MiB/ 30.7 MiB]
|
| [0 files][ 11.6 MiB/ 30.7 MiB]
/
-
- [0 files][ 13.2 MiB/ 30.7 MiB]
\
\ [0 files][ 14.7 MiB/ 30.7 MiB]
|
/
/ [0 …
```
=> Quiet copy

Flank/src/main/java/com/walmart/otto/tools/GsutilTool.java
#16
```
$ java -jar Flank-1.2.0.jar app.apk test.apk
Creating bucket: 2017-05-31_21:24:47.249000_zKzY
Uploading: app.apk to bucket: 2017-05-31_21:24:47.249000_zKzY
Uploading: test.apk to bucket: 2017-05-31_21:24:47.249000_zKzY
```
=> Add uniqueBucketName to match gcloud SDK

Flank/src/main/java/com/walmart/otto/tools/GsutilTool.java
=> Revert "Add uniqueBucketName to match gcloud SDK"

Flank/src/main/java/com/walmart/otto/tools/GsutilTool.java
```
$ ./e2e_test.sh
:clean
:compileJava
Note: /code/flank/Flank/src/main/java/com/walmart/otto/tools/ProcessBuilder.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources NO-SOURCE
:classes
:jar
:assemble
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build
BUILD SUCCESSFUL
Total time: 0.959 secs
+ java -jar ./build/libs/Flank-1.2.0.jar ../test_app/apks/app-debug.apk ../test_app/apks/app-debug-androidTest.apk
Local 'flank.tests' found. It contains test execution times used to create shards with configurable durations. Default shard duration is 120 …
```
=> Quiet all gsutil commands

Flank/src/main/java/com/walmart/otto/tools/ProcessExecutor.java
```
Local 'flank.tests' found. It contains test execution times used to create shards with configurable durations. Default shard duration is 120 seconds.
$ gsutil --quiet mb gs://delta-essence-114723-flank/ 
ServiceException: 409 Bucket delta-essence-114723-flank already exists.
Creating bucket: gs://delta-essence-114723-flank/
Uploading: /code/flank/test_app/apks/app-debug.apk to: gs://delta-essence-114723-flank/2017-06-02_00:29:47.711000_YhSn/
$ gsutil --quiet cp /code/flank/test_app/apks/app-debug.apk gs://delta-essence-114723-flank/2017-06-02_00:29:47.711000_YhSn/ 
Uploading: /code/flank/test_app/apks/app-debug-androidTest.apk to: gs://delta-essence-114723-flank/2017-06-02_00:29:47.711000_YhSn/
$ gsutil --quiet cp /code/flank/test_app/apks/app-debug-androidTest.apk …
```
=> Skip upload progress % in debug output

Flank/build.gradle, Flank/gradle/wrapper/gradle-wrapper.properties, Flank/src/main/java/com/walmart/otto/Constants.java, Flank/src/main/java/com/walmart/otto/Flank.java, Flank/src/main/java/com/walmart/otto/configurator/ConfigReader.java, Flank/src/main/java/com/walmart/otto/configurator/Configurator.java, Flank/src/main/java/com/walmart/otto/reporter/PriceReporter.java, Flank/src/main/java/com/walmart/otto/reporter/TimeReporter.java, Flank/src/main/java/com/walmart/otto/shards/ShardCreator.java, Flank/src/main/java/com/walmart/otto/shards/ShardExecutor.java, Flank/src/main/java/com/walmart/otto/tools/GcloudTool.java, Flank/src/main/java/com/walmart/otto/tools/GsutilTool.java, Flank/src/main/java/com/walmart/otto/tools/ProcessBuilder.java, Flank/src/main/java/com/walmart/otto/tools/ProcessExecutor.java, Flank/src/main/java/com/walmart/otto/tools/StreamBoozer.java, Flank/src/main/java/com/walmart/otto/tools/Tool.java, Flank/src/main/java/com/walmart/otto/tools/ToolManager.java, Flank/src/main/java/com/walmart/otto/utils/FileUtils.java, Flank/src/main/java/com/walmart/otto/utils/FilterUtils.java, Flank/src/main/java/com/walmart/otto/utils/XMLUtils.java, Flank/src/test/java/com/walmart/otto/reporter/PriceReporterTest.java
=> Google format

.travis.yml, cloud_testing/cloud_api_poc/build.gradle, cloud_testing/cloud_api_poc/gradle, cloud_testing/cloud_api_poc/gradle.properties, cloud_testing/cloud_api_poc/gradlew, cloud_testing/cloud_api_poc/gradlew.bat, cloud_testing/cloud_api_poc/readme.md, cloud_testing/cloud_api_poc/settings.gradle, cloud_testing/cloud_api_poc/src/main/java/Main.java, cloud_testing/readme.md
I'm building out a small proof of concept using APIs instead of the `gcloud` CLI.
```
// todo: upload apk via google-cloud-storage
// todo: schedule test via google-api-services-testing
// todo: fetch rest results via google-api-services-toolresults
```
Apk upload is working. I'll continue working on the rest of the integration.
=> Cloud API proof of concept

cloud_testing/client_generation.md
=> Improve overview details

cloud_testing/apis/storage_v1.json, cloud_testing/apis/testing/src/main/java/com/google/testing/Testing.java, cloud_testing/apis/testing/src/main/java/com/google/testing/model/AndroidInstrumentationTest.java, cloud_testing/apis/testing/src/main/java/com/google/testing/model/ClientInfoDetail.java, cloud_testing/apis/testing_v1.json, cloud_testing/apis/toolresults_v1beta3.json, cloud_testing/client_generation.md, cloud_testing/generate.sh
* Regenerate testing library using latest API json & api-client-generator
=> Orchestrator

Flank/src/main/java/com/walmart/otto/Flank.java, Flank/src/main/java/com/walmart/otto/configurator/ConfigReader.java, Flank/src/main/java/com/walmart/otto/configurator/Configurator.java, Flank/src/main/java/com/walmart/otto/utils/FilterUtils.java, Flank/src/test/java/com/walmart/otto/configurator/ConfigReaderTest.java, Flank/src/test/java/com/walmart/otto/utils/FilterUtilsTest.java, Flank/src/test/resources/skip-tests.properties
fixes https://github.com/TestArmada/flank/issues/79
=> Issue #79: Skipping tests in certain package

Flank/build.gradle, Flank/src/main/java/com/walmart/otto/Flank.java, Flank/src/test/java/com/walmart/otto/ParsingTest.java
=> CLI command parsing

cloud_testing/kotlin_poc/src/main/kotlin/ftl/Main.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcTestMatrix.kt, cloud_testing/mock_server/.gitignore, cloud_testing/mock_server/build.gradle.kts, cloud_testing/mock_server/buildSrc/src/main/java/Deps.java, cloud_testing/mock_server/gradle, cloud_testing/mock_server/gradle.properties, cloud_testing/mock_server/gradlew, cloud_testing/mock_server/gradlew.bat, cloud_testing/mock_server/readme.md, cloud_testing/mock_server/settings.gradle, cloud_testing/mock_server/src/main/kotlin/ftl/Main.kt
* Add individual test running support
* Start of mock server
=> Cloud testing

Flank/src/main/java/com/walmart/otto/aggregator/ArtifactsProcessor.java
We were attempting to copy the source logcat file before actually checking if it exists or not. Ops :)
Related to #100
=> Make sure source logcat file exists before copying it

cloud_testing/kotlin_poc/bash/flank, cloud_testing/kotlin_poc/bash/update_flank.sh, cloud_testing/kotlin_poc/build.gradle.kts, cloud_testing/kotlin_poc/src/main/kotlin/ftl/Main.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/cli/RefreshCommand.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/cli/RunCommand.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/FtlConstants.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/YamlConfig.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/reports/CostSummary.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/reports/MergeJUnitResults.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/reports/ResultSummary.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/run/TestRunner.kt
=> Add pico CLI to kotlin_poc

.travis.yml, cloud_testing/kotlin_poc/build.gradle.kts, cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/FtlConstants.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcToolResults.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/run/TestRunner.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/util/Utils.kt, cloud_testing/kotlin_poc/src/test/kotlin/ftl/MainTest.kt, cloud_testing/mock_server.md, cloud_testing/mock_server/build.gradle.kts, cloud_testing/mock_server/src/main/kotlin/ftl/Main.kt
=> Run test runner on Travis CI using mocked server

cloud_testing/kotlin_poc/build.gradle.kts
=> Add JaCoCo code coverage reporting

cloud_testing/kotlin_poc/readme.md, cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/YamlConfig.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/util/Utils.kt
=> Make GOOGLE_CLOUD_PROJECT optional

cloud_testing/kotlin_poc/readme.md, cloud_testing/kotlin_poc/src/main/kotlin/ftl/ios/IosCatalog.kt, cloud_testing/xctest_parser/build.gradle.kts
=> Add iOS beta detection

cloud_testing/kotlin_poc/readme.md
There are two ways of authenticating
=> Added info about service account

cloud_testing/kotlin_poc/src/main/kotlin/ftl/Main.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/cli/DoctorCommand.kt
```
$ flank doctor
Flank successfully connected to iOS catalog
```
=> Add flank doctor

cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/YamlConfig.kt, cloud_testing/kotlin_poc/src/test/kotlin/ftl/config/YamlConfigTest.kt
=> Make YamlConfig output platform specific.

cloud_testing/xctest_parser/build.gradle.kts, cloud_testing/xctest_parser/src/main/kotlin/xctest/Parse.kt, cloud_testing/xctest_parser/src/main/kotlin/xctest/Xctestrun.kt, cloud_testing/xctest_parser/src/test/kotlin/xctest/XctestrunTest.kt
=> Add Immutable test. Deep clone object in rewrite

cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/YamlConfig.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcAndroidMatrix.kt, cloud_testing/kotlin_poc/src/test/kotlin/ftl/config/YamlConfigTest.kt
=> Add default Android device config

cloud_testing/kotlin_poc/flank.yml, cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/YamlConfig.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcAndroidMatrix.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt, cloud_testing/kotlin_poc/src/test/kotlin/ftl/config/YamlConfigTest.kt, cloud_testing/kotlin_poc/src/test/kotlin/ftl/fixtures/flank.yml
=> Add environment variable flags for Android

cloud_testing/kotlin_poc/flank.yml, cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/YamlConfig.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcIosMatrix.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/run/IosTestRunner.kt, cloud_testing/kotlin_poc/src/test/kotlin/ftl/config/YamlConfigTest.kt, cloud_testing/kotlin_poc/src/test/kotlin/ftl/fixtures/flank.yml
=> Make directoriesToPull a yaml config option

cloud_testing/kotlin_poc/src/main/kotlin/ftl/android/AndroidCatalog.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/cli/RunCommand.kt, cloud_testing/kotlin_poc/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
=> Add Android device config validation

cloud_testing/kotlin_poc/src/main/kotlin/ftl/config/YamlConfig.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/gc/GcStorage.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/run/AndroidTestRunner.kt, cloud_testing/kotlin_poc/src/main/kotlin/ftl/run/TestRunner.kt, cloud_testing/kotlin_poc/src/test/kotlin/ftl/config/YamlConfigTest.kt, cloud_testing/kotlin_poc/src/test/kotlin/ftl/fixtures/flank.yml
=> Auto create root bucket if it doesn't exist.

jitpack.yml
=> Issue #234: Automate every release - build snapshot jar

cloud_testing/mock_server/src/main/kotlin/ftl/Main.kt
Allows testing the AndroidCatalog against the mock.
=> Add Android device catalog to mock server

cloud_testing/kotlin_poc/build.gradle.kts
=> dex parser library version bump to 2.0.0

cloud_testing/kotlin_poc/build.gradle.kts, cloud_testing/kotlin_poc/buildSrc/src/main/java/Deps.java, cloud_testing/kotlin_poc/src/main/kotlin/ftl/ios/Xctestrun.kt, cloud_testing/kotlin_poc/src/test/kotlin/ftl/ios/XctestrunTest.kt
=> Upstream cloneable

test_runner/src/main/kotlin/ftl/Main.kt, test_runner/src/main/kotlin/ftl/reports/HtmlErrorReport.kt, test_runner/src/main/kotlin/ftl/util/Utils.kt, test_runner/src/main/resources/version.txt
=> Read version from version.txt resource

README.md, test_runner/flank.ios.yml, test_runner/flank.yml, test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt, test_runner/src/main/kotlin/ftl/args/IArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt, test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt, test_runner/src/main/kotlin/ftl/run/AndroidTestRunner.kt, test_runner/src/main/kotlin/ftl/run/GenericTestRunner.kt, test_runner/src/main/kotlin/ftl/run/IosTestRunner.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt
=> Add testShards -1 support for one test per shard

test_runner/build.gradle.kts, test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt, test_runner/src/test/kotlin/ftl/args/IosArgsFileTest.kt, test_runner/src/test/kotlin/ftl/json/SavedMatrixTest.kt, test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt, test_runner/src/test/kotlin/ftl/test/util/FlankTestRunner.kt, test_runner/src/test/kotlin/ftl/test/util/MockServer.kt, test_runner/src/test/kotlin/ftl/test/util/TestArtifact.kt
=> Test SavedMatrix

README.md, test_runner/src/main/kotlin/ftl/Main.kt, test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt
Document shortcut commands
Fix #250
=> Add iOS and Android as top level commands

test_runner/src/main/kotlin/ftl/json/MatrixMap.kt, test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
=> Fix success check

test_runner/build.gradle.kts, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidDoctorCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRefreshCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosDoctorCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRefreshCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> 100% coverage on ftl.cli.*

test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt, test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt, test_runner/src/main/kotlin/ftl/run/AndroidTestRunner.kt, test_runner/src/main/kotlin/ftl/run/GenericTestRunner.kt, test_runner/src/main/kotlin/ftl/run/IosTestRunner.kt, test_runner/src/main/kotlin/ftl/util/ShardCounter.kt, test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt, test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt, test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt
=> Improve shard naming

test_runner/src/main/kotlin/ftl/util/Billing.kt, test_runner/src/test/kotlin/ftl/util/BillingTest.kt
=> Only print nonzero cost

test_runner/flank.ios.yml, test_runner/flank.yml, test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/IArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt, test_runner/src/main/kotlin/ftl/run/AndroidTestRunner.kt, test_runner/src/main/kotlin/ftl/run/GenericTestRunner.kt, test_runner/src/main/kotlin/ftl/run/IosTestRunner.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/FlankYmlTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsFileTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/doctor/DoctorTest.kt, test_runner/src/test/kotlin/ftl/fixtures/flank.gcs.yml, test_runner/src/test/kotlin/ftl/fixtures/flank.ios.gcs.yml, test_runner/src/test/kotlin/ftl/fixtures/flank.ios.yml, test_runner/src/test/kotlin/ftl/fixtures/flank.local.yml, test_runner/src/test/kotlin/ftl/fixtures/flank2.ios.yml, test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt
=> Rename testRuns to repeatTests

test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt, test_runner/src/main/kotlin/ftl/args/yml/IosFlankYml.kt, test_runner/src/main/kotlin/ftl/doctor/Doctor.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/doctor/DoctorTest.kt
=> Fix doctor YAML parsing

README.md, contributing.md, test_runner/flank.ios.yml, test_runner/flank.yml, test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/ArgsToString.kt, test_runner/src/main/kotlin/ftl/args/IArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/args/yml/GcloudYml.kt, test_runner/src/main/kotlin/ftl/config/Device.kt, test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt, test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt, test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt, test_runner/src/main/kotlin/ftl/reports/CostReport.kt, test_runner/src/main/kotlin/ftl/util/Billing.kt, test_runner/src/main/kotlin/ftl/util/Utils.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/fixtures/flank.gcs.yml, test_runner/src/test/kotlin/ftl/fixtures/flank.ios.gcs.yml, test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt, test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt, test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt, test_runner/src/test/kotlin/ftl/test/util/MockServer.kt, test_runner/src/test/kotlin/ftl/util/BillingTest.kt
=> Add results-history-name & Update args toString

README.md, test_runner/flank.ios.yml, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/args/yml/IosGcloudYml.kt, test_runner/src/main/kotlin/ftl/doctor/Doctor.kt, test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt, test_runner/src/main/kotlin/ftl/ios/IosCatalog.kt, test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/ios/IosCatalogTest.kt
=> Add xcode-version support

test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt, test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt, test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt, test_runner/src/main/kotlin/ftl/run/AndroidTestRunner.kt, test_runner/src/main/kotlin/ftl/run/IosTestRunner.kt, test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt, test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt, test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt
=> Fix duplicate tool results history ids

test_runner/build.gradle.kts, test_runner/build_earlgrey_example.sh, test_runner/src/main/kotlin/ftl/reports/HtmlErrorReport.kt, test_runner/src/main/kotlin/ftl/run/AndroidTestRunner.kt, test_runner/src/main/kotlin/ftl/run/GenericTestRunner.kt, test_runner/src/main/kotlin/ftl/run/IosTestRunner.kt, test_runner/src/main/kotlin/ftl/run/TestRunner.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/TestCommandTest.kt
=> Remove GlobalScope coroutines

test_runner/src/main/kotlin/ftl/reports/xml/JUnitXml.kt, test_runner/src/main/kotlin/ftl/reports/xml/model/JUnitTestCase.kt, test_runner/src/test/kotlin/ftl/reports/xml/JUnitXmlTest.kt
=> Support skipped on JUnitTestCase & add test

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
=> CLI support for all args: --test param

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
=> --use-orchestrator param

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
=> Add --auto-google-login and --no-auto-google-login

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
=> Add --environment-variables

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> Add --results-bucket

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> Add --record-video --no-record-video

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> Add --results-history-name

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> Add --test-shards

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> Add --repeat-tests

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> Add --test-targets-always-run

test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> Add --test-targets for iOS

test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> Add --xcode-version

test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/args/yml/IosGcloudYml.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/main/kotlin/ftl/config/FtlConstants.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> Add --device

test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
=> Fix iOS and Android --help formatting

README.md, docs/smart_flank.md, release_notes.md
=> Smart Flank Design Doc

release_notes.md, test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
Regresion [here](https://github.com/TestArmada/flank/commit/fcbaf02f9ccf6167563431e2100b88753941264e#diff-c6e4137a66868fe43ef798f4b2e94c00L145)
Fix #443
=> Fix create Gcs bucket method

test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
=> Fix GcStorage auth by removing user auth

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt, test_runner/src/main/kotlin/ftl/args/IArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/main/kotlin/ftl/shard/Shard.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/FlankYmlTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt, test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
Fixes #399 
Simpler version of the previous PR: https://github.com/TestArmada/flank/pull/470
=> Issue #399: Smart Flank - Dynamic bucket counts v2

test_runner/src/main/kotlin/ftl/run/AndroidTestRunner.kt, test_runner/src/main/kotlin/ftl/run/IosTestRunner.kt
=> Execute with retry

test_runner/src/main/kotlin/ftl/gc/GcIosMatrix.kt
=> Issue #480: Bug: iOS is hardcoding locale and orientation

test_runner/src/main/kotlin/ftl/util/Utils.kt, test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
=> Issue #484: Name with ':' breaks in windows

README.md, test_runner/flank.ios.yml, test_runner/flank.yml
=> Document all Flank properties in README

test_runner/src/main/kotlin/ftl/shard/Shard.kt, test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
=> testShards = -1, shardTime = 119 broken

test_runner/build.gradle.kts, test_runner/src/main/kotlin/ftl/cli/auth/LoginCommand.kt, test_runner/src/main/kotlin/ftl/config/FtlConstants.kt, test_runner/src/main/kotlin/ftl/gc/GcAuth.kt
=> Replace google-oauth-java-client with google-auth-library-java

release_notes.md, test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt, test_runner/src/test/kotlin/ftl/test/util/TestArtifact.kt
=> Fix nullability check in SavedMatrix.

test_runner/src/main/kotlin/ftl/args/IArgs.kt, test_runner/src/main/kotlin/ftl/run/GenericTestRunner.kt, test_runner/src/main/kotlin/ftl/run/TestRunner.kt, test_runner/src/main/kotlin/ftl/util/MatrixUtil.kt
=> Fix --local-result-dir

test_runner/gradle/wrapper/gradle-wrapper.properties, test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
=> Fix bucket list error

release_notes.md, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/args/yml/IosGcloudYml.kt, test_runner/src/main/kotlin/ftl/util/Utils.kt
=> Fix --test & --xctestrun-file on iOS CLI

release_notes.md, test_runner/.gitignore, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt, test_runner/src/main/kotlin/ftl/run/TestRunner.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> Add --dump-shards to flank android|ios run

release_notes.md, test_runner/src/main/kotlin/ftl/shard/Shard.kt, test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
=> Improve shard count validation

README.md
I want to make the documentation for obtaining coverage using Orchestrator easier to understand.
=> Update README.md to add more description about GrantPermissionsRule

test_runner/build.gradle.kts, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/main/kotlin/ftl/gc/GcStorage.kt, test_runner/src/main/kotlin/ftl/mock/MockServer.kt, test_runner/src/main/kotlin/ftl/mock/TestArtifact.kt, test_runner/src/main/kotlin/ftl/util/Utils.kt, test_runner/src/test/kotlin/Debug.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt, test_runner/src/test/kotlin/ftl/ios/ParseTest.kt, test_runner/src/test/kotlin/ftl/ios/XctestrunTest.kt, test_runner/src/test/kotlin/ftl/test/util/FlankTestRunner.kt
=> Add --dry option to android run & ios run

test_runner/buildSrc/src/main/kotlin/Deps.kt
Fixes #N/A
Change kotlin version 1.3.50 -> 1.3.70
=> Bump up kotlin version to 1.3.70

test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
Fixes #662 
* fixed class path 
* add additional verification to check if process was started
=> Fix tests and add additional check verification

test_runner/buildSrc/src/main/kotlin/Deps.kt, test_runner/gradle/wrapper/gradle-wrapper.properties
=> Update bugsnag to fix jar release task

test_runner/src/main/kotlin/ftl/args/yml/AndroidFlankYml.kt, test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Fixes bug introduced with #639
=> Implement fix for additional app feature

test_runner/src/main/kotlin/ftl/args/AndroidTestShard.kt, test_runner/src/main/kotlin/ftl/gc/GcTestMatrix.kt, test_runner/src/main/kotlin/ftl/run/CancelLastRun.kt, test_runner/src/main/kotlin/ftl/run/NewTestRun.kt, test_runner/src/main/kotlin/ftl/run/RefreshLastRun.kt, test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt, test_runner/src/main/kotlin/ftl/run/common/PollMatrices.kt, test_runner/src/test/kotlin/Tmp.kt, test_runner/src/test/kotlin/ftl/gc/GcTestMatrixTest.kt
Small refactor that prepares background for future work (especially #532 )
=> Refactor coroutines

README.md, test_runner/bash/update_flank.sh, test_runner/build.gradle.kts
* Remove redundant `fatJar` task
* Update `update_flank.sh`
* Update `README.md`
=> Remove fatJar task and update update_flank.sh

test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/IArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/CommonRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
* introduce `CommonRunCommand` which keeps duplicated parameters for both android and ios run commands
=> Add CommonRunCommand

test_runner/build.gradle.kts, test_runner/buildSrc/src/main/kotlin/Deps.kt, test_runner/src/main/kotlin/ftl/run/model/RunningDevices.kt, test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt, test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt, test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt, test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt, test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt, test_runner/src/test/kotlin/ftl/gc/GcTestMatrixTest.kt, test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt, test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt, test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt, test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt, test_runner/src/test/kotlin/ftl/run/model/RunningDevicesTest.kt, test_runner/src/test/kotlin/ftl/shard/ShardTest.kt, test_runner/src/test/kotlin/ftl/util/ArtifactsTest.kt, test_runner/src/test/kotlin/ftl/util/MatrixUtilTest.kt
* replace `mockito` with `mockk`
* add tests for `RunningDevices`
=> Replace mockito with mockk.

release_notes.md, test_runner/flank.ios.yml, test_runner/flank.yml, test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/IArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/args/yml/GcloudYml.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/CommonRunCommand.kt, test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt, test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt, test_runner/src/main/kotlin/ftl/gc/Utils.kt, test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt, test_runner/src/test/kotlin/Debug.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
=> Add support for client-details option

test_runner/build.gradle.kts
=> Fix publishing task

release_notes.md, test_runner/build.gradle.kts
=> Update group id to com.github.flank

test_runner/build.gradle.kts
=> Add javadoc and sources jar

test_runner/build.gradle.kts, test_runner/settings.gradle.kts
=> Update project name

test_runner/build.gradle.kts
=> Add javadoc & source jars

test_runner/build.gradle.kts
=> Fix javadoc sources Jar publication

release_notes.md, test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt, test_runner/src/main/kotlin/ftl/gc/GcStorage.kt, test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
=> Add shard name for uploaded xctestrun files

release_notes.md, test_runner/docs/ascii/flank.jar_-android-run.adoc, test_runner/docs/ascii/flank.jar_-firebase-test-android-run.adoc, test_runner/docs/ascii/flank.jar_-firebase-test-ios-run.adoc, test_runner/docs/ascii/flank.jar_-ios-run.adoc, test_runner/flank.ios.yml, test_runner/flank.yml, test_runner/src/main/kotlin/ftl/Main.kt, test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/IArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/CommonRunCommand.kt, test_runner/src/main/kotlin/ftl/run/status/ExecutionStatusPrinter.kt, test_runner/src/main/kotlin/ftl/run/status/OutputStyle.kt, test_runner/src/main/kotlin/ftl/run/status/TestMatrixStatusPrinter.kt, test_runner/src/main/kotlin/ftl/util/StopWatch.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsFileTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt, test_runner/src/test/kotlin/ftl/fixtures/flank.ios.yml, test_runner/src/test/kotlin/ftl/fixtures/flank.local.yml
Fixes #779 
Adds option for output style
=> Add output-style option

release_notes.md, test_runner/src/main/kotlin/ftl/reports/api/ProcessFromApi.kt
Fixes #789   Fixed dry run crashes
=> #789 Fixed dry run crashes

test_runner/buildSrc/src/main/kotlin/Deps.kt
Update dex parser from 2.1.1 -> 2.2.1
=> Update dex parser

test_runner/docs/ascii/flank.jar_-android-run.adoc, test_runner/docs/ascii/flank.jar_-firebase-test-android-run.adoc, test_runner/docs/ascii/flank.jar_-firebase-test-ios-run.adoc, test_runner/docs/ascii/flank.jar_-ios-run.adoc, test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt, test_runner/src/test/kotlin/ftl/run/platform/RunAndroidTestsKtTest.kt, test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
Fixes #846 
`./gradlew check` pass
=> Update unit tests

README.md
Just an update to the readme to match the updated path to the JUnit report for android
=> Updating Readme to include the new path to the JUnit report for smart flank

docs/getting_delete_permission_exception_when_using_results-dir_option.md
This PR adds documentation which summarizes research for #790
=> Add docs for issue 790

docs/host_binaries_solutions_comparison.md, docs/test_artifacts.md
Contains investigation results of #849 
Full documentation can be found in the file: host_binaries_solutions_comparison.md 
By comparing these three solutions, talk with @jan-gogo, and some amount of test git-annex we staying with GitHub releases and automated the release process.
=>  Binary File Storage Research

docs/flank_secrets.md, docs/flank_vision.md
=> Add secrets and vision doc

.github/workflows/release.yml, flank-scripts/src/main/kotlin/flank/scripts/release/hub/ReleaseFlank.kt, flank-scripts/src/main/kotlin/flank/scripts/utils/ShellExecute.kt, test_runner/build.gradle.kts
Fixes Release job
[Release job works](https://github.com/Flank/flank/runs/941034167?check_suite_focus=true) :)
=> fix release job

flank-scripts/src/main/kotlin/flank/scripts/release/hub/ReleaseFlank.kt
Fixes #
Escape `'` characters to avoid problem with release title and tag
=> Fix release title and tag

flank-scripts/src/main/kotlin/flank/scripts/release/hub/ReleaseFlank.kt, flank-scripts/src/main/kotlin/flank/scripts/utils/ShellExecute.kt, release_notes.md
Fixes #931
[Flank release job works properly](https://github.com/Flank/flank/runs/945098075?check_suite_focus=true)
[Labels are displayed correctly](https://github.com/Flank/flank/releases)
=> #931 Delete incorrect flank snapshot labels

docs/release_process.md, release_notes.md
Prepare for `v20.8.0` release
CC: @bootstraponline
=> Release v20.8.0

.github/workflows/release.yml
Fixes #
Condition which run release was bad, now it is fixed
=> Fix incorrect release condition

.github/workflows/macos_workflow.yml, .github/workflows/ubuntu-workflow.yml
=> Fixed running triggers on each PR

.opensource/project.json
Context: 
https://github.com/firebase/firebaseopensource.com/issues/184
=> Convert pages from an array to a map

release_notes.md
This is release notes update for next release `v20.08.1`
=> Release v20.08.1

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Tiger label is added to new issues/bugs by default.
=> chore: Add tigers to issue template

config/detekt.yml, release_notes.md, test_runner/build.gradle.kts, test_runner/buildSrc/src/main/kotlin/Deps.kt, test_runner/src/main/kotlin/ftl/util/MatrixState.kt
Fixes #949 
Run the detekt gradle command.
.
=> style: Update detekt

test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
Fixes #1003 
Tests are passing
=> fix: failing tests

.github/workflows/release.yml, docs/release_process.md, flank-scripts/README.md, flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GenerateChangeLog.kt, flank-scripts/src/main/kotlin/flank/scripts/release/hub/ReleaseFlank.kt, flank-scripts/src/main/kotlin/flank/scripts/release/hub/ReleaseFlankCommand.kt, flank-scripts/src/test/kotlin/flank/scripts/release/hub/ReleaseFlankCommandTest.kt
Fixes #1002 
After making release there is no need to manually input release notes in description
=> ci: Generate release notes for Github release description

.github/workflows/release_notes_generation.yml, test_runner/.gitignore
Fixes #832
Before release new documentation is generated
=> feat: Generating docs before release

test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt
Artifacts are fetched async now.
=> refactor: Fetch artifacts async

.github/workflows/release.yml, README.md, test_runner/build.gradle.kts
Fixes #955 
Flank is published to GitHub packages when making a release job
=> ci: Publish to GitHub packages

flank-scripts/src/main/kotlin/flank/scripts/release/hub/ReleaseFlank.kt
After changing release notes structure, I forgot to change method to update release notes body at GitHub releases.
This small PR, fix that issue
=> fix: Release notes message at GitHub release

test_runner/buildSrc/src/main/kotlin/Deps.kt, test_runner/src/main/kotlin/ftl/args/yml/errors/ConfigurationErrorMessageBuilder.kt, test_runner/src/main/kotlin/ftl/environment/LocalesDescription.kt, test_runner/src/main/kotlin/ftl/environment/android/AndroidModelDescription.kt, test_runner/src/main/kotlin/ftl/environment/android/AndroidSoftwareVersionDescription.kt, test_runner/src/main/kotlin/ftl/environment/ios/IosModelDescription.kt, test_runner/src/main/kotlin/ftl/environment/ios/IosSoftwareVersionDescription.kt, test_runner/src/main/kotlin/ftl/reports/api/CreateTestExecutionData.kt, test_runner/src/main/kotlin/ftl/reports/outcome/TestOutcome.kt, test_runner/src/main/kotlin/ftl/run/common/GetLastGcsPath.kt, test_runner/src/main/kotlin/ftl/run/platform/common/BeforeRunMessage.kt, test_runner/src/main/kotlin/ftl/util/LogTableBuilder.kt
Fixes #1024 
Build finishes without error. Manual verification always appreciated .
=> refactor: Update kotlin version to 1.4

.github/workflows/pr_checks.yml
Pull request checks works correctly within forked repository
=> fix: PR check from fork

test_runner/src/main/kotlin/ftl/json/MatrixMap.kt, test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt, test_runner/src/main/kotlin/ftl/run/NewTestRun.kt, test_runner/src/main/kotlin/ftl/run/RefreshLastRun.kt, test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt, test_runner/src/test/kotlin/ftl/json/MatrixMapTest.kt, test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
Fixes #1038
All the tests pass.
=> refactor: MatrixMap immutability

.github/workflows/release.yml
Fixes #1046 
Add filter to avoid releasing on document changes only
=> fix: Avoid releasing on document changes only

test_runner/build.gradle.kts
Reverts Flank/flank#1071
Those changes will wait for integration tests before the merge.
=> revert: "build: Added options to minimize the shadowJar process" [BEFORE RELEASE!!!] 

.github/workflows/release.yml
Fix for $ in github workflows for the slack notification
=> fix: Fix slack notification in slack

release_notes.md, test_runner/docs/ascii/flank.jar_-android-run.adoc, test_runner/docs/ascii/flank.jar_-firebase-test-android-run.adoc, test_runner/docs/ascii/flank.jar_-firebase-test-ios-run.adoc, test_runner/docs/ascii/flank.jar_-ios-run.adoc
=> revert: "chore: release notes for v20.09.0"

release_notes.md, test_runner/docs/ascii/flank.jar_-android-run.adoc, test_runner/docs/ascii/flank.jar_-firebase-test-android-run.adoc, test_runner/docs/ascii/flank.jar_-firebase-test-ios-run.adoc, test_runner/docs/ascii/flank.jar_-ios-run.adoc
This reverts commit dbb29ac56a20535deff16548340947a3ef1e15eb.
.
=> revert: "[Automatic PR] Generate release notes (#1083)"

release_notes.md
All records contain a pull request authors.
=> fix: add missing authors to release notes

.github/workflows/release.yml
Fixing format changes for Flank release bot.
Need to wait for a release for testing.
Expecting link preview to show correct update text.
=> fix: Flank release bot formatting

test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt, test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
Fixes #1098 
1. Upload apk to gcs bucket
2. Replace (in config yml) local file path with newly uploaded apk (`gs://...`)
3. The test run should proceed normally
=> fix: Fix gcs files validation

test_runner/build.gradle.kts
Fixes #1063 
Re Added as integration tests are complete
=> feat: Readded shadowjar minimization

test_runner/bash/update_flank.sh
run `./gradlew updateFlank` task and see flank shadow jar is correctly build
=> build: Update flank_update script

.github/workflows/release.yml
=> fix: Bump action versioning

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Plugins.kt, buildSrc/src/main/kotlin/Versions.kt, flank-scripts/build.gradle.kts, integration_tests/build.gradle.kts, samples/gradle-export-api/build.gradle.kts, settings.gradle.kts, test_runner/build.gradle.kts
This is aggregate PR for all proposed (and relatively) small improvements for Gradle structure
=> build: Enhance gradle structure

.github/workflows/macos_workflow.yml
Code coverage runs after making coverage report
=> fix: Running Code coverage job

README.md, docs/building_updating_flank.md
=> docs: Optimization docs addition

.github/workflows/macos_workflow.yml, README.md, flank-scripts/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties, test_runner/build.gradle.kts, test_runner/gradle/wrapper/gradle-wrapper.properties, test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt, test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt, test_runner/src/main/kotlin/ftl/gc/GcStorage.kt, test_runner/src/main/kotlin/ftl/util/BugsnagInitHelper.kt, test_runner/src/main/kotlin/ftl/util/Obfuscation.kt, test_runner/src/main/kotlin/ftl/util/TestMatrixExtension.kt, test_runner/src/main/kotlin/ftl/util/Utils.kt, test_runner/src/test/kotlin/ftl/util/FlankBugsnagInitHelperTest.kt
Fixes #1123 
Flank `test_runner` compiles within Java 15
=> feat: add Java 15 compile support

flank-scripts/src/main/kotlin/flank/scripts/utils/Serialization.kt
Flank-scripts generate next release tag
=> fix: Flank-scripts next release tag generation

flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GitHubRelease.kt, flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GithubPullRequest.kt, flank-scripts/src/main/kotlin/flank/scripts/exceptions/FlankScriptsExceptionMappers.kt, flank-scripts/src/main/kotlin/flank/scripts/release/updatebugsnag/BugSnagResponse.kt, flank-scripts/src/main/kotlin/flank/scripts/release/updatebugsnag/UpdateBugSnag.kt, flank-scripts/src/main/kotlin/flank/scripts/utils/Serialization.kt, flank-scripts/src/test/kotlin/flank/scripts/FuelTestRunner.kt, flank-scripts/src/test/kotlin/flank/scripts/utils/SerializationTest.kt
After the update for new kotlin-serialization, API of JSON parsing should be updated to works properly
Flank-scripts serialization works correctly
=> fix: update flank-scripts serialization

junit_html_report/package-lock.json, junit_html_report/package.json
lets get rid of the message
`npm audit fix` was run to fix the culprit errors.
=> fix: Dependabot security issues

.github/workflows/release.yml
Flank action version bump for release notes.
=> fix: Flank action

.github/workflows/update_dependencies.yml, build.gradle.kts, flank-scripts/build.gradle.kts, samples/gradle-export-api/build.gradle.kts, test_runner/build.gradle.kts
Fixes #1168 
`./gradlew flankFullRun` should finish without any errors
=> build: Follow up after dependencies update

README.md
Fixes #1157 
Flank is synced without any problems using described solution
=> docs: Add FAQ section about sync problems

docs/dependencies_update_process.md, flank-scripts/src/main/kotlin/flank/scripts/dependencies/update/DependencyExtensions.kt, flank-scripts/src/main/kotlin/flank/scripts/dependencies/update/UpdateGradle.kt, flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/DependencyExtensionsTest.kt, flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/UpdateGradleTest.kt, flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/testfiles/expected_gradle-wrapper.properties_RC.test, flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/testfiles/report.json
Fixes #1211 
1. Generate report using command `./gradlew dependencyUpdates -DoutputFormatter=json -DoutputDir=.`
2. Build flank scripts using script `./flank-scripts/bash/buildFlankScripts.sh`
3. Run `./flank-scripts/bash/flankScripts dependencies update`
4. `git diff` should print updated gradle wrappers 
```
On branch fix-dependency-gradle
Your branch is up to date with 'origin/fix-dependency-gradle'.
diff --git a/flank-scripts/gradle/wrapper/gradle-wrapper.properties b/flank-scripts/gradle/wrapper/gradle-wrapper.properties
index 21f9f98d..88fe4c8a 100644
--- a/flank-scripts/gradle/wrapper/gradle-wrapper.properties
+++ b/flank-scripts/gradle/wrapper/gradle-wrapper.properties
@@ -1,5 +1,5 @@
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists …
```
=> ci: Enable RC versions for gradle (dependency update task)

README.md, flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/UpdateGradleTest.kt, test_runner/flank.ios.yml, test_runner/flank.yml, test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/IosArgs.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Fixes #1185
All options are printed during Flank run
=> feat: Added printing missing options

README.md, test_runner/flank.ios.yml, test_runner/flank.yml, test_runner/src/main/kotlin/ftl/config/common/CommonGcloudConfig.kt
Fixes #1223 
Documentation should be replaced in all occurrences.
=> docs: Update documentation

.github/workflows/release.yml, .github/workflows/release_notes_generation.yml, .github/workflows/update_dependencies.yml
Fixes #1226 
- Workflows work properly like previous
- No deprecation messages on workflows
=> ci: Update deprecated options ::set-env and ::add-path

docs/index.md, test_runner/flank.yml, test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt, test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt, test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
=> feat: Obb file addition

.github/workflows/integration_tests.yml, .github/workflows/windows-non-wsl-workflow.yml, .github/workflows/wsl-workflow.yml
Review counter does not work properly, this is quick fix for it
=> chore: Make integration test temporary manual

buildSrc/src/main/kotlin/Versions.kt, flank-scripts/bash/buildFlankScripts.bat, flank-scripts/bash/flankScripts.bat, test_runner/src/main/kotlin/ftl/gc/UserAuth.kt, test_runner/src/test/kotlin/ftl/run/status/MultiLinePrinterTest.kt
Fixes #1290 
Integration tests should work on windows.
=> fix: Integration tests on windows

.github/workflows/release.yml, flank-actions/sendMessage.kts
Fixes #1332 
Flank job publish properly snapshot versions
=> fix: Publishing Flank snapshot

.github/workflows/full_suite_integration_tests.yml
This PR adds a missing step which is essential for proper IT workflow
=> ci: Add create google account config step

.github/workflows/full_suite_integration_tests.yml, flank-scripts/build.gradle.kts, flank-scripts/src/main/kotlin/flank/scripts/integration/PrepareMessage.kt, flank-scripts/src/test/kotlin/flank/scripts/integration/ProcessResultTest.kt
Artifacts are not resolved when the `assemble` task is used. Change it to `build`
=> ci: Change gradle command

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt, firebase_apis/json/testing_v1.json, firebase_apis/test_api/build.gradle.kts, firebase_apis/test_api/src/main/java/com/google/testing/model/IosModel.java
Changes: 
* update google api client
* move client dependency to the common source of truth, which will allow to update client automatically
No new logic introduced. Normal build + integration tests should be enough (will be handled by GH actions)
=> refactor: Update firebase_apis module

.github/workflows/full_suite_integration_tests.yml
A small change in IT workflow. Comments now have the build scan URL.
=> ci: Change IT workflow comment

.github/workflows/update_dependencies_and_client.yml
Adds missing `checkout` step in dependencies workflow
=> ci: Add missing step

.github/workflows/ubuntu-workflow.yml
Fixes #1441 
Performance tests do not fail on ubuntu-workflow
=> fix: CI failures on performance tests

docs/analytics_comparsion.md
=> docs: Choose analytics tool

build.gradle.kts
Kt lint is enabled also for tests
=> style: Add Kotlin Lint to tests

integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare, integration_tests/src/test/resources/compare/GameloopIT-ios-compare
Fixes #1524 
1. We can consider it works correctly when IT are succeeded
=> test: Add missing iOS options in IT

.github/workflows/full_suite_integration_tests.yml
Fixes #1527 
Run @flank-it to see if it passes succesfully
.
=> ci: Windows integration test

.github/workflows/full_suite_integration_tests.yml, test_runner/src/main/kotlin/ftl/ios/xctest/common/InstallParseBinaries.kt
=> fix: IT test fix

docs/flank-github-action/flank_github_acton_sdd.md
=> docs: Fix SDD for Github action

.github/workflows/release_flank_scripts.yml, flank-scripts/build.gradle.kts
- Token was missing
- Title has unnecessary characters
Flank-scripts is released without any problems. See #1618 for more details
=> fix: Releasing flank-scripts

.github/workflows/create_new_release.yml, .github/workflows/full_suite_integration_tests.yml, .github/workflows/pr_checks.yml, .github/workflows/release.yml, .github/workflows/release_flank_scripts.yml, .github/workflows/release_notes_generation.yml, .github/workflows/update_dependencies_and_client.yml, flank-scripts/build.gradle.kts
- Github CLI needs authentication
Flank-scripts is released without any problems. See #1618 for more details
=> fix: Authenticate in Github CLI before release Flank-Scripts

.github/workflows/full_suite_integration_tests.yml
Fixes #1553 
> Unfortunately will only know once its merged into Master.
=> feat: Part 1 of multiple OS IT tests

.github/workflows/full_suite_integration_tests.yml
=> fix: Spacing fix for yml file

.github/workflows/full_suite_integration_tests.yml, integration_tests/src/test/resources/compare/AllTestFilteredIT-android-compare, integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare, integration_tests/src/test/resources/compare/GameloopIT-android-compare, integration_tests/src/test/resources/compare/GameloopIT-ios-compare, integration_tests/src/test/resources/compare/IgnoreFailedIT-compare, integration_tests/src/test/resources/compare/MultipleApksIT-compare, integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare, integration_tests/src/test/resources/compare/RunTimeoutIT-compare, integration_tests/src/test/resources/compare/SanityRoboIT-compare, integration_tests/src/test/resources/compare/TestFilteringIT-compare
Fixes #1628 
1. Integration tests pass
=> fix: Update compare files in IT

flank-scripts/build.gradle.kts, flank-scripts/src/main/kotlin/flank/scripts/cli/integrationtests/ProcessResultCommand.kt, flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/ProcessIntegrationTestsResult.kt, flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/ITResult.kt, flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/IntegrationResultContext.kt, flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/PrepareMessage.kt, flank-scripts/src/test/kotlin/flank/scripts/ops/integrationtests/DummyITRunState.kt, flank-scripts/src/test/kotlin/flank/scripts/ops/integrationtests/ProcessResultTest.kt
Fixes #1553 
Now handles 3 URLS
=> feat: Part 2 of IT tests

.github/workflows/release.yml
=> ci: Fix gradle command

.github/workflows/release.yml
=> fix: Publishing to maven central by running commands one by one

.github/workflows/release.yml
=> fix: reading PGP key in env

.github/workflows/release.yml
Github packages publishing works as expected
=> fix: publishing to GithubPackages

README.md, test_runner/build.gradle.kts
Snapshots are published to maven central
Badge from readme removed(because it does not work properly)
=> fix: Fix snapshot upload

.github/workflows/full_suite_integration_tests.yml
`env` variable should be parsed to JSON object
=> ci: Parse env object to JSON

.github/workflows/release.yml
This is merely 1 step in fixing #1595 
Github actions can only truly be tested when executed.
=> feat: Update Flank Slack release notifier

test_runner/src/main/kotlin/ftl/cli/firebase/test/AndroidCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/IosCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidLocalesCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidModelsCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidOrientationsCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidVersionsCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosLocalesCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosModelsCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosOrientationsCommand.kt, test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosVersionsCommand.kt
Fixes #1637 
Flank works as previously
=> refactor: Change packages of commands

integration_tests/src/test/kotlin/integration/MultipleDevicesIT.kt, integration_tests/src/test/resources/cases/flank_android_multiple_devices.yml, integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
=> fix: Remove physical device from integration tests

.github/workflows/release.yml
Snapshots are published after each merge to master
=> ci: Fix publishing snapshots

action.yml
=> fix: white space in Github action

test_runner/build.gradle.kts
Fixes #1731 
This is follow up fix for #1724 
1. run`./gradlew flankFullRun` -- no errors
2. IT passes
=> fix: Follow up refactor fix

junit_html_report/package-lock.json
=> build(deps): Fix dependabot security vulnerabilities

junit_html_report/package-lock.json, junit_html_report/package.json
Fix dependabot security vulnerabilities
=> build: Fix dependabot security vulnerabilities

flank-scripts/build.gradle.kts, flank-scripts/src/test/kotlin/flank/scripts/ops/testartifacts/TestArtifactsRepoTest.kt
Fixes #1769
Mac-os build finished without errors
=> fix: Fix flank-scripts test failure on MacOS

integration_tests/src/test/kotlin/integration/DumpShardsIT.kt, integration_tests/src/test/kotlin/utils/MatrixTestShards.kt
=> test: Update DumpShardsIT

integration_tests/src/test/kotlin/integration/CustomShardingIT.kt
Fixes #1795
2. run `./gradlew integrationTests --tests CustomShardingIT` on windows :exclamation:
3. no errors 🎉
=> test: 1795 update custom sharding it

.github/workflows/ubuntu-workflow.yml
=> fix: CI issues on ubuntu

integration_tests/build.gradle.kts
Fixes #1838 
IT are green and happy again
=> test: Update task ordering

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt, corellium/adapter/build.gradle.kts, corellium/adapter/src/main/kotlin/flank/corellium/adapter/ParseTestApk.kt, corellium/adapter/src/test/kotlin/flank/corellium/adapter/ParseTestApkTest.kt, corellium/api/src/main/kotlin/flank/corellium/api/TestApk.kt, settings.gradle.kts, test_runner/build.gradle.kts
Fixes #1836 
The unit test is passing
=> feat: TestApk parser

test_runner/src/main/kotlin/ftl/domain/DescribeAndroidVersions.kt, test_runner/src/main/kotlin/ftl/environment/android/AndroidSoftwareVersionDescription.kt, test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/versions/AndroidVersionsDescribeCommand.kt, test_runner/src/test/kotlin/ftl/cli/firebase/test/android/versions/AndroidVersionsDescribeCommandTest.kt
Fixes #1848 
- Code is refactored according to #1848 
- Android describe models command works like previously
=> refactor: Refactor android versions logging

test_runner/src/main/kotlin/ftl/domain/DescribeIosModels.kt, test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/models/IosModelDescribeCommand.kt, test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/models/describe/IosModelDescription.kt, test_runner/src/test/kotlin/ftl/environment/ios/IosModelDescriptionTest.kt
Fixes #1850
- Code is refactored according to #1850
- iOS describe models command works like previously
=> refactor: Structural output iOS models describe

test_runner/src/main/kotlin/ftl/adapter/GoogleIpBlockFetch.kt, test_runner/src/main/kotlin/ftl/adapter/google/IpBlockAdapter.kt, test_runner/src/main/kotlin/ftl/api/IpBlock.kt, test_runner/src/main/kotlin/ftl/api/TestEnvironment.kt, test_runner/src/main/kotlin/ftl/domain/ListIPBlocks.kt, test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/environment/TestEnvironmentInfo.kt, test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ipblocks/IPBlocksListCommand.kt, test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ipblocks/IpBlocksToTable.kt, test_runner/src/test/kotlin/ftl/adapter/google/IpBlockAdapterTest.kt, test_runner/src/test/kotlin/ftl/adapter/google/OrientationsAdapterTest.kt
Fixes #1863 
2. run `flank ip-blocks list`
3. 🎉 
4. run `flank android test-environment`
5. 🎉 
6. repeat 4), 5) for `ios`
=> refactor: Ip blocks output

test_runner/src/main/kotlin/ftl/domain/ListIosLocales.kt, test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/locales/AndroidLocalesListCommand.kt, test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/configuration/IosLocalesListCommand.kt
Fixes #1859 
Works as intended and follows outline as set out in #1859
=> refactor: iOS List locales

.github/workflows/full_suite_integration_tests.yml, flank-scripts/build.gradle.kts, flank-scripts/src/main/kotlin/flank/scripts/cli/integrationtests/ProcessResultCommand.kt, flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/ProcessIntegrationTestsResult.kt, flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/IntegrationResultContext.kt
Remaining `ubuntu-latest` changed to `ubuntu-18.04`
=> ci: Remaining ubuntu-latest variables

junit_html_report/package-lock.json, junit_html_report/package.json
=> build: Fix dependabot alerts

.github/workflows/full_suite_integration_tests.yml, flank-scripts/build.gradle.kts, flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/IntegrationResultContext.kt
Processing result logic is now independent of OS version
=> ci: Make IT results independent of os versions

test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt, test_runner/src/main/kotlin/ftl/domain/ListAndroidVersions.kt, test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/versions/AndroidVersionsListCommand.kt, test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/versions/ListAndroidSofwareVersions.kt, test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/environment/TestEnvironmentInfo.kt, test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
Fixes #1858 
Refactored in accordance with #1858
=> refactor: list android versions

corellium/cli/build.gradle.kts, corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt, corellium/cli/src/main/kotlin/flank/corellium/cli/util/Config.kt, corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt, corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestAndroidCorellium.kt, settings.gradle.kts
=> feat: Corellium MVP CLI layer

integration_tests/src/test/kotlin/integration/DumpShardsIT.kt
=> fix: Enable dump shards IT

junit_html_report/package-lock.json, junit_html_report/package.json
No changes in production code. This PR is a replacement for dependant bot PR.
=> fix: Bump up trim-newlines version

docs/corellium/modules.puml, docs/corellium/run-test-android.puml
=> Fix diagrams

.github/workflows/create_new_release.yml, .github/workflows/release_notes_generation.yml
Small follow up issue for notification logic
=> ci: Slack notification follow up

.github/workflows/full_suite_integration_tests.yml, docs/index.md, test_runner/flank.yml
Fixes #2022 
Very minor option name change.
=> fix: Parameterized Tests name change

tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Parallel.kt, tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Execution.kt, tool/execution/parallel/src/test/kotlin/flank/exection/parallel/Example.kt, tool/execution/parallel/src/test/kotlin/flank/exection/parallel/ExecuteKtTest.kt
=> feat: Add option for running parallel tasks as synchronized sequence.

corellium/sandbox/build.gradle.kts
Comment out legacy tasks and `shardowJar` plugin for `:corellium:sandbox`.
This module is not used for a long time but increases build time.
=> chore: Speeds up build disabling shardowJar plugin for :corellium:sandbox

test_runner/src/main/kotlin/ftl/adapter/GoogleUserAuthorizationRequest.kt, test_runner/src/main/kotlin/ftl/api/UserAuthorization.kt, test_runner/src/main/kotlin/ftl/client/google/UserAuth.kt, test_runner/src/main/kotlin/ftl/domain/LoginGoogleAccount.kt, test_runner/src/main/kotlin/ftl/presentation/cli/auth/LoginCommand.kt
Fixes #1866
All outputs logs and behavior of command `flank auth login` works like previously
=> refactor: Structural output login google

test_runner/src/main/kotlin/ftl/client/google/AppDetails.kt, test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
Fixes #2109 
No directly 'visible' changes. Flank should proceed normally.
=> feat: Get apk details with retry

.github/workflows/action_it_tests.yml
Fixes #1702 
The github action executes monthly and runs succesfully.
Its not about testing the integrity of the IT tests but the Flank action itself.
=> ci: Simple GHA Dogfood script

build.gradle.kts, corellium/adapter/build.gradle.kts, corellium/domain/build.gradle.kts, integration_tests/build.gradle.kts, tool/analytics/build.gradle.kts, tool/analytics/mixpanel/build.gradle.kts, tool/config/build.gradle.kts, tool/execution/parallel/build.gradle.kts
Fixes #1926 
Build output does not produce warning(except the important ones)
=> build: Fix build warnings

gradle.properties, test_runner/build.gradle.kts
=> chore: Fix GitHub Actions CI jobs

docs/index.md
=> docs: Use correct proxy property names.

test_runner/src/main/resources/android_catalog.json, test_runner/src/main/resources/ios_catalog.json
=> chore: Update device catalog

docs/exit_codes_and_exceptions.md, test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt, test_runner/src/main/kotlin/ftl/run/exception/FlankException.kt, test_runner/src/main/kotlin/ftl/run/exception/FlankExitCodes.kt, test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt, test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt, test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt, test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
=> feat: Exit with code 3 when there are no tests

.github/workflows/codeql.yml
Removes unused languages from codeql.yml.
=> chore: Update codeql languages

docs/flank-scripts/ops_structure.md, docs/flank_secrets.md, docs/index.md, flank-scripts/src/test/kotlin/flank/scripts/ops/dependencies/testfiles/ExpectedTestVersionsAfterUpdateVersion, flank-scripts/src/test/kotlin/flank/scripts/ops/dependencies/testfiles/ExpectedVersionAfterPluginDependencies, flank-scripts/src/test/kotlin/flank/scripts/ops/dependencies/testfiles/ExpectedVersionAfterUpdateDependencies, flank-scripts/src/test/kotlin/flank/scripts/ops/dependencies/testfiles/TestPlugins, flank-scripts/src/test/kotlin/flank/scripts/ops/dependencies/testfiles/TestVersions, flank-scripts/src/test/kotlin/flank/scripts/ops/dependencies/testfiles/build.gradle.kts.test, flank-scripts/src/test/kotlin/flank/scripts/ops/dependencies/testfiles/report.json, integration_tests/build.gradle.kts
=> chore: Remove references to JFrog and Bintray

.github/workflows/create_new_release.yml
Also add ability to manually dispatch via `workflow_dispatch`.
=> chore: Update create new release workflow with new bot

.github/workflows/create_new_release.yml
=> chore: Update create_new_release workflow to be manually run

.github/workflows/scorecards.yml
fixes broken scorecard action
https://github.com/ossf/scorecard-action/issues/998
=> ci: update scorecard-action version

buildSrc/src/main/kotlin/Versions.kt
* BEN_MANES  0.42.0 -> 0.47.0
* COMMON_TEXT  1.9 -> 1.10.0
* DD_PLIST  1.23 -> 1.27
* GOOGLE_AUTH  1.17.0 -> 1.18.0
* GOOGLE_NIO  0.124.7 -> 0.126.17
* GOOGLE_STORAGE  2.16.0 -> 2.22.4
* GSON  2.9.0 -> 2.10.1
* JCABI_GITHUB  1.2.0 -> 1.6.4
* JSON  20220320 -> 20230618
* KOTLIN  1.8.21 -> 1.8.22
* KTOR  2.0.3 -> 2.3.1
* PICOCLI  4.6.3 -> 4.7.4
Unit and integration tests pass
.
=> fix: Update out of date dependencies

test_runner/src/main/kotlin/ftl/client/google/GcToolResults.kt, test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt
=> fix: point authentication error message link to correct/relevant docs

.github/workflows/ubuntu_workflow.yml
=> ci: update ubuntu_workflow to use env vars
